### ISSUE TITLE
Yarn dev fails on Linux Subsystem for Windows 10

### ISSUE THREAD

**Issue by jonathontoon** [electron-react-boilerplate/electron-react-boilerplate#1748]
I've been using this boilerplate without issue for most of the year on my [project](https://github.com/jonathontoon/tweet-tray) so just wanted to first say thanks for all the hard work!

However revisiting the project after a few months, now that I'm running the Linux Subsystem for Windows 10, I cannot seem to compile anything when running `yarn dev`.

My setup:
**Windows**: Version 1803 OS Build 17134.228
**Linux Subsystem**: 16.04.4 LTS (Xenial Xerus)
**Node**: v9.10.0
**Npm**: 5.6.0
**Yarn**: 1.7.0
```
yarn dev
yarn run v1.7.0
$ cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js
Starting Main Process...
electron-react-boilerplate@0.14.0 start-main-dev /mnt/c/users/[user]/src/electron-react-boilerplate
cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.14.0 start-main-dev: 'cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.14.0 start-main-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/[user]/.npm/_logs/2018-09-03T11_53_01_899Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                               
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I've also tried to obtain the debug logs but the log files themselves are simply empty.

Side note, I've been able to compile my project and a fresh clone of the boilerplate on my macOS machine running 10.13.6 with no problems.

Let me know if I can provide anything else, cheers!

**Comment by amilajack** [comment]
Upload the logs please

**Comment by jonathontoon** [comment]
Thanks for the help. Logs attached from an attempt earlier today.

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/[user]/.nvm/versions/node/v9.10.0/bin/node',
1 verbose cli   '/home/[user]/.nvm/versions/node/v9.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]2 info using npm@5.6.03 info using node@v9.10.04 verbose run-script [ 'predev', 'dev', 'postdev' ]5 info lifecycle electron-react-boilerplate@0.14.0~predev: electron-react-boilerplate@0.14.06 info lifecycle electron-react-boilerplate@0.14.0~dev: electron-react-boilerplate@0.14.07 verbose lifecycle electron-react-boilerplate@0.14.0~dev: unsafe-perm in lifecycle true8 verbose lifecycle electron-react-boilerplate@0.14.0~dev: PATH: /home/[user]/.nvm/versions/node/v9.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/users/[user]/src/electron-react-boilerplate/node_modules/.bin:/home/[user]/gems/bin:/home/[user]/.nvm/versions/node/v9.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Ruby23-x64/bin:/mnt/c/Users/[user]/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/[user]/AppData/Local/hyper/app-2.0.0/resources/bin:/mnt/c/Users/[user]/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/[user]/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/[user]/AppData/Local/GitHubDesktop/bin9 verbose lifecycle electron-react-boilerplate@0.14.0~dev: CWD: /mnt/c/users/[user]/src/electron-react-boilerplate10 silly lifecycle electron-react-boilerplate@0.14.0~dev: Args: [ '-c',10 silly lifecycle   'cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev' ]11 silly lifecycle electron-react-boilerplate@0.14.0~dev: Returned: code: 1  signal: null12 info lifecycle electron-react-boilerplate@0.14.0~dev: Failed to exec dev script
13 verbose stack Error: electron-react-boilerplate@0.14.0 dev: `cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/[user]/.nvm/versions/node/v9.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/[user]/.nvm/versions/node/v9.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid electron-react-boilerplate@0.14.0
15 verbose cwd /mnt/c/users/[user]/src/electron-react-boilerplate
16 verbose Linux 4.4.0-17134-Microsoft17 verbose argv "/home/[user]/.nvm/versions/node/v9.10.0/bin/node" "/home/[user]/.nvm/versions/node/v9.10.0/bin/npm" "run" "dev"
18 verbose node v9.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-react-boilerplate@0.14.0 dev: `cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev`
22 error Exit status 1
23 error Failed at the electron-react-boilerplate@0.14.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
"2018-09-03T11_25_26_156Z-debug.log" 38L, 4117C
```
