### ISSUE TITLE
"Uncaught Error: Cannot find module 'moment'" and other issues

### ISSUE THREAD

**Issue by webpleb** [electron-react-boilerplate/electron-react-boilerplate#1859]
## Prerequisites

- Using yarn
- Using an up-to-date master branch

## Expected Behavior

Correctly package my application

##### Issues here:
- filterDepWithoutEntryPoints: "SyntaxError: Unexpected token v in JSON at position 0"
- Building the application for rpm doesn't work

yarn run v1.10.1
$ yarn build && electron-builder build --publish never
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config ./configs/webpack.config.main.prod.js --colors
$ cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config ./configs/webpack.config.renderer.prod.js --colors
[1] SyntaxError: Unexpected token v in JSON at position 0
[1]     at JSON.parse (<anonymous>)
[1]     at filterDepWithoutEntryPoints (/home/clay/Company/newBoilderplate/Application/configs/webpack.config.base.js:24:22)
[1]     at Array.filter (<anonymous>)
[1]     at Object.<anonymous> (/home/clay/Company/newBoilderplate/Application/configs/webpack.config.base.js:36:45)
[1]     at Module._compile (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
[1]     at loader (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (internal/modules/cjs/loader.js:599:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[1]     at Module.require (internal/modules/cjs/loader.js:637:17)
[1]     at require (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[1]     at Object.<anonymous> (/home/clay/Company/newBoilderplate/Application/configs/webpack.config.renderer.prod.js:12:1)
[1]     at Module._compile (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
[1]     at loader (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (internal/modules/cjs/loader.js:599:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[1]     at Module.require (internal/modules/cjs/loader.js:637:17)
[1]     at require (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[1]     at WEBPACK_OPTIONS (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:133:13)
[1]     at requireConfig (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:135:6)
[1]     at /home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:142:17
[1]     at Array.forEach (<anonymous>)
[1]     at module.exports (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:140:15)
[1]     at yargs.parse (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/cli.js:241:39)
[1]     at Object.parse (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/node_modules/yargs/yargs.js:563:18)
[1]     at /home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/cli.js:219:8
[1]     at Object.<anonymous> (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/cli.js:530:3)
[1]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[1]     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:152:7)
[1]     at Module.load (internal/modules/cjs/loader.js:599:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0] SyntaxError: Unexpected token v in JSON at position 0
[0]     at JSON.parse (<anonymous>)
[0]     at filterDepWithoutEntryPoints (/home/clay/Company/newBoilderplate/Application/configs/webpack.config.base.js:24:22)
[0]     at Array.filter (<anonymous>)
[0]     at Object.<anonymous> (/home/clay/Company/newBoilderplate/Application/configs/webpack.config.base.js:36:45)
[0]     at Module._compile (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
[0]     at loader (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:144:5)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:154:7)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0]     at require (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[0]     at Object.<anonymous> (/home/clay/Company/newBoilderplate/Application/configs/webpack.config.main.prod.js:10:1)
[0]     at Module._compile (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
[0]     at loader (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:144:5)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:154:7)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0]     at require (/home/clay/Company/newBoilderplate/Application/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[0]     at WEBPACK_OPTIONS (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:133:13)
[0]     at requireConfig (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:135:6)
[0]     at /home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:142:17
[0]     at Array.forEach (<anonymous>)
[0]     at module.exports (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/convert-argv.js:140:15)
[0]     at yargs.parse (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/cli.js:241:39)
[0]     at Object.parse (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/node_modules/yargs/yargs.js:563:18)
[0]     at /home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/cli.js:219:8
[0]     at Object.<anonymous> (/home/clay/Company/newBoilderplate/Application/node_modules/webpack-cli/bin/cli.js:530:3)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/home/clay/Company/newBoilderplate/Application/node_modules/babel-register/lib/node.js:152:7)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0] Hash: dca761516895a32b5fdd
[0] Version: webpack 4.16.3
[0] Time: 6577ms
[0] Built at: 10/18/2018 5:51:05 PM
[0]                  Asset     Size  Chunks             Chunk Names
[0]     ./app/main.prod.js  112 KiB       0  [emitted]  main
[0] ./app/main.prod.js.map  462 KiB       0  [emitted]  main
[0] Entrypoint main = ./app/main.prod.js ./app/main.prod.js.map
[0] [./app/main.dev.js] 3.15 KiB {0} [built]
[0] [./app/menu.js] 6.28 KiB {0} [built]
[0] [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {0} [built]
[0] [assert] external "assert" 42 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [module] external "module" 42 bytes {0} [built]
[0] [net] external "net" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [tty] external "tty" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 47 hidden modules
[0] 
[0] WARNING in ./node_modules/electron-debug/index.js 101:45-58
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.js
[0] 
[0] WARNING in ./node_modules/electron-debug/index.js 102:61-74
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.js
[0] yarn build-main exited with code 0
[1] Hash: 4be54ab68e12663c5e34
[1] Version: webpack 4.16.3
[1] Time: 39087ms
[1] Built at: 10/18/2018 5:51:38 PM
[1]                Asset      Size  Chunks             Chunk Names
[1]     renderer.prod.js  6.06 MiB       0  [emitted]  main
[1] renderer.prod.js.map  11.1 MiB       0  [emitted]  main
[1] Entrypoint main = renderer.prod.js renderer.prod.js.map
[1] [./app/Appi.js] 5.54 KiB {0} [built]
[1] [./app/assets/jss/App/index.js] 9.04 KiB {0} [built]
[1] [./app/assets/jss/Container/container.js] 948 bytes {0} [built]
[1] [./app/containers/AppBarContainer/index.js] 2.69 KiB {0} [built]
[1] [./app/features/shared/ui/index.js] 399 bytes {0} [built]
[1] [./app/index.js] 2.84 KiB {0} [built]
[1] [./app/store/index.js] 3.51 KiB {0} [built]
[1] [./app/store/middleware/index.js] 1.56 KiB {0} [built]
[1] [./app/store/rootReducer/index.js] 1.1 KiB {0} [built]
[1] [./app/store/routes/index.js] 3.4 KiB {0} [built]
[1] [./node_modules/history/es/index.js] ./node_modules/history/es/index.js + 9 modules 34.8 KiB {0} [built]
[1]     |    10 modules
[1] [./node_modules/react-redux/es/index.js] ./node_modules/react-redux/es/index.js + 24 modules 43.2 KiB {0} [built]
[1]     |    25 modules
[1] [./node_modules/redux-persist/es/index.js] ./node_modules/redux-persist/es/index.js + 11 modules 22.1 KiB {0} [built]
[1]     |    12 modules
[1] [./node_modules/redux-saga/es/index.js] ./node_modules/redux-saga/es/index.js + 4 modules 30 KiB {0} [built]
[1]     |    5 modules
[1] [moment] external "moment" 42 bytes {0} [built]
[1]     + 5894 hidden modules
[1] yarn build-renderer exited with code 0
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.6 appOutDir=release/linux-unpacked
  • building        target=snap arch=x64 file=release/electron-react-boilerplate_0.16.0_amd64.snap
  • building        target=AppImage arch=x64 file=release/electron-react-boilerplate-0.16.0-x86_64.AppImage
  • building        target=deb arch=x64 file=release/electron-react-boilerplate_0.16.0_amd64.deb
  • building        target=rpm arch=x64 file=release/electron-react-boilerplate-0.16.0.x86_64.rpm
Error: Exit code: 1. Command failed: /home/clay/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t rpm --architecture amd64 --name electron-react-boilerplate --force --after-install /tmp/temp-dir-FTeMe1/0-after-install --after-remove /tmp/temp-dir-FTeMe1/2-after-remove --description Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development --version 0.16.0 --package /home/clay/Company/newBoilderplate/Application/release/electron-react-boilerplate-0.16.0.x86_64.rpm --maintainer John Doe <johndoe@gmail.com> --url https://github.com/electron-react-boilerplate/electron-react-boilerplate#readme --vendor John Doe <johndoe@gmail.com> --rpm-compression xzmt --rpm-os linux --depends libnotify --depends libappindicator --depends libXScrnSaver --license MIT /home/clay/Company/newBoilderplate/Application/release/linux-unpacked/=/opt/ElectronReact /home/clay/Company/newBoilderplate/Application/resources/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/64x64.png=/usr/share/icons/hicolor/64x64/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/electron-react-boilerplate.png /home/clay/Company/newBoilderplate/Application/resources/icons/1024x1024.png=/usr/share/icons/hicolor/1024x1024/apps/electron-react-boilerplate.png /tmp/temp-dir-FTeMe1/5-ElectronReact.desktop=/usr/share/applications/electron-react-boilerplate.desktop

{:timestamp=>"2018-10-18T17:54:13.814632+0200", :message=>"Need executable 'rpmbuild' to convert dir to rpm", :level=>:error}

    at /home/clay/Company/newBoilderplate/Application/node_modules/builder-util/src/util.ts:128:16
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
From previous event:
    at FpmTarget.build (/home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/targets/fpm.ts:232:43)
    at /home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/platformPackager.ts:130:24
From previous event:
    at AsyncTaskManager.add (/home/clay/Company/newBoilderplate/Application/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/platformPackager.ts:122:17)
    at /home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at LinuxPackager.pack (/home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/clay/Company/newBoilderplate/Application/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/clay/Company/newBoilderplate/Application/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /home/clay/Company/newBoilderplate/Application/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/clay/Company/newBoilderplate/Application/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:139:20)
From previous event:
    at Packager._build (/home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/home/clay/Company/newBoilderplate/Application/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/home/clay/Company/newBoilderplate/Application/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/clay/Company/newBoilderplate/Application/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at Object.args [as handler] (/home/clay/Company/newBoilderplate/Application/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/home/clay/Company/newBoilderplate/Application/node_modules/electron-builder/node_modules/yargs/lib/command.js:237:44)
    at Object.parseArgs [as _parseArgs] (/home/clay/Company/newBoilderplate/Application/node_modules/electron-builder/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/home/clay/Company/newBoilderplate/Application/node_modules/electron-builder/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/home/clay/Company/newBoilderplate/Application/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
clay@OKlayCOMPUTER:~/Company/newBoilderplate/G$ 

##### Obviously persist and rehydrate of the redux store are triggered, but then 'moment' isn't found

persist/PERSIST 
module.js:545 Uncaught Error: Cannot find module 'moment'
    at Module._resolveFilename (module.js:543)
    at Function.Module._resolveFilename (/home/clay/Company/newBoilderplate//Application//release/linux-unpacked/resources/electron.asar/common/reset-search-paths.js:35)
    at Function.Module._load (module.js:473)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at Object.moment (external "moment":1)
    at l (bootstrap:19)
    at Object../node_modules/material-ui-pickers/utils/moment-utils.js (moment-utils.js:8)
    at l (bootstrap:19)
    at Object../app/Appi.js (Appi.js:4)
persist/REHYDRATE 

#### Edit: Sorry, forgot to mention: when I copied my application into this boilerplate, I only modified the depencies in the outer package.json and installed the depencies. In dev mode it worked fine. Here is said package.json:

{
  "name": "electron-react-boilerplate",
  "productName": "ElectronReact",
  "version": "0.16.0",
  "description": "Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development",
  "scripts": {
    "build": "concurrently \"yarn build-main\" \"yarn build-renderer\"",
    "build-dll": "cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config ./configs/webpack.config.renderer.dev.dll.js --colors",
    "build-e2e": "cross-env E2E_BUILD=true yarn build",
    "build-main": "cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config ./configs/webpack.config.main.prod.js --colors",
    "build-renderer": "cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config ./configs/webpack.config.renderer.prod.js --colors",
    "dev": "cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev",
    "electron-rebuild": "electron-rebuild --parallel --force --types prod,dev,optional --module-dir app",
    "flow": "flow",
    "flow-typed": "rimraf flow-typed/npm && flow-typed install --overwrite || true",
    "lint": "cross-env NODE_ENV=development eslint --cache --format=pretty .",
    "lint-fix": "yarn --silent lint --fix; exit 0",
    "lint-styles": "stylelint --ignore-path .eslintignore '**/*.*(css|scss)' --syntax scss",
    "lint-styles-fix": "yarn --silent lint-styles --fix; exit 0",
    "package": "yarn build && electron-builder build --publish never",
    "package-all": "yarn build && electron-builder build -mwl",
    "package-ci": "yarn postinstall && yarn build && electron-builder --publish always",
    "package-linux": "yarn build && electron-builder build --linux",
    "package-win": "yarn build && electron-builder build --win --x64",
    "postinstall": "node -r babel-register internals/scripts/CheckNativeDep.js && yarn flow-typed && yarn build-dll && electron-builder install-app-deps package.json",
    "postlint-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.{*{js,jsx,json},babelrc,eslintrc,prettierrc,stylelintrc}'",
    "postlint-styles-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.{css,scss}'",
    "precommit": "lint-staged",
    "prestart": "yarn build",
    "start": "cross-env NODE_ENV=production electron ./app/",
    "start-main-dev": "cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js",
    "start-renderer-dev": "cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config configs/webpack.config.renderer.dev.js",
    "test": "cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 node --trace-warnings -r babel-register ./internals/scripts/RunTests.js",
    "test-all": "yarn lint && yarn flow && yarn build && yarn test && yarn build-e2e && yarn test-e2e",
    "test-e2e": "node -r babel-register ./internals/scripts/CheckBuiltsExist.js && cross-env NODE_ENV=test testcafe electron:./app ./test/e2e/HomePage.e2e.js",
    "test-e2e-live": "node -r babel-register ./internals/scripts/CheckBuiltsExist.js && cross-env NODE_ENV=test testcafe-live electron:./app ./test/e2e/HomePage.e2e.js",
    "test-watch": "yarn test --watch"
  },
  "browserslist": "electron 1.6",
  "lint-staged": {
    "*.{js,jsx}": [
      "cross-env NODE_ENV=development eslint --cache --format=pretty",
      "prettier --ignore-path .eslintignore --single-quote --write",
      "git add"
    ],
    "{*.json,.{babelrc,eslintrc,prettierrc,stylelintrc}}": [
      "prettier --ignore-path .eslintignore --parser json --write",
      "git add"
    ],
    "*.{css,scss}": [
      "stylelint --ignore-path .eslintignore --syntax scss --fix",
      "prettier --ignore-path .eslintignore --single-quote --write",
      "git add"
    ],
    "*.{yml,md}": [
      "prettier --ignore-path .eslintignore --single-quote --write",
      "git add"
    ]
  },
  "build": {
    "productName": "ElectronReact",
    "appId": "org.develar.ElectronReact",
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": [
        "nsis",
        "msi"
      ]
    },
    "linux": {
      "target": [
        "deb",
        "rpm",
        "snap",
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "buildResources": "resources",
      "output": "release"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron-react-boilerplate/electron-react-boilerplate.git"
  },
  "contributors": [
    {
      "name": "Vikram Rangaraj",
      "email": "vikr01@icloud.com",
      "url": "https://github.com/vikr01"
    },
    {
      "name": "Amila Welihinda",
      "email": "amilajack@gmail.com",
      "url": "https://github.com/amilajack"
    }
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues"
  },
  "keywords": [
    "electron",
    "boilerplate",
    "react",
    "redux",
    "flow",
    "sass",
    "webpack",
    "hot",
    "reload"
  ],
  "homepage": "https://github.com/electron-react-boilerplate/electron-react-boilerplate#readme",
  "jest": {
    "testURL": "http://localhost/",
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/internals/mocks/fileMock.js",
      "\\.(css|less|sass|scss)$": "identity-obj-proxy"
    },
    "moduleFileExtensions": [
      "js",
      "jsx",
      "json"
    ],
    "moduleDirectories": [
      "node_modules",
      "app/node_modules"
    ],
    "transform": {
      "^.+\\.jsx?$": "babel-jest"
    },
    "setupFiles": [
      "./internals/scripts/CheckBuiltsExist.js"
    ]
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.6",
    "babel-jest": "^23.4.2",
    "babel-loader": "^7.1.5",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-flow-runtime": "^0.17.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "chalk": "^2.4.1",
    "concurrently": "^3.6.1",
    "connected-react-router": "^4.4.1",
    "cross-env": "^5.2.0",
    "cross-spawn": "^6.0.5",
    "css-loader": "^1.0.0",
    "detect-port": "^1.2.3",
    "electron": "^2.0.6",
    "electron-builder": "^20.28.4",
    "electron-devtools-installer": "^2.2.4",
    "electron-rebuild": "^1.8.2",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.4",
    "eslint": "^5.2.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-formatter-pretty": "^1.3.0",
    "eslint-import-resolver-webpack": "^0.10.1",
    "eslint-plugin-compat": "^2.5.1",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jest": "^21.18.0",
    "eslint-plugin-jsx-a11y": "6.1.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-react": "^7.10.0",
    "eslint-plugin-testcafe": "^0.2.1",
    "fbjs-scripts": "^0.8.3",
    "file-loader": "^1.1.11",
    "flow-bin": "^0.77.0",
    "flow-runtime": "^0.17.0",
    "flow-typed": "^2.5.1",
    "husky": "^0.14.3",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^23.4.2",
    "lint-staged": "^7.2.0",
    "mini-css-extract-plugin": "^0.4.1",
    "node-sass": "^4.9.2",
    "optimize-css-assets-webpack-plugin": "^5.0.0",
    "prettier": "^1.14.3",
    "react-test-renderer": "^16.4.1",
    "redux-logger": "^3.0.6",
    "rimraf": "^2.6.2",
    "sass-loader": "^7.0.3",
    "sinon": "^6.1.4",
    "spectron": "^3.8.0",
    "style-loader": "^0.21.0",
    "stylelint": "^9.4.0",
    "stylelint-config-prettier": "^4.0.0",
    "stylelint-config-standard": "^18.2.0",
    "testcafe": "^0.21.1",
    "testcafe-browser-provider-electron": "^0.0.6",
    "testcafe-live": "^0.1.3",
    "testcafe-react-selectors": "^3.0.0",
    "uglifyjs-webpack-plugin": "1.2.7",
    "url-loader": "^1.0.1",
    "webpack": "^4.16.3",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5",
    "webpack-merge": "^4.1.3",
    "yarn": "^1.9.2"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.2.0",
    "@material-ui/core": "^3.1.0",
    "@material-ui/icons": "^3.0.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
    "classnames": "^2.2.6",
    "devtron": "^1.4.0",
    "electron-debug": "^2.0.0",
    "extract-text-webpack-plugin": "^3.0.1",
    "fixed-data-table": "^0.6.5",
    "history": "^4.7.2",
    "html-webpack-plugin": "^2.28.0",
    "jwt-decode": "^2.2.0",
    "material-ui-pickers": "^1.0.0-rc.14",
    "moment": "^2.22.2",
    "primeicons": "^1.0.0-beta.10",
    "primereact": "^2.0.0-beta.1",
    "prop-types": "^15.6.2",
    "query-string": "^6.1.0",
    "react": "^16.4.1",
    "react-bootstrap": "^0.32.1",
    "react-bootstrap-table": "^4.3.1",
    "react-burger-menu": "^2.5.2",
    "react-dom": "^16.4.1",
    "react-hot-loader": "^4.3.4",
    "react-redux": "^5.0.7",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-to-print": "^2.0.0-alpha-3",
    "redux": "^4.0.0",
    "redux-actions": "^2.6.1",
    "redux-form": "^7.4.2",
    "redux-persist": "^5.10.0",
    "redux-persist-transform-filter": "0.0.18",
    "redux-saga": "^0.16.0",
    "redux-thunk": "^2.3.0",
    "source-map-support": "^0.5.6"
  },
  "devEngines": {
    "node": ">=7.x",
    "npm": ">=4.x",
    "yarn": ">=0.21.3"
  }
}

## Possible Solution

It's probably because of a webpack config, but I'm a bloody beginner when it comes to webpack

## Context

I am developing a electron-react-webpack application. Until now I used another electron-react-webpack boilerplate which worked fine in dev mode, but didn't package the project. That boilerplate isn't maintained at all.
So I decided to switch to this boilerplate and everything about the default counter app worked fine. Then I inserted my application "on top" of this boilerplate and it worked fine in dev mode, too. 

But when I package the project and run it (release/linux-unpacked), the above issues appear.
I didn't find solutions for the above issues yet and they're probably easy to fix, but I'm new to webpack and electron, so it would be great if someone could help me here or direct me in the right direction. 

Also, this is my first issue on github, please tell me if I made a mistake!

Thanks in advance!

## Your Environment

- Node version : 10.9.0
- Version or Branch used : Master, latest version
- Operating System and version : Ubuntu 18.04.1

**Comment by webpleb** [comment]
Update: Fixed the issue myself, it was caused by my own reluctance to reading the docs of each piece of software I need (webpack in this case. I know, it's important, but I'm new to web dev and it really is a frustrating mess at times). 

#### If anyone encounters a similar problem, let me know and I'll try to help.

Kudos to the devs!

**Comment by avinashroy** [comment]
What is your solution, i am having this same issue

**Comment by webpleb** [comment]
I already forgot the exact steps I took, but the main part of the solution was to put the 'moment' dependency into the inner package.json (which doesn't have any dependencies in the boilerplate), so it's treated as an external. Back then I read somewhere that this module has caused similar issues before. Let me know if this helped!
