### ISSUE TITLE
MPV.JS works with npm install, but gives errors with yarn.

### ISSUE THREAD

**Issue by oguzkulcu** [electron-react-boilerplate/electron-react-boilerplate#2106]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.0.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

https://github.com/Kagami/mpv.js/ I'm installing the plugin in this link. But I'm getting an error. When I do npm install, I can build it. When I try to install with Yarn, it gives an error.

## Current Behavior

I'm getting the following error when I'm doing mpv.js in yarn add. I am not getting the error when I do npm install.

```
• rebuilding native dependency name=mpv.js
Error: /usr/local/Cellar/node/11.4.0/bin/node exited with code 1
Output:
yarn run v1.12.3
$ prebuild-install -t 1.0.0 || node-gyp rebuild
  CXX(target) Release/obj.target/mpvjs/index.o
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
prebuild-install WARN install No prebuilt binaries found (target=1.0.0 runtime=electron arch=x64 platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.6.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/11.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/mpv.js/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/11.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/oguzhankulcu/.electron-gyp/iojs-3.0.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/oguzhankulcu/.electron-gyp/iojs-3.0.13',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/11.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/oguzhankulcu/.electron-gyp/iojs-3.0.13/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/mpv.js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../index.cc:9:10: fatal error: 'GLES2/gl2.h' file not found
#include <GLES2/gl2.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/mpvjs/index.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/11.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.4.0/bin/node" "/usr/local/Cellar/node/11.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/mpv.js
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:276:13)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:188:13)
    at Pipe._handle.close (net.js:610:12)
From previous event:
    at processImmediate (timers.js:632:19)
From previous event:
    at /Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/app-builder-lib/src/util/yarn.ts:155:24
From previous event:
    at _rebuild (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at _installOrRebuild (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at _installAppDeps (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/electron-builder/out/cli/install-app-deps.js:176:26)
    at installAppDeps (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/electron-builder/out/cli/install-app-deps.js:144:26)
    at then (/Users/oguzhankulcu/Desktop/limitsiz-masaustu/node_modules/electron-builder/src/cli/cli.ts:46:19)
error Command failed with exit code 1.

```

## Your Environment

- Node version : v10.15.0
- Version or Branch used : v0.17.1
- Operating System and version : Macos Mojave 10.14.2

**Comment by htran844** [comment]
how to fix this bug ?
