### ISSUE TITLE
Windows 10 unable to deploy electron-pack

### ISSUE THREAD

**Issue by Flashryan** [electron-react-boilerplate/electron-react-boilerplate#2147]
Hi,

im trying to package an electron with React app in Windows 10.

Any ideas where I am going wrong would be greatly appriciated

 Using node v8.9.4

Error: /usr/local/bin/node exited with code 1
Output:

> fsevents@1.2.7 install /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents
> node install

Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v4.0-darwin-x64/fse.node --module_name=fse --module_path=/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v4.0-darwin-x64 --napi_version=1 --node_abi_napi=napi' (1)

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v4.0-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and electron@4.0.4 (electron-v4.0 ABI, unknown) (falling back to source compile with node-gyp)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 817, in Write
    mac_bundle_deps, extra_outputs, part_of_all)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1453, in WriteTarget
    lambda p: Sourceify(self.Absolutify(p)))
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 809, in GetLdflags
    archs = self.GetActiveArchs(self.configname)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v4.0-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v4.0-darwin-x64" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v4.0-darwin-x64/fse.node --module_name=fse --module_path=/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v4.0-darwin-x64 --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.2.7 install: `node install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryandavies/.npm/_logs/2019-02-07T15_20_21_409Z-debug.log

    at ChildProcess.childProcess.once.code (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at _rebuild (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at _installOrRebuild (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:511:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:472:70)
    at /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/ryandavies/Desktop/reactElectron/my-react-app/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-react-app@0.1.0 electron-pack: `build --win --macos -c.extraMetadata.main=build/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-react-app@0.1.0 electron-pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryandavies/.npm/_logs/2019-02-07T15_20_21_538Z-debug.log
Ryans-MacBook-Pro-3:my-react-app ryandavies

**Comment by amilajack** [comment]
This isn't an issue with the boilerplate. See this issue https://github.com/nodejs/node-gyp/issues/1464.
