### ISSUE TITLE
yarn installing packages failed in windows server R2 (2012)

### ISSUE THREAD

**Issue by medaamarnadh** [electron-react-boilerplate/electron-react-boilerplate#2164]
I am trying to install my electron-react-boilerplate project on Windows server R2 version. I am getting installation error while installing packages. My project includes sqlite3 as well. 
## Prerequisites

-  Using yarn
- Using node 10.x
- Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)

## Expected Behavior
It has to install all the packages given package.json. 

## Current Behavior
It is showing below error.
`Done in 8.42s.
  • electron-builder version=20.36.2
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=win32 arch=x64 appDir=C:\Frontend\cl-fe\app
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild
yarn run v1.12.3
$ node -r babel-register ../internals/scripts/ElectronRebuild.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Frontend\\cl-fe\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Frontend\cl-fe\app\node_modules\sqlite3\build\deps\action_before_build.vcxproj(20,3): error MSB4019: The imported pro
ject "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and t
hat the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Frontend\cl-fe\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild" "--target=3.0.10" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_n
ame=node_sqlite3" "--module_path=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v3.0-win32-x64"
 "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.0.4/{toolset}/" "--package_name=electro
n-v3.0-win32-x64.tar.gz"
gyp ERR! cwd C:\Frontend\cl-fe\app\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Frontend\\cl-fe\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Frontend\cl-fe\app\node_modules\sqlite3\build\deps\action_before_build.vcxproj(20,3): error MSB4019: The imported pro
ject "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and t
hat the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Frontend\cl-fe\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild" "--target=3.0.10" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_n
ame=node_sqlite3" "--module_path=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v3.0-win32-x64"
 "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.0.4/{toolset}/" "--package_name=electro
n-v3.0-win32-x64.tar.gz"
gyp ERR! cwd C:\Frontend\cl-fe\app\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.next (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:189:22)
child_process.js:651
    throw err;
    ^

Error: Command failed: ..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Frontend\\cl-fe\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Frontend\cl-fe\app\node_modules\sqlite3\build\deps\action_before_build.vcxproj(20,3): error MSB4019: The imported pro
ject "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and t
hat the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Frontend\cl-fe\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild" "--target=3.0.10" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_n
ame=node_sqlite3" "--module_path=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v3.0-win32-x64"
 "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.0.4/{toolset}/" "--package_name=electro
n-v3.0-win32-x64.tar.gz"
gyp ERR! cwd C:\Frontend\cl-fe\app\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Frontend\\cl-fe\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\westagilelabs\\.electron-gyp\\iojs-3.0.10\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Frontend\cl-fe\app\node_modules\sqlite3\build\deps\action_before_build.vcxproj(20,3): error MSB4019: The imported pro
ject "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and t
hat the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Frontend\cl-fe\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Frontend\\cl-fe\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild" "--target=3.0.10" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_n
ame=node_sqlite3" "--module_path=C:\\Frontend\\cl-fe\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v3.0-win32-x64"
 "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.0.4/{toolset}/" "--package_name=electro
n-v3.0-win32-x64.tar.gz"
gyp ERR! cwd C:\Frontend\cl-fe\app\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.next (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:189:22)

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at Object.<anonymous> (C:/Frontend/cl-fe/internals/scripts/ElectronRebuild.js:21:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at loader (C:\Frontend\cl-fe\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Frontend\cl-fe\node_modules\babel-register\lib\node.j
s:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
error Command failed with exit code 1.
error Command failed with exit code 1.

    at SafeSubscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.next (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:189:22)
    at SafeSubscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Frontend\cl-fe\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.next (C:\Frontend\cl-fe\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:189:22)
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at Object.<anonymous> (C:/Frontend/cl-fe/internals/scripts/ElectronRebuild.js:21:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at loader (C:\Frontend\cl-fe\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Frontend\cl-fe\node_modules\babel-register\lib\node.j
s:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at ChildProcess.childProcess.once.code (C:\Frontend\cl-fe\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at _installOrRebuild (C:\Frontend\cl-fe\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\Frontend\cl-fe\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\Frontend\cl-fe\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installAppDeps (C:\Frontend\cl-fe\node_modules\electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (C:\Frontend\cl-fe\node_modules\electron-builder\out\cli\install-app-deps.js:144:26)
    at then (C:\Frontend\cl-fe\node_modules\electron-builder\src\cli\cli.ts:46:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\Frontend\cl-fe>
PS C:\Frontend\cl-fe>`

## Possible Solution
I am looking for a solution.

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Context
Installing packages.

## Your Environment

- Node version :  10.13
- Version or Branch used :  master
- Operating System and version : windows server 2012 R2
- Link to your project : NA

**Comment by vikr01** [comment]
`sqlite3` is a native module. From what I can tell, this is either an issue with [`sqlite3`](https://github.com/mapbox/node-sqlite3) or [`electron-rebuild`](https://github.com/electron/electron-rebuild) and **not** the boilerplate. I recommend making issue tickets in one of those repos.
