### ISSUE TITLE
Syntax Error on Package

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2234]
```SyntaxError: Unexpected token ﻿ in JSON at position 0
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at then.it (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:55:22)
    at tryCatcher (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\bluebird\js\release\promise.js:643:18)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
From previous event:
    at readJson (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:55:6)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:224:61
    at Generator.next (<anonymous>)
    at callback (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\graceful-fs\polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Collector.readChildPackage (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:206:90)
    at _bluebirdLst.default.map.it (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:191:69)
From previous event:
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:191:40
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Collector.readInstalled (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:170:91)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:78:16
    at Generator.next (<anonymous>)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
From previous event:
    at Collector.collect (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:76:28)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
    at _getProductionDependencies (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\packageDependencies.js:92:37)
    at getProductionDependencies (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\packageDependencies.js:83:37)
    at Lazy.<anonymous> (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:138:24)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\lazy-val\src\main.ts:18:25)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\yarn.js:166:90
From previous event:
    at _getProductionDependencies (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\packageDependencies.js:92:37)
    at getProductionDependencies (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\packageDependencies.js:83:37)
    at Lazy.<anonymous> (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:138:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\lazy-val\src\main.ts:18:25)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\yarn.js:166:90
    at Generator.next (<anonymous>)
From previous event:
    at _rebuild (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installOrRebuild (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:470:70)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:396:24)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\graceful-fs\graceful-fs.js:111:16
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:335:133)
    at D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\electron-builder\src\builder.ts:228:10)
    at then (D:\Development\Apps\ElectronOnlyApps\mausys\node_modules\electron-builder\src\cli\cli.ts:49:19)
error Command failed with exit code 1.```


- I tried to search here the issues and fix it but with no success


I wanted the app to package for Windows but instead got this error, I have ERB not very modified only added my Components created my Layout with react but the app has not really a functionality right now.

**Comment by kas** [comment]
I resolved this by upgrading electron-builder. Try updating your package.json:

`"electron-builder": "^21.2.0",`

**Comment by julienma** [comment]
Still waiting for #2267.
