### ISSUE TITLE
package-win error

### ISSUE THREAD

**Issue by lida1984** [electron-react-boilerplate/electron-react-boilerplate#2301]
yarn package-win v1.0.2
(node:408) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ yarn build && electron-builder build --win --x64
(node:25092) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[0] (node:14312) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1] (node:12664) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[0]
[0] WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version.
Currently, we assume version 2.x when no version is passed. Since this default version will likely
change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
[0]
[0] You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the
following commands:
[0]
[0]   npm install --save core-js@2    npm install --save core-js@3
[0]   yarn add core-js@2              yarn add core-js@3
[0]
[1]
[1] WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version.
Currently, we assume version 2.x when no version is passed. Since this default version will likely
change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
[1]
[1] You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the
following commands:
[1]
[1]   npm install --save core-js@2    npm install --save core-js@3
[1]   yarn add core-js@2              yarn add core-js@3
[1]
[0] Hash: e46966d62a95097c3880
[0] Version: webpack 4.41.2
[0] Time: 1215ms
[0] Built at: 2019-10-28 09:41:30
[0]                  Asset      Size  Chunks                   Chunk Names
[0]     ./app/main.prod.js  76.8 KiB       0  [emitted]        main
[0] ./app/main.prod.js.map   280 KiB       0  [emitted] [dev]  main
[0] Entrypoint main = ./app/main.prod.js ./app/main.prod.js.map
[0] [./app/main.dev.js] ./app/main.dev.js + 1 modules 8.7 KiB {0} [built]
[0]     | ./app/main.dev.js 2.54 KiB [built]
[0]     | ./app/menu.js 6.14 KiB [built]
[0] [assert] external "assert" 42 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [electron-debug] external "electron-debug" 42 bytes {0} [built]
[0] [electron-log] external "electron-log" 42 bytes {0} [built]
[0] [electron-updater] external "electron-updater" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [source-map-support] external "source-map-support" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 70 hidden modules
[0]
[0]
[0]                             Thanks for using Webpack!
[0]                  Please consider donating to our Open Collective
[0]                         to help us maintain this package.
[0]
[0]
[0]
[0]                  Donate: https://opencollective.com/webpack/donate
[0]
[0]
[0] D:\workspace\jpcs-audio-distinguish\srt-electron-project\node_modules\webpack-cli\bin\cli.js:352
[0]                                                             if (!e && fileOwnerId === process.getuid()) utimesSync(openCollectivePath, now, now);
[0]                                                                                               ^[0]
[0] TypeError: process.getuid is not a function
[0]     at e (D:\workspace\jpcs-audio-distinguish\srt-electron-project\node_modules\webpack-cli\bin\cli.js:352:43)
[0]     at FSReqWrap.oncomplete (fs.js:141:20)
error Command failed with exit code 1.
[0] yarn build-main exited with code 1
[1] Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
[1] Hash: dc195a34a08730e3bed5
[1] Version: webpack 4.41.2
[1] Time: 9275ms
[1] Built at: 2019-10-28 09:41:39
[1]                                Asset      Size  Chunks                   Chunk Names
[1] 44f3dc3035a778e4628b1fc0609c3d61.ttf    59 KiB          [emitted]
[1]                     renderer.prod.js    65 KiB       0  [emitted]        main
[1]                 renderer.prod.js.map   219 KiB       0  [emitted] [dev]  main
[1]                            style.css   518 KiB       0  [emitted]        main
[1]                        style.css.map  1.25 MiB          [emitted]
[1] Entrypoint main = style.css renderer.prod.js renderer.prod.js.map
[1] [./app/app.global.css] 39 bytes {0} [built]
[1] [./app/constants/routes.json] 43 bytes {0} [built]
[1] [./app/index.js] ./app/index.js + 17 modules 41.6 KiB {0} [built]
[1]     | ./app/index.js 1.43 KiB [built]
[1]     | ./app/containers/Root.js 1.33 KiB [built]
[1]     | ./app/store/configureStore.js 333 bytes [built]
[1]     | ./app/Routes.js 1.36 KiB [built]
[1]     | ./app/store/configureStore.dev.js 1.84 KiB [built]
[1]     | ./app/store/configureStore.prod.js 562 bytes [built]
[1]     | ./app/containers/App.js 1.2 KiB [built]
[1]     | ./app/containers/HomePage.js 1.21 KiB [built]
[1]     | ./app/actions/counter.js 604 bytes [built]
[1]     | ./app/containers/CounterPage.js 430 bytes [built]
[1]     | ./app/reducers/index.js 265 bytes [built]
[1]     | ./app/reducers/counter.js 297 bytes [built]
[1]     | ./app/services/ajax.js 2.3 KiB [built]
[1]     | ./app/utils/fileReader.js 574 bytes [built]
[1]     |     + 4 hidden modules
[1] [./app/renderer/transform.js] 1.6 KiB {0} [built]
[1] [antd] external "antd" 42 bytes {0} [built]
[1] [connected-react-router] external "connected-react-router" 42 bytes {0} [built]
[1] [history] external "history" 42 bytes {0} [built]
[1] [react] external "react" 42 bytes {0} [built]
[1] [react-dom] external "react-dom" 42 bytes {0} [built]
[1] [react-hot-loader] external "react-hot-loader" 42 bytes {0} [built]
[1] [react-redux] external "react-redux" 42 bytes {0} [built]
[1] [react-router] external "react-router" 42 bytes {0} [built]
[1] [react-router-dom] external "react-router-dom" 42 bytes {0} [built]
[1] [redux] external "redux" 42 bytes {0} [built]
[1] [redux-thunk] external "redux-thunk" 42 bytes {0} [built]
[1]     + 37 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!app/app.global.css:[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./node_modules/css-loader/dist/cjs.js?!./app/app.global.css] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./app/app.global.css 709 bytes {0} [built]
[1]         + 2 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!app/components/Counter.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!app/components/home/modules/transform/index.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!app/components/home/modules/update/style.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        4 modules
[1]
[1]
[1]                             Thanks for using Webpack!
[1]                  Please consider donating to our Open Collective
[1]                         to help us maintain this package.
[1]
[1]
[1]
[1]                  Donate: https://opencollective.com/webpack/donate
[1]
[1]
[1] D:\workspace\jpcs-audio-distinguish\srt-electron-project\node_modules\webpack-cli\bin\cli.js:352
[1]                                                             if (!e && fileOwnerId === process.getuid()) utimesSync(openCollectivePath, now, now);
[1]                                                                                               ^[1]
[1] TypeError: process.getuid is not a function
[1]     at e (D:\workspace\jpcs-audio-distinguish\srt-electron-project\node_modules\webpack-cli\bin\cli.js:352:43)
[1]     at FSReqWrap.oncomplete (fs.js:141:20)
error Command failed with exit code 1.
[1] yarn build-renderer exited with code 1
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by amilajack** [comment]
Try updating your version of electron-builder. If that doesn't work, try migrating to 0.18.0.
