### ISSUE TITLE
Cannot create property '-registry-npmjs-org' on string '{"-registry-npmjs-org":""}'

### ISSUE THREAD

**Issue by zmhweb** [electron-react-boilerplate/electron-react-boilerplate#2340]
```
Trace: 
  TypeError: Cannot create property '-registry-npmjs-org' on string '{"-registry-npmjs-org":""}'
      at set (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:53892:28)
      at set (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:53906:14)
      at set (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:53886:16)
      at Function.objectPath.set (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:53939:14)
      at NpmRegistry.mergeEnv (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:95973:18)
      at NpmRegistry.<anonymous> (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:31899:12)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:304:30)
      at /usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:322:14
      at new Promise (<anonymous>)

npm manifest: 
  {
    "name": "electron-react-boilerplate",
    "productName": "ElectronReact",
    "version": "0.18.0",
    "description": "Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development",
    "scripts": {
      "build": "concurrently \"yarn build-main\" \"yarn build-renderer\"",
      "build-dll": "cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors",
      "build-e2e": "cross-env E2E_BUILD=true yarn build",
      "build-main": "cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors",
      "build-renderer": "cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors",
      "dev": "cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev",
      "electron-rebuild": "electron-rebuild --parallel --force --types prod,dev,optional --module-dir app",
      "flow": "flow",
      "flow-typed": "rimraf flow-typed/npm && flow-typed install --overwrite || true",
      "lint": "cross-env NODE_ENV=development eslint --cache --format=pretty .",
      "lint-fix": "yarn --silent lint --fix; exit 0",
      "lint-styles": "stylelint --ignore-path .eslintignore '**/*.*(css|scss)' --syntax scss",
      "lint-styles-fix": "yarn --silent lint-styles --fix; exit 0",
      "package": "yarn build && electron-builder build --publish never",
      "package-all": "yarn build && electron-builder build -mwl",
      "package-ci": "yarn postinstall && yarn build && electron-builder --publish always",
      "package-linux": "yarn build && electron-builder build --linux",
      "package-win": "yarn build && electron-builder build --win --x64",
      "postinstall": "node -r @babel/register internals/scripts/CheckNativeDep.js && yarn flow-typed && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall",
      "postlint-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.{js,jsx,json,html,css,less,scss,yml}'",
      "postlint-styles-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.{css,scss}'",
      "preinstall": "node ./internals/scripts/CheckYarn.js",
      "prestart": "yarn build",
      "start": "cross-env NODE_ENV=production electron ./app/main.prod.js",
      "start-main-dev": "cross-env START_HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js",
      "start-renderer-dev": "cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js",
      "test": "cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 jest",
      "test-all": "yarn lint && yarn flow && yarn build && yarn test && yarn build-e2e && yarn test-e2e",
      "test-e2e": "node -r @babel/register ./internals/scripts/CheckBuildsExist.js && cross-env NODE_ENV=test testcafe electron:./app ./test/e2e/HomePage.e2e.js",
      "test-e2e-live": "node -r @babel/register ./internals/scripts/CheckBuildsExist.js && cross-env NODE_ENV=test testcafe --live electron:./app ./test/e2e/HomePage.e2e.js",
      "test-watch": "yarn test --watch"
    },
    "lint-staged": {
      "*.{js,jsx}": [
        "cross-env NODE_ENV=development eslint --cache --format=pretty",
        "git add"
      ],
      "{*.json,.{babelrc,eslintrc,prettierrc,stylelintrc}}": [
        "prettier --ignore-path .eslintignore --parser json --write",
        "git add"
      ],
      "*.{css,scss}": [
        "stylelint --ignore-path .eslintignore --syntax scss --fix",
        "prettier --ignore-path .eslintignore --single-quote --write",
        "git add"
      ],
      "*.{html,md,yml}": [
        "prettier --ignore-path .eslintignore --single-quote --write",
        "git add"
      ]
    },
    "build": {
      "productName": "ElectronReact",
      "appId": "org.develar.ElectronReact",
      "files": [
        "dist/",
        "node_modules/",
        "app.html",
        "main.prod.js",
        "main.prod.js.map",
        "package.json"
      ],
      "dmg": {
        "contents": [
          {
            "x": 130,
            "y": 220
          },
          {
            "x": 410,
            "y": 220,
            "type": "link",
            "path": "/Applications"
          }
        ]
      },
      "win": {
        "target": [
          "nsis",
          "msi"
        ]
      },
      "linux": {
        "target": [
          "deb",
          "rpm",
          "AppImage"
        ],
        "category": "Development"
      },
      "directories": {
        "buildResources": "resources",
        "output": "release"
      },
      "publish": {
        "provider": "github",
        "owner": "electron-react-boilerplate",
        "repo": "electron-react-boilerplate",
        "private": false
      }
    },
    "repository": {
      "type": "git",
      "url": "git+https://github.com/electron-react-boilerplate/electron-react-boilerplate.git"
    },
    "author": {
      "name": "Electron React Boilerplate Maintainers",
      "email": "electronreactboilerplate@gmail.com",
      "url": "https://electron-react-boilerplate.js.org"
    },
    "contributors": [
      {
        "name": "Vikram Rangaraj",
        "email": "vikr01@icloud.com",
        "url": "https://github.com/vikr01"
      },
      {
        "name": "Amila Welihinda",
        "email": "amilajack@gmail.com",
        "url": "https://github.com/amilajack"
      }
    ],
    "license": "MIT",
    "bugs": {
      "url": "https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues"
    },
    "keywords": [
      "electron",
      "boilerplate",
      "react",
      "redux",
      "flow",
      "sass",
      "webpack",
      "hot",
      "reload"
    ],
    "homepage": "https://github.com/electron-react-boilerplate/electron-react-boilerplate#readme",
    "jest": {
      "testURL": "http://localhost/",
      "moduleNameMapper": {
        "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/internals/mocks/fileMock.js",
        "\\.(css|less|sass|scss)$": "identity-obj-proxy"
      },
      "moduleFileExtensions": [
        "js",
        "jsx",
        "json"
      ],
      "moduleDirectories": [
        "node_modules",
        "app/node_modules"
      ],
      "transform": {
        "^.+\\.jsx?$": "babel-jest"
      },
      "setupFiles": [
        "./internals/scripts/CheckBuildsExist.js"
      ]
    },
    "devDependencies": {
      "@babel/core": "^7.7.4",
      "@babel/plugin-proposal-class-properties": "^7.7.4",
      "@babel/plugin-proposal-decorators": "^7.7.4",
      "@babel/plugin-proposal-do-expressions": "^7.7.4",
      "@babel/plugin-proposal-export-default-from": "^7.7.4",
      "@babel/plugin-proposal-export-namespace-from": "^7.7.4",
      "@babel/plugin-proposal-function-bind": "^7.7.4",
      "@babel/plugin-proposal-function-sent": "^7.7.4",
      "@babel/plugin-proposal-json-strings": "^7.7.4",
      "@babel/plugin-proposal-logical-assignment-operators": "^7.7.4",
      "@babel/plugin-proposal-nullish-coalescing-operator": "^7.7.4",
      "@babel/plugin-proposal-numeric-separator": "^7.7.4",
      "@babel/plugin-proposal-optional-chaining": "^7.7.4",
      "@babel/plugin-proposal-pipeline-operator": "^7.7.4",
      "@babel/plugin-proposal-throw-expressions": "^7.7.4",
      "@babel/plugin-syntax-dynamic-import": "^7.7.4",
      "@babel/plugin-syntax-import-meta": "^7.7.4",
      "@babel/plugin-transform-react-constant-elements": "^7.7.4",
      "@babel/plugin-transform-react-inline-elements": "^7.7.4",
      "@babel/preset-env": "^7.7.4",
      "@babel/preset-flow": "^7.7.4",
      "@babel/preset-react": "^7.7.4",
      "@babel/register": "^7.7.4",
      "babel-core": "7.0.0-bridge.0",
      "babel-eslint": "^10.0.3",
      "babel-jest": "^24.9.0",
      "babel-loader": "^8.0.6",
      "babel-plugin-dev-expression": "^0.2.2",
      "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
      "chalk": "^3.0.0",
      "concurrently": "^5.0.0",
      "cross-env": "^6.0.3",
      "cross-spawn": "^7.0.1",
      "css-loader": "^3.2.0",
      "detect-port": "^1.3.0",
      "electron": "6",
      "electron-builder": "^22.2.0",
      "electron-devtools-installer": "^2.2.4",
      "electron-rebuild": "^1.8.8",
      "enzyme": "^3.7.0",
      "enzyme-adapter-react-16": "^1.7.0",
      "enzyme-to-json": "^3.3.4",
      "eslint": "^6.6.0",
      "eslint-config-airbnb": "^18.0.1",
      "eslint-config-erb": "^0.1.1",
      "eslint-config-prettier": "^6.6.0",
      "eslint-formatter-pretty": "^3.0.0",
      "eslint-import-resolver-webpack": "^0.11.0",
      "eslint-plugin-compat": "^3.3.0",
      "eslint-plugin-flowtype": "^4.4.1",
      "eslint-plugin-import": "^2.18.2",
      "eslint-plugin-jest": "^23.0.4",
      "eslint-plugin-jsx-a11y": "6.2.3",
      "eslint-plugin-prettier": "^3.1.1",
      "eslint-plugin-promise": "^4.2.1",
      "eslint-plugin-react": "^7.16.0",
      "eslint-plugin-testcafe": "^0.2.1",
      "fbjs-scripts": "^1.2.0",
      "file-loader": "^4.2.0",
      "flow-bin": "^0.112.0",
      "flow-runtime": "^0.17.0",
      "flow-typed": "^2.6.2",
      "husky": "^3.1.0",
      "identity-obj-proxy": "^3.0.0",
      "jest": "^24.9.0",
      "lint-staged": "^9.4.3",
      "mini-css-extract-plugin": "^0.8.0",
      "node-sass": "^4.13.0",
      "opencollective-postinstall": "^2.0.2",
      "optimize-css-assets-webpack-plugin": "^5.0.3",
      "prettier": "^1.19.1",
      "react-test-renderer": "^16.12.0",
      "redux-logger": "^3.0.6",
      "rimraf": "^3.0.0",
      "sass-loader": "^8.0.0",
      "sinon": "^7.5.0",
      "spectron": "^9.0.0",
      "style-loader": "^1.0.0",
      "stylelint": "^12.0.0",
      "stylelint-config-prettier": "^6.0.0",
      "stylelint-config-standard": "^19.0.0",
      "terser-webpack-plugin": "^2.2.1",
      "testcafe": "^1.6.1",
      "testcafe-browser-provider-electron": "^0.0.12",
      "testcafe-react-selectors": "^3.3.0",
      "url-loader": "^2.2.0",
      "webpack": "^4.41.2",
      "webpack-bundle-analyzer": "^3.6.0",
      "webpack-cli": "^3.3.10",
      "webpack-dev-server": "^3.9.0",
      "webpack-merge": "^4.2.2",
      "yarn": "^1.19.1"
    },
    "dependencies": {
      "@fortawesome/fontawesome-free": "^5.11.2",
      "@hot-loader/react-dom": "^16.11.0",
      "connected-react-router": "^6.6.1",
      "core-js": "^3.4.5",
      "devtron": "^1.4.0",
      "electron-debug": "^3.0.1",
      "electron-log": "^3.0.9",
      "electron-updater": "^4.2.0",
      "history": "^4.10.1",
      "react": "^16.12.0",
      "react-dom": "^16.12.0",
      "react-hot-loader": "^4.12.18",
      "react-redux": "^7.1.3",
      "react-router": "^5.1.2",
      "react-router-dom": "^5.1.2",
      "redux": "^4.0.4",
      "redux-thunk": "^2.3.0",
      "source-map-support": "^0.5.16"
    },
    "devEngines": {
      "node": ">=7.x",
      "npm": ">=4.x",
      "yarn": ">=0.21.3"
    },
    "collective": {
      "url": "https://opencollective.com/electron-react-boilerplate-594"
    },
    "browserslist": "electron 1.6",
    "husky": {
      "hooks": {
        "pre-commit": "lint-staged"
      }
    }
  }
```
user  ``yarn install`` report this error ,How to solve this problem?

**Comment by amilajack** [comment]
Please try the solutions in #400

**Comment by tambo** [comment]
I encountered this issue when I had accidentally set a registry config for yarn badly (eg yarn config add registry=https://registry.npmjs.org). 

fixed by using `yarn config delete registry=https://registry.npmjs.org`

Make sure to correctly set registry without the '=' , ie: `yarn config add registry https://registry.npmjs.org`
