### ISSUE TITLE
build-dll resulting in out of memory

### ISSUE THREAD

**Issue by techterbium** [electron-react-boilerplate/electron-react-boilerplate#2352]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
`build-dll` task should be successfully completed and .dll files are to be generated. 

## Current Behavior

It fails with out of memory error. And, the build-dll task makes CPU go crazy as it makes huge noise during the task. I don't know if this is weird, but happens in my case. I wish I could take a video. 

 I am not sure if this is being caused by an npm dependency. Here is my dependencies list.

```
 "dependencies": {
    "@hot-loader/react-dom": "16.11.0",
    "@openid/appauth": "1.2.6",
    "antd": "3.25.3",
    "asar": "^2.0.1",
    "axios": "^0.19.0",
    "babel-preset-react": "6.24.1",
    "core-js": "3.4.2",
    "devtron": "1.4.0",
    "electron-debug": "3.0.1",
    "electron-log": "3.0.9",
    "electron-updater": "4.2.0",
    "history": "4.10.1",
    "is-online": "8.2.1",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-google-button": "0.6.0",
    "react-hot-loader": "4.12.18",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "simple-crypto-js": "2.2.0",
    "source-map-support": "0.5.16",
    "systeminformation": "4.15.3",
    "uuid": "3.3.3",
    "video-react": "^0.14.1",
    "video.js": "^7.6.6"
  }
```

Here is the command output

```
yarn run v1.16.0
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
The DLL files are missing. Sit back while we build them for you with "yarn build-dll"
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 2: node::FatalTryCatch::~FatalTryCatch() [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 6: 0x2fc2cf0427d
error Command failed with exit code 1.
Error: Command failed: yarn build-dll
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 2: node::FatalTryCatch::~FatalTryCatch() [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/<USER>/.nvm/versions/node/v10.0.0/bin/node]
 6: 0x2fc2cf0427d
error Command failed with exit code 1.

    at checkExecSyncError (child_process.js:596:11)
    at execSync (child_process.js:633:13)
    at Object.<anonymous> (/Users/<USER>/<NAME>/<APP_NAME>-app/configs/webpack.config.renderer.dev.babel.js:42:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module._compile (/Users/<USER>/<NAME>/<APP_NAME>-app/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.newLoader [as .js] (/Users/<USER>/<NAME>/<APP_NAME>-app/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Your Environment

- Node version : 11.15
- Operating System and version : Mac 10.13

**Comment by techterbium** [comment]
Changing `build-dll` command as below helped to deal with heap out of memory.

```cross-env NODE_OPTIONS=--max_old_space_size=4096 NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors```
