### ISSUE TITLE
Unknown version 8.1.0 of electron. Could you please explain why?

### ISSUE THREAD

**Issue by saifeiLee** [electron-react-boilerplate/electron-react-boilerplate#2459]
I upgrade electron from 7.1.13 to 8.1.0. When I run `yarn dev`, I got the error. `Unknown version 8.1.0 of electron (While processing: "/Users/waltermitty/Code/cvte/electron-easi-camera/babel.config.js$0")`. I wanna know the reason of this error happening. 

## Prerequisites

- [✅] Using yarn
- [[✅] Using node 10.x
- [[✅] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ [✅] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [[✅ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [✅ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

run `yarn dev`, the project can start.

## Current Behavior

An error:
```bash
/Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/core/lib/config/full.js:168
    throw e;
    ^
BrowserslistError: [BABEL] /Users/waltermitty/Code/cvte/electron-easi-camera/internals/scripts/CheckPortInUse.js: Unknown version 8.1.0 of electron (While processing: "/Users/waltermitty/Code/cvte/electron-easi-camera/babel.config.js$0")
    at Function.select (/Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:945:15)
    at /Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:299:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:281:18)
    at Function.select (/Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:1033:14)
    at /Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:299:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:281:18)
    at browserslist (/Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:405:21)
    at getTargets (/Users/waltermitty/Code/cvte/electron-easi-camera/node_modules/@babel/helper-compilation-targets/lib/index.js:202:48)
```

## Your Environment

- Node version : 10.16.0
- Version or Branch used : master
- Operating System and version : oxs 10.15.3

**Comment by amilajack** [comment]
Try updating all babel dependencies. If that doesn't work, temporarily change babel target to something newer like node 13. Babel's preset env targets aren't updated yet to take into account.

**Comment by saifeiLee** [comment]
> Try updating all babel dependencies. If that doesn't work, temporarily change babel target to something newer like node 13. Babel's preset env targets aren't updated yet to take into account.

Well, updating `babel-preset` & `babel/core` solved my problem. Thank you very much!
