### ISSUE TITLE
I followed the steps from https://electron-react-boilerplate.js.org/docs/installation/ and ran into a peer dependency error

### ISSUE THREAD

**Issue by andresmejia3** [electron-react-boilerplate/electron-react-boilerplate#2518]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
When I run 

```
git clone --depth=1 https://github.com/electron-react-boilerplate/electron-react-boilerplate your-project-name
cd your-project-name
yarn
```

I expected dependencies to be installed successfully

## Current Behavior
Instead I get
 ```
    warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
    warning " > connected-react-router@6.8.0" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
    warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
    warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
    warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.1.0" has incorrect peer dependency "eslint@^5.16.0 || ^6.8.0".
    warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.1.0" has incorrect peer dependency "eslint-plugin-react-hooks@^2.5.0 || ^1.7.0".
    warning " > eslint-config-erb@1.0.0" has unmet peer dependency "eslint-plugin-flowtype@^5.1.3".
    warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".
    [4/4] 🔨  Building fresh packages...
    $ node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall
    npm ERR! peer dep missing: electron@^7.0.0, required by browserslist-config-erb@0.0.1
    npm ERR! peer dep missing: eslint-plugin-jsx-a11y@6.2.3, required by eslint-config-erb@1.0.0
    npm ERR! peer dep missing: immutable@^3.8.1 || ^4.0.0-rc.1, required by connected-react-router@6.8.0
    npm ERR! peer dep missing: seamless-immutable@^7.1.3, required by connected-react-router@6.8.0
    npm ERR! peer dep missing: eslint-plugin-flowtype@^5.1.3, required by eslint-config-erb@1.0.0
    npm ERR! peer dep missing: eslint@^5.16.0 || ^6.8.0, required by eslint-config-airbnb@18.1.0
    npm ERR! peer dep missing: eslint-plugin-react-hooks@^2.5.0 || ^1.7.0, required by eslint-config-airbnb@18.1.0
```

This might be pretty easy to solve, but I'm new to electron.js so I'm not sure what to do

## Steps to Reproduce (for bugs)

1. I've tried it multiple times and whenever I run 

git clone --depth=1 https://github.com/electron-react-boilerplate/electron-react-boilerplate your-project-name
cd your-project-name
yarn

I get those warnings and errors

## Context
I want to make sure that I'm installing it properly

## Your Environment

- Node version : v14.5.0
- Version or Branch used : master
- Operating System and version : MacOS Catalina 10.15.5

**Comment by amilajack** [comment]
I'm not able to repo this. What's your version of yarn?

**Comment by Mehuge** [comment]
I am having the same issue. 

Yarn version was 1.12.3. So I updated yarn using (`npm i -g yarn`) and now have version 1.22.4.
I still get the same issue.

```
yarn install v1.22.4
$ node ./internals/scripts/CheckYarn.js
[1/4] �  Resolving packages...
[2/4] �  Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] �  Linking dependencies...
warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning " > connected-react-router@6.8.0" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-config-airbnb-typescript@^8.0.2".
warning " > eslint-config-erb@1.0.0" has unmet peer dependency "eslint-plugin-flowtype@^5.1.3".
warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".
[4/4] �  Building fresh packages...
$ node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall
npm ERR! peer dep missing: electron@^7.0.0, required by browserslist-config-erb@0.0.1
npm ERR! peer dep missing: eslint-config-airbnb-typescript@^8.0.2, required by eslint-config-erb@1.0.0
npm ERR! peer dep missing: eslint-plugin-jsx-a11y@6.2.3, required by eslint-config-erb@1.0.0
npm ERR! peer dep missing: immutable@^3.8.1 || ^4.0.0-rc.1, required by connected-react-router@6.8.0
npm ERR! peer dep missing: seamless-immutable@^7.1.3, required by connected-react-router@6.8.0
npm ERR! peer dep missing: eslint-plugin-flowtype@^5.1.3, required by eslint-config-erb@1.0.0
npm ERR! peer dep missing: node-sass@^4.0.0, required by sass-loader@9.0.2
npm ERR! peer dep missing: sass@^1.3.0, required by sass-loader@9.0.2
npm ERR! peer dep missing: fibers@>= 3.1.0, required by sass-loader@9.0.2
npm ERR! peer dep missing: canvas@^2.5.0, required by jsdom@16.3.0
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.3.1
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.3.1
Native dependencies could not be checked
  • electron-builder  version=22.7.0
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=D:\DEV\alien-ui\your-project-name\app
  ⨯ C:\Program Files (x86)\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild
yarn run v1.22.4
info If you think this is a bug, please open a bug report with the information provided in "D:\\DEV\\alien-ui\\your-project-name\\app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:

Error output:
error An unexpected error occurred: "Cannot create property '-registry-npmjs-org' on string '{\"-registry-npmjs-org\":true}'".
error Command failed with exit code 1.
  stackTrace=
```

**Comment by einsteinx2** [comment]
I'm reproducing this as well, fresh clone on macOS 10.15.5 with node 12.16.1 and yarn 1.22.4:

```
ben-mbp :: ~/workspacer » git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git register-app-updated 
Cloning into 'register-app-updated'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 138 (delta 7), reused 91 (delta 2), pack-reused 0
Receiving objects: 100% (138/138), 1.50 MiB | 3.45 MiB/s, done.
Resolving deltas: 100% (7/7), done.
ben-mbp :: ~/workspacer » cd register-app-updated 
ben-mbp :: ~/workspacer/register-app-updated ‹git master› » node -v
v12.16.1
ben-mbp :: ~/workspacer/register-app-updated ‹git master› » yarn
yarn install v1.22.4
$ node ./internals/scripts/CheckYarn.js
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning " > connected-react-router@6.8.0" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-config-airbnb-typescript@^8.0.2".
warning " > eslint-config-erb@1.0.0" has unmet peer dependency "eslint-plugin-flowtype@^5.1.3".
warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".
[4/4] 🔨  Building fresh packages...
$ node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall
npm ERR! peer dep missing: electron@^7.0.0, required by browserslist-config-erb@0.0.1
npm ERR! peer dep missing: eslint-config-airbnb-typescript@^8.0.2, required by eslint-config-erb@1.0.0
npm ERR! peer dep missing: eslint-plugin-jsx-a11y@6.2.3, required by eslint-config-erb@1.0.0
npm ERR! peer dep missing: immutable@^3.8.1 || ^4.0.0-rc.1, required by connected-react-router@6.8.0
npm ERR! peer dep missing: seamless-immutable@^7.1.3, required by connected-react-router@6.8.0
npm ERR! peer dep missing: eslint-plugin-flowtype@^5.1.3, required by eslint-config-erb@1.0.0
Native dependencies could not be checked
  • electron-builder  version=22.7.0
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=darwin arch=x64 appDir=/Users/bbaron/workspacer/register-app-updated/app
yarn run v1.22.4
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors
Hash: 07dc0b477b87a5bcee12
Version: webpack 4.43.0
Time: 1569ms
Built at: 08/03/2020 6:04:06 PM
              Asset      Size    Chunks             Chunk Names
renderer.dev.dll.js  3.38 MiB  renderer  [emitted]  renderer
Entrypoint renderer = renderer.dev.dll.js
[0] dll renderer 12 bytes {renderer} [built]
[./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {renderer} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {renderer} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {renderer} [built]
[child_process] external "child_process" 42 bytes {renderer} [built]
[crypto] external "crypto" 42 bytes {renderer} [built]
[electron] external "electron" 42 bytes {renderer} [built]
[events] external "events" 42 bytes {renderer} [built]
[fs] external "fs" 42 bytes {renderer} [built]
[http] external "http" 42 bytes {renderer} [built]
[https] external "https" 42 bytes {renderer} [built]
[os] external "os" 42 bytes {renderer} [built]
[path] external "path" 42 bytes {renderer} [built]
[querystring] external "querystring" 42 bytes {renderer} [built]
[url] external "url" 42 bytes {renderer} [built]
    + 264 hidden modules

WARNING in ./node_modules/electron-debug/index.js 108:45-58
Critical dependency: the request of a dependency is an expression
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js 109:61-74
Critical dependency: the request of a dependency is an expression
 @ dll renderer
✨  Done in 3.27s.
Thank you for using electron-react-boilerplate!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/electron-react-boilerplate-594/donate

✨  Done in 61.11s.
ben-mbp :: ~/workspacer/register-app-updated ‹git master› » yarn --version
1.22.4
```

The app did launch though:

```
ben-mbp :: ~/workspacer/register-app-updated ‹git master› » yarn dev
yarn run v1.22.4
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...
ℹ ｢wds｣: Project is running at http://localhost:1212/
ℹ ｢wds｣: webpack output is served from http://localhost:1212/dist
ℹ ｢wds｣: Content not from webpack is served from /Users/bbaron/workspacer/register-app-updated/configs/dist
ℹ ｢wds｣: 404s will fallback to /index.html
npm WARN lifecycle The node binary used for scripts is /var/folders/q7/bkzkfyv524160c3ngvtg3xl80000gn/T/yarn--1596496039640-0.6745887732321076/node but npm is using /Users/bbaron/.nvm/versions/node/v12.16.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> electron-react-boilerplate@1.3.0 start-main-dev /Users/bbaron/workspacer/register-app-updated
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts

ℹ ｢wdm｣: Compiled successfully.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Error: Exited with code 9
    at ChildProcess.<anonymous> (/Users/bbaron/workspacer/register-app-updated/node_modules/cross-unzip/index.js:38:21)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
18:07:28.561 › Skip checkForUpdatesAndNotify because application is not packed
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
```

<img width="1048" alt="Screen Shot 2020-08-03 at 6 08 31 PM" src="https://user-images.githubusercontent.com/350423/89235726-61364e80-d5b4-11ea-8c62-54b4a28b44a6.png">

**Comment by dylel** [comment]
I had this issue as well and it appeared to be something with the yarn installation, i installed via yarns second method "Install via Chocolatey" and the issue went away

[Yarn Install](https://classic.yarnpkg.com/en/docs/install/#windows-stable)

**Comment by wenxiayili** [comment]
> I had this issue as well and it appeared to be something with the yarn installation, i installed via yarns second method "Install via Chocolatey" and the issue went away
> 
> [Yarn Install](https://classic.yarnpkg.com/en/docs/install/#windows-stable)

Useless...

**Comment by wenxiayili** [comment]
> I'm not able to repo this. What's your version of yarn?
same issues
yarn: 1.22.5
node: 12.13.0

**Comment by mustafaKamal-fe** [comment]
hi
i had some issues with my dependencies and did this:
1- npm i package-lock-only
2-npm audit fix
3- then removed yarn.lock file
4- finally yarn import

this has fixed many problems for me. however, i still have this:
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".

**Comment by GeorgeBarlow** [comment]
None of these solutions worked for me, anyone got any way to resolve this?

**Comment by toilahung** [comment]
me too, waiting for solution now

**Comment by einsteinx2** [comment]
@GeorgeBarlow so far there doesn't seem to be, but for what it's worth, we haven't seen any actual issues running out application even with the errors. We also got similar errors from a muuuch older version of this repo years ago that we've been using in production for years with similar peer dependency errors without any actual issues we're aware of. So while I'd also like to resolve it, it doesn't seem to cause any real issues besides error log spam.
