### ISSUE TITLE
'Cannot get /' after cloning project

### ISSUE THREAD

**Issue by pkail** [electron-react-boilerplate/electron-react-boilerplate#2535]
- [x ] Using yarn
- [ x] Using node 10.x
- [ x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x ] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x ] Console output shown below (compiled successfully)
- [ x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
Electron starts and, at the same time, the React app starts on localhost:1212, as suggested by the console output.
Maybe it's not supposed to appear in the browser; however, it seems strange that it doesn't.

Electron starts up, but there is nothing in the browser.

Console output:

$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...
ℹ ｢wds｣: Project is running at http://localhost:1212/
ℹ ｢wds｣: webpack output is served from http://localhost:1212/dist
ℹ ｢wds｣: Content not from webpack is served from /home/p/Data/XS/your-project-name/configs/dist
ℹ ｢wds｣: 404s will fallback to /index.html
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1596155273479-0.36928582350696604/node but npm is using /home/p/.nvm/versions/node/v14.5.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> electron-react-boilerplate@1.3.0 start-main-dev /home/p/Data/XS/your-project-name
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Error: Exited with code 9
    at ChildProcess.<anonymous> (/home/p/Data/XS/your-project-name/node_modules/cross-unzip/index.js:38:21)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
17:27:56.689 › APPIMAGE env is not defined, current application is not an AppImage
ℹ ｢wdm｣: wait until bundle finished: /dist/renderer.dev.js
ℹ ｢wdm｣: Compiled successfully.
## Steps to Reproduce (for bugs)

1.git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
cd your-project-name
yarn

No

## Your Environment
node v14.5.0/

- Node version :14.5.0/
- Version or Branch used :master
- Operating System and version : Linux Mint 19.3 /64-bit

**Comment by Virushaan** [comment]
Currently experiencing this issue as well :/ I'm running on Windows 10.

**Comment by Virushaan** [comment]
Same issue here on Windows 10, running through the debugging steps did not fix it. :/

**Comment by thisismydesign** [comment]
Seen the same error on Windows 10, running Electron in WSL.

**Comment by amilajack** [comment]
We don't support WSL at the moment

**Comment by desmondchoon** [comment]
Getting the same issue on MacOS 10.15

**Comment by desmondchoon** [comment]
> Seen the same error on Windows 10, running Electron in WSL. Nevertheless, my app started successfully.

Getting the same error too on MacOS 10.16, and app still started successfully. Not sure what is the cause and if it would affect the app down the line.

**Comment by Cedric-ruiu** [comment]
Hi,

First install & and first `yarn start` i got the same error. Win10, Node v12.19, yarn v1.22.10. But app started successfully.

```bash
D:\www\myapp(master -> origin) (electron-react-boilerplate) 
λ yarn start
yarn run v1.22.10
$ yarn build
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
[0] Hash: 9f0a82ccd8e1f8c0b832
[0] Version: webpack 4.44.1
[0] Time: 13872ms
[0] Built at: 2020-11-09 21:27:25
[0]                          Asset      Size  Chunks             Chunk Names
[0]             ./app/main.prod.js   715 KiB       0  [emitted]  main
[0] ./app/main.prod.js.LICENSE.txt  55 bytes          [emitted]
[0] Entrypoint main = ./app/main.prod.js
[0] [./app/main.dev.ts] ./app/main.dev.ts + 1 modules 14.1 KiB {0} [built]
[0]     | ./app/main.dev.ts 6.07 KiB [built]
[0]     | ./app/menu.ts 8.03 KiB [built]
[0] [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {0} [built]
[0] [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [crypto] external "crypto" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [http] external "http" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [os] external "os" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [querystring] external "querystring" 42 bytes {0} [built]
[0] [url] external "url" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 593 hidden modules
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 108:45-58
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 109:61-74
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0] yarn build-main exited with code 0
[1] Hash: ec925dff7e079369922f
[1] Version: webpack 4.44.1
[1] Time: 16144ms
[1] Built at: 2020-11-09 21:27:28
[1]                                  Asset       Size  Chunks             Chunk Names
[1]                     0.renderer.prod.js   2.37 KiB       0  [emitted]  CounterPage
[1]                            0.style.css  562 bytes       0  [emitted]  CounterPage
[1]                        0.style.css.map  998 bytes          [emitted]
[1]   131054e1a15e8c1a2be90a810fd3b340.ttf    133 KiB          [emitted]
[1]  1bdf103cf1d2f4875cb40d7f8263339f.woff    102 KiB          [emitted]
[1] 2ffc1f5b1909c172f2396d16f9b8571e.woff2   76.8 KiB          [emitted]
[1]   46c13076acbc82aac893393573f90dc1.eot    134 KiB          [emitted]
[1]   4d5e84b7703fc47f5b870e30b01fbb70.svg    141 KiB          [emitted]
[1]   59f4a1ec50a2e39950ae7abbfebe6bf4.eot   33.5 KiB          [emitted]
[1] 6462b09d97cb0149ec021b8e01b9cc90.woff2   13.3 KiB          [emitted]
[1]   6e617fd4bfae0ebd495be461ed773e32.ttf    200 KiB          [emitted]
[1]   85ca58b3dfb55c08f9cf7532b755c0ac.svg    730 KiB          [emitted]
[1]   8ce738c3de1f5af6f0db90f9b55b71c7.ttf   33.3 KiB          [emitted]
[1]   ab3ef4abdaedeced52195d7ae4917446.eot    200 KiB          [emitted]
[1]  aee72cf0a11239dba36c7e37f831fae4.woff   16.4 KiB          [emitted]
[1]  d87ca79c4938f3ca66cbfa9d28526ba7.woff   90.1 KiB          [emitted]
[1]   dad3d991c79c6ec9e284296aab3f8cc3.svg    896 KiB          [emitted]
[1] f2d8806e4ac0d7a6e72fb4f22bd3c802.woff2   78.4 KiB          [emitted]
[1]                       renderer.prod.js    507 KiB       1  [emitted]  main
[1]           renderer.prod.js.LICENSE.txt   1.01 KiB          [emitted]
[1]                              style.css   58.7 KiB       1  [emitted]  main
[1]                          style.css.map    110 KiB          [emitted]
[1] Entrypoint main = style.css renderer.prod.js
[1] [0] multi core-js regenerator-runtime/runtime ./app/index.tsx 52 bytes {1} [built]
[1] [./app/app.global.css] 39 bytes {1} [built]
[1] [./app/constants/routes.json] 43 bytes {1} [built]
[1] [./app/containers/CounterPage.tsx] ./app/containers/CounterPage.tsx + 1 modules 3.84 KiB {0} [built]
[1]     | ./app/containers/CounterPage.tsx 1.1 KiB [built]
[1]     | ./app/features/counter/Counter.tsx 2.71 KiB [built]
[1] [./app/containers/Root.tsx] ./app/containers/Root.tsx + 4 modules 5.95 KiB {1} [built]
[1]     | ./app/containers/Root.tsx 1.42 KiB [built]
[1]     | ./app/Routes.tsx 1.89 KiB [built]
[1]     | ./app/containers/App.tsx 173 bytes [built]
[1]     | ./app/containers/HomePage.tsx 1.08 KiB [built]
[1]     |     + 1 hidden module
[1] [./app/features/counter/Counter.css] 203 bytes {0} [built]
[1] [./app/features/counter/counterSlice.ts] 1.11 KiB {1} [built]
[1] [./app/index.tsx] ./app/index.tsx + 2 modules 4.35 KiB {1} [built]
[1]     | ./app/index.tsx 1.57 KiB [built]
[1]     | ./app/store.ts 2.38 KiB [built]
[1]     | ./app/rootReducer.ts 354 bytes [built]
[1] [./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js] ./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js + 3 modules 71 KiB {1} [built]
[1]     |    4 modules
[1] [./node_modules/connected-react-router/esm/index.js] ./node_modules/connected-react-router/esm/index.js + 5 modules 17.1 KiB {1} [built]
[1]     |    6 modules
[1] [./node_modules/history/esm/history.js] ./node_modules/history/esm/history.js + 2 modules 30.6 KiB {1} [built]
[1]     |    3 modules
[1] [./node_modules/react-redux/es/index.js] ./node_modules/react-redux/es/index.js + 22 modules 49.9 KiB {1} [built]
[1]     |    23 modules
[1] [./node_modules/react-router/esm/react-router.js] ./node_modules/react-router/esm/react-router.js + 1 modules 29.9 KiB {1} [built]
[1]     |    2 modules
[1] [./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {1} [built]
[1]     + 581 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!app/app.global.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./node_modules/css-loader/dist/cjs.js?!./app/app.global.css] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./app/app.global.css 2.39 KiB {0} [built]
[1]         + 18 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!app/components/Home.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!app/features/counter/Counter.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./node_modules/css-loader/dist/cjs.js?!./app/features/counter/Counter.css] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./app/features/counter/Counter.css 2.09 KiB {0} [built]
[1]         + 1 hidden module
[1] yarn build-renderer exited with code 0
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...
i ｢wds｣: Project is running at http://localhost:1212/
i ｢wds｣: webpack output is served from http://localhost:1212/dist
i ｢wds｣: Content not from webpack is served from D:\www\myapp\configs\dist
i ｢wds｣: 404s will fallback to /index.html

> electron-react-boilerplate@ start-main-dev D:\www\myapp
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts

i ｢wdm｣: Compiled successfully.

Error: Exited with code 2
    at ChildProcess.<anonymous> (D:\www\myapp\node_modules\cross-unzip\index.js:38:21)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
21:27:58.769 > Skip checkForUpdatesAndNotify because application is not packed
```
