### ISSUE TITLE
Error: Cannot find module './configs/webpack.config.eslint.js'

### ISSUE THREAD

**Issue by doublethinkio** [electron-react-boilerplate/electron-react-boilerplate#2541]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/e799828f0c65a073c88c05beb30601a79bdfbbca/.eslintrc.js#L14-L21

## Steps to Reproduce (for bugs)

1. 
```
git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
cd your-project-name
yarn
```

2. 
```bash
$ yarn lint
yarn run v1.22.4
$ cross-env NODE_ENV=development eslint . --cache --ext .js,.jsx,.ts,.tsx

Oops! Something went wrong! :(

ESLint: 7.5.0

Error: Cannot read config file: O:\git.workspace\electron.workspace\.eslintrc.js
Error: Cannot find module './configs/webpack.config.eslint.js'
Require stack:
- O:\git.workspace\electron.workspace\.eslintrc.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\config-array-factory.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\cli-engine.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\eslint\eslint.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\eslint\index.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.resolve (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\v8-compile-cache\v8-compile-cache.js:166:23)
    at Object.<anonymous> (O:\git.workspace\electron.workspace\.eslintrc.js:3:22)
    at Module._compile (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at module.exports (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\import-fresh\index.js:31:59)
    at loadJSConfigFile (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\config-array-factory.js:218:16)error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by doublethinkio** [comment]
I found the reason：https://github.com/benmosher/eslint-plugin-import/issues/1865#issuecomment-667668108

**Comment by doublethinkio** [comment]
I found the reason：https://github.com/benmosher/eslint-plugin-import/issues/1865#issuecomment-667668108
