### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by metju90** [electron-react-boilerplate/electron-react-boilerplate#2543]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

I expect to install dependencies with `yarn` without any issues.

## Current Behavior

When I executed `yarn`  the following error was thrown:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Steps to Reproduce

1. Clone a new copy of the repo
2. In the root of the directory execute `yarn`

## Your Environment

- Node version : v10.16.3
- electron-react-boilerplate version or branch : Master
- Operating System and version : Mac 10.15.5
- Link to your project : N/A

**Comment by metju90** [comment]
This issue occurred to be right after installing yarn with brew. Not sure how, but the following line fixed the issue for me `yarn global add npm`

https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver#answer-49422151
