### ISSUE TITLE
Sequelize cannot find Sqlite3 even though it's added in app/package.json

### ISSUE THREAD

**Issue by andresmejia3** [electron-react-boilerplate/electron-react-boilerplate#2576]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

The app should have launched and recognized that sqlite3 is installed.

## Current Behavior

```
yarn
yarn install v1.22.4
$ node ./internals/scripts/CheckYarn.js
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall
npm ERR! peer dep missing: electron@^7.0.0, required by browserslist-config-erb@0.0.1
npm ERR! peer dep missing: eslint-config-airbnb-typescript@^8.0.2, required by eslint-config-erb@1.0.0
npm ERR! peer dep missing: eslint-plugin-jsx-a11y@6.2.3, required by eslint-config-erb@1.0.0
npm ERR! peer dep missing: immutable@^3.8.1 || ^4.0.0-rc.1, required by connected-react-router@6.8.0
npm ERR! peer dep missing: seamless-immutable@^7.1.3, required by connected-react-router@6.8.0
npm ERR! peer dep missing: eslint-plugin-flowtype@^5.1.3, required by eslint-config-erb@1.0.0
Native dependencies could not be checked
  • electron-builder  version=22.7.0
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=darwin arch=x64 appDir=/Users/andresmejia/Code/Projects/Test/test/app
yarn run v1.22.4
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors
Hash: 7d6cc47810df5e431167
Version: webpack 4.43.0
Time: 1972ms
Built at: 09/03/2020 12:55:12 AM
              Asset      Size    Chunks             Chunk Names
renderer.dev.dll.js  6.19 MiB  renderer  [emitted]  renderer
Entrypoint renderer = renderer.dev.dll.js
[0] dll renderer 12 bytes {renderer} [built]
[./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {renderer} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {renderer} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {renderer} [built]
[child_process] external "child_process" 42 bytes {renderer} [built]
[crypto] external "crypto" 42 bytes {renderer} [built]
[electron] external "electron" 42 bytes {renderer} [built]
[events] external "events" 42 bytes {renderer} [built]
[fs] external "fs" 42 bytes {renderer} [built]
[http] external "http" 42 bytes {renderer} [built]
[https] external "https" 42 bytes {renderer} [built]
[os] external "os" 42 bytes {renderer} [built]
[path] external "path" 42 bytes {renderer} [built]
[querystring] external "querystring" 42 bytes {renderer} [built]
[url] external "url" 42 bytes {renderer} [built]
    + 675 hidden modules

WARNING in ./node_modules/electron-debug/index.js 108:45-58
Critical dependency: the request of a dependency is an expression
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js 109:61-74
Critical dependency: the request of a dependency is an expression
 @ dll renderer

WARNING in ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js 69:15-63
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/sequelize/lib/dialects/postgres/connection-manager.js
 @ ./node_modules/sequelize/lib/dialects/postgres/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ dll renderer

WARNING in ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js 74:13-32
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/sequelize/lib/dialects/postgres/connection-manager.js
 @ ./node_modules/sequelize/lib/dialects/postgres/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ dll renderer

ERROR in ./node_modules/sequelize/lib/dialects/postgres/hstore.js
Module not found: Error: Can't resolve 'pg-hstore' in '/Users/andresmejia/Code/Projects/Test/test/node_modules/sequelize/lib/dialects/postgres'
 @ ./node_modules/sequelize/lib/dialects/postgres/hstore.js 3:15-35
 @ ./node_modules/sequelize/lib/dialects/postgres/data-types.js
 @ ./node_modules/sequelize/lib/data-types.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ dll renderer
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
## Steps to Reproduce

1. git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name

2. cd your-project-name

3. yarn

4. yarn add sequelize

5. cd app

6. yarn add sqlite3

7. Add lines to ping the SQLite database using sequelize in main.dev.ts:
```
const Sequelize = require('sequelize');
const sequelize = new Sequelize('sqlite::memory:');

const onLaunch = async () => {
  try {
    await sequelize.authenticate();
    console.log('Ping')
  } catch (e) {
    console.log('Error:', e)
  }
  return createWindow()
}

if (process.env.E2E_BUILD === 'true') {
  // eslint-disable-next-line promise/catch-or-return
  app.whenReady().then(onLaunch);
} else {
  app.on('ready', onLaunch);
}

```

8. cd ..

9. yarn dev

After trying to run in dev mode I get the following errors:

```
yarn run v1.22.4
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...
ℹ ｢wds｣: Project is running at http://localhost:1212/
ℹ ｢wds｣: webpack output is served from http://localhost:1212/dist
ℹ ｢wds｣: Content not from webpack is served from /Users/andresmejia/Code/Projects/Test/test/configs/dist
ℹ ｢wds｣: 404s will fallback to /index.html
npm WARN lifecycle The node binary used for scripts is /var/folders/2j/bnsm85f95tb26yhwg6jwlm580000gn/T/yarn--1599109702057-0.9691046206599772/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> electron-react-boilerplate@1.3.0 start-main-dev /Users/andresmejia/Code/Projects/Test/test
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts

App threw an error during load
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/Users/andresmejia/Code/Projects/Test/test/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/Users/andresmejia/Code/Projects/Test/test/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
    at new SqliteDialect (/Users/andresmejia/Code/Projects/Test/test/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
    at new Sequelize (/Users/andresmejia/Code/Projects/Test/test/node_modules/sequelize/lib/sequelize.js:340:20)
    at Object.<anonymous> (/Users/andresmejia/Code/Projects/Test/test/app/main.dev.ts:117:19)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Module._compile (/Users/andresmejia/Code/Projects/Test/test/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Object.newLoader [as .ts] (/Users/andresmejia/Code/Projects/Test/test/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:816:32)
ℹ ｢wdm｣: Compiled successfully.
```

Then an error window pops up from electron with the same error message

## Context

This issue prevents me from running sequelize to use SQLite easily. The only changes that I've made to the boilerplate is adding sequelize to package.json and adding sqlite3 to app/package.json using yarn. I also added the lines provided in step 9 of ```steps to reproduce``` to ping the SQLite database using sequelize

## Your Environment

- Node version : v14.5.0
- electron-react-boilerplate version or branch : master
- Operating System and version : MacOS Catalina v10.15.5

**Comment by suiyuex** [comment]
hi, this is not a bug, you should not perform `yarn add sqlite3` after `cd app`, so yo can just remove the fifth step of reproduce and try again

**Comment by andresmejia3** [comment]
@suiyuex But Sequelize needs Sqlite3 to run. How else would I get that dependency? I'm not sure if I'm misunderstanding, but in https://sequelize.org/master/manual/getting-started.html it claims that I need both.

**Comment by suiyuex** [comment]
you can cannot add Sqlite3 in `app/package.json` when `Sequelize ` added in your `your-project-name/package.json`, but you can add it in `your-project-name/package.json`, 
or you can add both `Sqlite3 ` and `Sequelize ` to your **app/package.json** or **your-project-name/package.json**

**Comment by andresmejia3** [comment]
@suiyuex It works now! Thanks a lot, I've been trying to fix this for a few days. I was following the ```adding dependencies``` guide strictly. Thanks again!

**Comment by andresmejia3** [comment]
@suiyuex It works now! Thanks a lot, I've been trying to fix this for a few days. I was following the adding dependencies guide strictly. Thanks again!
