### ISSUE TITLE
Leaflet and react-leaflet install fails

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-react-boilerplate/electron-react-boilerplate#2649]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
Leaflet and react-leaflet to be installed without any issue

## Current Behavior
installation fails

## Steps to Reproduce

1. clone electron-react-boilerplate

2. cd electron-react-boilerplate

3. yarn add leaflet react-leaflet

## Context
I am trying to use leaflet along with react but installation fails
<details>
<summary>Output</summary>
<br>

```
yarn add v1.22.4
$ node ./internals/scripts/CheckYarn.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ leaflet@1.7.1
info All dependencies
└─ leaflet@1.7.1
$ node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall
  • electron-builder  version=22.8.0
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/home/loopaz/Projects/Noscrio/ADiA-reboot/app
  ⨯ /home/loopaz/.nvm/versions/node/v14.15.0/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild
yarn run v1.22.4
$ node -r ../internals/scripts/BabelRegister.js ../internals/scripts/ElectronRebuild.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:

Error output:
warning ../package.json: License should be a valid SPDX license expression
warning ../package.json: License should be a valid SPDX license expression
- Searching dependency tree
✖ Rebuild Failed
[31m
An unhandled error occurred inside electron-rebuild[39m
[31mgyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.15.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/loopaz/.electron-gyp/8.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/loopaz/.electron-gyp/8.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/loopaz/.electron-gyp/8.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi/build'
make: Leaving directory '/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi/build'
make: *** No rule to make target 'Release/obj.target/nothing/../../../node-addon-api/src/nothing.o', needed by 'Release/obj.target/../../../node-addon-api/src/nothing.a'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-52-generic
gyp ERR! command "/home/loopaz/.nvm/versions/node/v14.15.0/bin/node" "/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=8.5.0" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.15.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/loopaz/.electron-gyp/8.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/loopaz/.electron-gyp/8.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/loopaz/.electron-gyp/8.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi/build'
make: Leaving directory '/home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi/build'
make: *** No rule to make target 'Release/obj.target/nothing/../../../node-addon-api/src/nothing.o', needed by 'Release/obj.target/../../../node-addon-api/src/nothing.a'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-52-generic
gyp ERR! command "/home/loopaz/.nvm/versions/node/v14.15.0/bin/node" "/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=8.5.0" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/loopaz/Projects/Noscrio/ADiA-reboot/app/node_modules/ffi-napi
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/rxjs/internal/Subscriber.js:143:22)[39m
child_process.js:655
    throw err;
    ^

Error: Command failed: ../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (/home/loopaz/Projects/Noscrio/ADiA-reboot/internals/scripts/ElectronRebuild.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/home/loopaz/Projects/Noscrio/ADiA-reboot/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 15762,
  stdout: null,
  stderr: null
}
```
</details>

## Your Environment

- Node version : 14.15.0
- electron-react-boilerplate version or branch : master
- Operating System and version : Ubuntu 20.04
- Link to your project : NA

**Comment by MD-AZMAL** [comment]
Gives the same issue on installing react-map-gl

**Comment by amilajack** [comment]
What's the stacktrace

**Comment by MD-AZMAL** [comment]
The stack trace is not being printed properly in the terminal. Too many empty spaces I have redirected the output to a file so i can share it.

<details>
<summary>Output</summary>
<br>

```
yarn add v1.22.4
$ node ./internals/scripts/CheckYarn.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ react-map-gl@5.2.10
info All dependencies
└─ react-map-gl@5.2.10
$ node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall
  • electron-builder  version=22.8.0
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/home/loopaz/Projects/Noscrio/ADiA-reboot/app
yarn run v1.22.4
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors
Hash: [1m2af3af54bd2dc4b5d0e4[39m[22m
Version: webpack [1m4.44.1[39m[22m
Time: [1m7996[39m[22mms
Built at: 09/11/2020 [1m4:41:46 pm[39m[22m
              [1mAsset[39m[22m     [1mSize[39m[22m    [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m[1mChunk Names[39m[22m
[1m[32mrenderer.dev.dll.js[39m[22m  7.5 MiB  [1mrenderer[39m[22m  [1m[32m[emitted][39m[22m  renderer
Entrypoint [1mrenderer[39m[22m = [1m[32mrenderer.dev.dll.js[39m[22m
[0] [1mdll renderer[39m[22m 12 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[./node_modules/electron-debug sync recursive] [1m./node_modules/electron-debug sync[39m[22m 160 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[./node_modules/webpack/buildin/harmony-module.js] [1m(webpack)/buildin/harmony-module.js[39m[22m 573 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[./node_modules/webpack/buildin/module.js] [1m(webpack)/buildin/module.js[39m[22m 497 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[child_process] [1mexternal "child_process"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[crypto] [1mexternal "crypto"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[electron] [1mexternal "electron"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[events] [1mexternal "events"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[fs] [1mexternal "fs"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[http] [1mexternal "http"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[https] [1mexternal "https"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[os] [1mexternal "os"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[path] [1mexternal "path"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[querystring] [1mexternal "querystring"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
[url] [1mexternal "url"[39m[22m 42 bytes {[1m[33mrenderer[39m[22m}[1m[32m [built][39m[22m
    + 1162 hidden modules

[1m[33mWARNING in ./node_modules/electron-debug/index.js 108:45-58
Critical dependency: the request of a dependency is an expression
 @ dll renderer[39m[22m

[1m[33mWARNING in ./node_modules/electron-debug/index.js 109:61-74
Critical dependency: the request of a dependency is an expression
 @ dll renderer[39m[22m
Done in 12.29s.
[96m[1mThank you for using adia-reboot![96m[1m
[0m[96mIf you rely on this package, please consider supporting our open collective:[22m[39m
> [94mhttps://opencollective.com/electron-react-boilerplate-594/donate[0m

Done in 37.45s.
```
</details>

This is what I get, seems pretty weird.

**Comment by MD-AZMAL** [comment]
its happening with almost all dependencies tried in a fresh boilerplate as well

**Comment by MD-AZMAL** [comment]
@amilajack could you suggest any method to solve this?

**Comment by amilajack** [comment]
That is the expected output. As long as it doesn't exit with non zero exit code then it is most likely working as expected.
