### ISSUE TITLE
Unable to install ffi

### ISSUE THREAD

**Issue by femiveys** [electron-react-boilerplate/electron-react-boilerplate#2666]
## Prerequisites
- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
```
cd app
yarn add ffi
```

Installing node-ffi should not give an error

## Current Behavior
When trying to install node-ffi, the module gets installed, but the rebuild afterwards goes in error:

## Steps to Reproduce
```
clone the repository
cd <myrepo>
yarn
cd app
yarn add ffi
```

Error:
```
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/femi/Sync/apps/esko/ffi/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/femi/.nvm/versions/node/v10.23.0/bin/node" "/Users/femi/Sync/apps/esko/ffi/node_modules/.bin/node-gyp" "rebuild" "--target=8.5.0" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/femi/Sync/apps/esko/ffi/app/node_modules/ref
gyp ERR! node -v v10.23.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/femi/Sync/apps/esko/ffi/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/femi/Sync/apps/esko/ffi/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/femi/Sync/apps/esko/ffi/node_modules/rxjs/internal/Subscriber.js:143:22)
child_process.js:669
    throw err;
    ^

Error: Command failed: ../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/Users/femi/Sync/apps/esko/ffi/internals/scripts/ElectronRebuild.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/femi/Sync/apps/esko/ffi/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/femi/Sync/apps/esko/ffi/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Your Environment
- Node version : v10.23.0
- electron-react-boilerplate version or branch : master
- Operating System and version : OSX 10.15.7

**Comment by jooohhn** [comment]
Hey femiveys, it might be a problem with `node-ffi`'s support for node@12 which is used in electron@8 

Related thread: https://github.com/electron/electron-rebuild/issues/344

**Comment by femiveys** [comment]
I have been able to solve the problem by using [node-ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi).
