### ISSUE TITLE
Error: Cannot find module '../.erb/scripts/node_modules/@babel/register' when trying to re-implement Redux

### ISSUE THREAD

**Issue by NicolasNewman** [electron-react-boilerplate/electron-react-boilerplate#2692]
## Summary

For security purposes, I need an updated version of Electron. After trying to update it unsuccessfully in v1, I'm now attempting to re-implement Redux to v2 using the Counter example from v1. When I attempt to lint the project, I get the following error:

```
Error resolving webpackConfig Error: Cannot find module '../.erb/scripts/node_modules/@babel/register'
Require stack:
- C:\...\electron-react-boilerplate\.erb\configs\webpack.config.eslint.js
- C:\...\electron-react-boilerplate\node_modules\eslint-import-resolver-webpack\index.js
- C:\...\electron-react-boilerplate\node_modules\eslint-module-utils\resolve.js
- C:\...\electron-react-boilerplate\node_modules\eslint-plugin-import\lib\rules\no-unresolved.js     
- C:\...\electron-react-boilerplate\node_modules\eslint-plugin-import\lib\index.js
- C:\...\electron-react-boilerplate\node_modules\@eslint\eslintrc\lib\config-array-factory.js        
- C:\...\electron-react-boilerplate\node_modules\@eslint\eslintrc\lib\index.js
- C:\...\electron-react-boilerplate\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\...\electron-react-boilerplate\node_modules\eslint\lib\eslint\eslint.js
- C:\...\electron-react-boilerplate\node_modules\eslint\lib\eslint\index.js
- C:\...\electron-react-boilerplate\node_modules\eslint\lib\cli.js
- C:\...\electron-react-boilerplate\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (C:\...\electron-react-boilerplate\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\...\electron-react-boilerplate\.erb\configs\webpack.config.eslint.js:2:1)
    at Module._compile (C:\...\electron-react-boilerplate\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\...\\electron-react-boilerplate\\.erb\\configs\\webpack.config.eslint.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint-import-resolver-webpack\\index.js', 
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint-module-utils\\resolve.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint-plugin-import\\lib\\rules\\no-unresolved.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint-plugin-import\\lib\\index.js',      
    'C:\\...\\electron-react-boilerplate\\node_modules\\@eslint\\eslintrc\\lib\\config-array-factory.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\@eslint\\eslintrc\\lib\\index.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint\\lib\\cli-engine\\cli-engine.js',   
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint\\lib\\eslint\\eslint.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint\\lib\\eslint\\index.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint\\lib\\cli.js',
    'C:\\...\\electron-react-boilerplate\\node_modules\\eslint\\bin\\eslint.js'
  ]
}
```

The error seems to originate from the Counter and Home component inside of /components when react is imported. There doesn't seem to be a package.json in the scripts folder. Likewise, going into BabelRegister.js doesn't show any errors and successfully resolves the `require('@babel/register')` import in node_modules of the root directory.

**Comment by NicolasNewman** [comment]
I should mention that running `yarn start` successfully launches the program with no errors, however Husky fails with the above error when I try and push to my own repo.

**Comment by NicolasNewman** [comment]
Changing line 3 of the file `.erb/scripts/BabelRegister.js` to `require('@babel/register')` appears to fix the issue for my needs.

**Comment by kyleawayan** [comment]
Same, just getting this error right now when I try to push. Was able to push to my repo like a few days ago.

**Comment by kyleawayan** [comment]
> 
> 
> Changing line 3 of the file `.erb/scripts/BabelRegister.js` to `require('@babel/register')` appears to fix the issue for my needs.

My `BabelRegister.js` looks like this, even with the require:
```JS
const path = require('path');

require('@babel/register')({
  extensions: ['.es6', '.es', '.jsx', '.js', '.mjs', '.ts', '.tsx'],
  cwd: path.join(__dirname, '../..'),
});
```

Still can't push without getting the same error you had.

**Comment by kyleawayan** [comment]
Never mind, I was just able to push, even with Husky. Weird, looks like it fixed itself 😄

**Comment by brioapp** [comment]
Same here. when trying to add redux.

**Comment by kyleawayan** [comment]
Oh, my bad, I didn't realize this error was caused by Redux. I didn't touch Redux at all, so my error may be different. 

But I did still get the same error here in this issue all of a sudden when I tried to push. I was able to push yesterday without changing any configs, which was weird.

But my friend recently tried to push to the same repo on his end, but it gave him the error I was getting.

**Comment by rendomnet** [comment]
same problem. app runs but cant git commit

**Comment by LarryKlugerDS** [comment]
I'm having the same problem. My BabelRegister.js is the same as @kyleawayan's 

Messages from git (Husky):

````
Commit failed - exit code 1 received, with output: 'husky > pre-commit (node v12.20.0)
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.{js,jsx,ts,tsx}
[STARTED] Running tasks for {*.json,.{babelrc,eslintrc,prettierrc}}
[STARTED] Running tasks for *.{css,scss}
[STARTED] Running tasks for *.{html,md,yml}
[STARTED] cross-env NODE_ENV=development eslint --cache
[STARTED] prettier --ignore-path .eslintignore --parser json --write
[STARTED] prettier --ignore-path .eslintignore --single-quote --write
[STARTED] prettier --ignore-path .eslintignore --single-quote --write
[SUCCESS] prettier --ignore-path .eslintignore --parser json --write
[SUCCESS] Running tasks for {*.json,.{babelrc,eslintrc,prettierrc}}
[SUCCESS] prettier --ignore-path .eslintignore --single-quote --write
[SUCCESS] Running tasks for *.{css,scss}
[SUCCESS] prettier --ignore-path .eslintignore --single-quote --write
[SUCCESS] Running tasks for *.{html,md,yml}
[FAILED] cross-env NODE_ENV=development eslint --cache [FAILED]
[FAILED] cross-env NODE_ENV=development eslint --cache [FAILED]
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...

✖ cross-env NODE_ENV=development eslint --cache:

Oops! Something went wrong! :(

ESLint: 7.16.0

Error: Cannot find module '../.erb/scripts/node_modules/@babel/register'
Require stack:
- /Users/larry.kluger/www/electron-react-boilerplate/.erb/configs/webpack.config.eslint.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-import-resolver-webpack/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-module-utils/resolve.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-plugin-import/lib/rules/no-unresolved.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-plugin-import/lib/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/@eslint/eslintrc/lib/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/eslint/eslint.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/eslint/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/cli.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/larry.kluger/www/electron-react-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/larry.kluger/www/electron-react-boilerplate/.erb/configs/webpack.config.eslint.js:2:1)
    at Module._compile (/Users/larry.kluger/www/electron-react-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
Error resolving webpackConfig Error: Cannot find module '../.erb/scripts/node_modules/@babel/register'
Require stack:
- /Users/larry.kluger/www/electron-react-boilerplate/.erb/configs/webpack.config.eslint.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-import-resolver-webpack/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-module-utils/resolve.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-plugin-import/lib/rules/no-unresolved.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-plugin-import/lib/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/@eslint/eslintrc/lib/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/eslint/eslint.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/eslint/index.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/cli.js
- /Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/larry.kluger/www/electron-react-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/larry.kluger/www/electron-react-boilerplate/.erb/configs/webpack.config.eslint.js:2:1)
    at Module._compile (/Users/larry.kluger/www/electron-react-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/larry.kluger/www/electron-react-boilerplate/.erb/configs/webpack.config.eslint.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-import-resolver-webpack/index.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-module-utils/resolve.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-plugin-import/lib/rules/no-unresolved.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint-plugin-import/lib/index.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/@eslint/eslintrc/lib/config-array-factory.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/@eslint/eslintrc/lib/index.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/cli-engine/cli-engine.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/eslint/eslint.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/eslint/index.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/lib/cli.js',
    '/Users/larry.kluger/www/electron-react-boilerplate/node_modules/eslint/bin/eslint.js'
  ]
}
husky > pre-commit hook failed (add --no-verify to bypass)'
````

**Comment by TylerJNewman** [comment]
> Changing line 3 of the file `.erb/scripts/BabelRegister.js` to `require('@babel/register')` appears to fix the issue for my needs.

this worked for me, thanks

**Comment by rendomnet** [comment]
@TylerJNewman 
const path = require('path');

this is my BabelRegister.js

require('@babel/register')({
  extensions: ['.es6', '.es', '.jsx', '.js', '.mjs', '.ts', '.tsx'],
  cwd: path.join(__dirname, '../..'),
});

what should I do?

**Comment by TylerJNewman** [comment]
> @TylerJNewman
> const path = require('path');
> 
> this is my BabelRegister.js
> 
> 
> ```
> const path = require('path');
> 
> require('@babel/register')({
>   extensions: ['.es6', '.es', '.jsx', '.js', '.mjs', '.ts', '.tsx'],
>   cwd: path.join(__dirname, '../..'),
> });
> ```
> 
> what should I do?
^that code above is correct

here is the change I made in the following file: ```.erb/configs/webpack.config.eslint.js```

<img width="565" alt="Screen Shot 2020-12-30 at 8 10 12 PM" src="https://user-images.githubusercontent.com/8213268/103394064-09583100-4adb-11eb-92b8-81bdbda43e96.png">

hope that is more clear
