### ISSUE TITLE
Yarn rebuild error with serialport library

### ISSUE THREAD

**Issue by dbmanny18** [electron-react-boilerplate/electron-react-boilerplate#2724]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
Installed serialport library. Expected to run yarn rebuild and to have a successful rebuild.

## Current Behavior
**I am receiving an error when doing yarn rebuild**

PREFACE: I cloned the library without modifications
1.) I installed "serialport": "^9.0.4".
2.) Ran yarn rebuild
3.) Getting error:
 
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/manny/Documents/GitHub/electron-react/src/node_modules/@serialport/bindings'.
Error: `gyp` failed with exit code: 1

Error: node-gyp failed to rebuild '/Users/manny/Documents/GitHub/electron-react/src/node_modules/@serialport/bindings'.
Error: `gyp` failed with exit code: 1

    at ModuleRebuilder.rebuildNodeGypModule (/Users/manny/Documents/GitHub/electron-react/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

NOTE:
1.) I checked to make sure i have command line tools installed on mac
2.) Tried downgrading to different versions of serialport with same problem occurring
3.) Tried this repo which is electron with serialport and it works:
https://github.com/serialport/electron-serialport

## Your Environment

- Node version : local node version V12.14.1
- electron-react-boilerplate version or branch : master branch
- Operating System and version : macOs bigSur 11.1

**Comment by dbmanny18** [comment]
Problem fixed. It may have been because a long time ago I accidentally used npm instead of yarn to install a package and something got screwed up. Started again from scratch with only yarn and it works again. One thing I also added was:

app.allowRendererProcessReuse = false;
within the main.dev.ts createWindow function, because I was getting another error at that point along the lines of "Requiring Native Modules in the Renderer Process".

This fixed all problems and works perfectly now.
