### ISSUE TITLE
 TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by royeradames** [electron-react-boilerplate/electron-react-boilerplate#2760]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [X] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
Successful installation

## Current Behavior

$ rm -rf node_modules &&
> yarn cache clean &&
> yarn &&
> yarn electron-rebuild &&
> yarn dev
yarn cache v1.22.10
success Cleared cache.
Done in 15.48s.
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.2.1: The platform "win32" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > enzyme-adapter-react-16@1.15.5" has incorrect peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.15.5" has incorrect peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.13.1" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-config-airbnb-typescript@^8.0.2".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-import-resolver-webpack@^0.12.2".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-plugin-jest@^23.13.2".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".
warning " > eslint-config-erb@2.0.0" has unmet peer dependency "eslint-plugin-testcafe@^0.2.1".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "react@^16.13.1".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has incorrect peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config
./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=D:\lambda\projects\testing_electron\src
yarn run v1.22.10
$ D:\lambda\projects\testing_electron\node_modules\.bin\cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (D:\lambda\projects\testing_electron\node_modules\webpack\lib\NormalModule.js:171:10)
    at D:\lambda\projects\testing_electron\node_modules\webpack\lib\LoaderOptionsPlugin.js:43:17
    at Hook.eval (eval at create (D:\Lambda\projects\testing_electron\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (D:\Lambda\projects\testing_electron\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (D:\Lambda\projects\testing_electron\node_modules\webpack\lib\Compiler.js:943:26)
    at D:\Lambda\projects\testing_electron\node_modules\webpack\lib\Compiler.js:984:29
    at Hook.eval [as callAsync] (eval at create (D:\Lambda\projects\testing_electron\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Lambda\projects\testing_electron\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (D:\Lambda\projects\testing_electron\node_modules\webpack\lib\Compiler.js:979:28)
    at D:\Lambda\projects\testing_electron\node_modules\webpack\lib\Compiler.js:470:12
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

## Steps to Reproduce

1. git clone https://github.com/royeradames/testing_electron.git
2. cd testing_electron
3. yarn

## Possible Solution (Not obligatory)

None

## Your Environment

- Node version: Node.js v14.15.1.
- electron-react-boilerplate version or branch: main
- Operating System and version: windows 10
- Link to your project: https://github.com/royeradames/testing_electron

**Comment by royeradames** [comment]
Solution:
Looks like you have something in your globally installed npm packages, I had to remove them all (just rm -rf /usr/local/lib/node_modules) and reinstall everything. Maybe there was a more sane way to do it.

Then yarn will compile without an error.

https://stackoverflow.com/a/65626897/3044126
