### ISSUE TITLE
Webpack not copying custom node addon to asar

### ISSUE THREAD

**Issue by mithusingh32** [electron-react-boilerplate/electron-react-boilerplate#2769]
## Prerequisites

- [ X] Using yarn
- [ X] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ X] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [X ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [X ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
Fedora 33 OS - Electron app launches without issue after running `yarn package` with custom node addon being copied into the asar file. 

## Current Behavior

Webpack is not copying custom node addon during package. 
When executing the AppImage I get this error: 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /tmp/.mount_ElectrvLyf4E/audio-processor/build/Release/addon.node: Error: /tmp/.mount_ElectrvLyf4E/audio-processor/build/Release/addon.node: cannot open shared object file: No such file or directory
    at Object.64516 (/tmp/.mount_ElectrvLyf4E/resources/app.asar/main.prod.js:2:548475)
    at r (/tmp/.mount_ElectrvLyf4E/resources/app.asar/main.prod.js:2:720268)
    at Module.56808 (/tmp/.mount_ElectrvLyf4E/resources/app.asar/main.prod.js:2:3857)
    at r (/tmp/.mount_ElectrvLyf4E/resources/app.asar/main.prod.js:2:720268)
    at /tmp/.mount_ElectrvLyf4E/resources/app.asar/main.prod.js:2:720779
    at Object.<anonymous> (/tmp/.mount_ElectrvLyf4E/resources/app.asar/main.prod.js:2:720793)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
```

Loaders used: 
- node-loader
- native-ext-loader

I've checked the asar file, and the .node file is not there. 

## Steps to Reproduce

webpack.config.main.prod.babel.js:
``` javascript
/**
 * Webpack config for production electron main process
 */

import path from 'path';
import webpack from 'webpack';
import { merge } from 'webpack-merge';
import TerserPlugin from 'terser-webpack-plugin';
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';
import baseConfig from './webpack.config.base';
import CheckNodeEnv from '../scripts/CheckNodeEnv';
import DeleteSourceMaps from '../scripts/DeleteSourceMaps';

CheckNodeEnv('production');
DeleteSourceMaps();

const devtoolsConfig = process.env.DEBUG_PROD === 'true' ? {
  devtool: 'source-map'
} : {};

export default merge(baseConfig, {
  ...devtoolsConfig,

  mode: 'production',

  target: 'electron-main',

  entry: './src/main/main.dev.ts',

  output: {
    path: path.join(__dirname, '../../'),
    filename: './src/main.prod.js',
  },

  optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
      }),
    ]
  },
  
  module: {
    rules:[
      {
        test: /\.node$/,
        loader: "node-loader",
      }
    ]
  },


  plugins: [
    new BundleAnalyzerPlugin({
      analyzerMode:
        process.env.OPEN_ANALYZER === 'true' ? 'server' : 'disabled',
      openAnalyzer: process.env.OPEN_ANALYZER === 'true',
    }),

    /**
     * Create global constants which can be configured at compile time.
     *
     * Useful for allowing different behaviour between development builds and
     * release builds
     *
     * NODE_ENV should be production so that modules do not perform certain
     * development checks
     */
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      DEBUG_PROD: false,
      START_MINIMIZED: false,
    }),
  ],
  /**
   * Disables webpack processing of __dirname and __filename.
   * If you run the bundle in node.js it falls back to these values of node.js.
   * https://github.com/webpack/webpack/issues/2010
   */
  node: {
    __dirname: false,
    __filename: false,
  },
});
```

main.dev.ts:
``` javascript
/* eslint global-require: off, no-console: off */

/**
 * This module executes inside of electron's main process. You can start
 * electron renderer process from here and communicate with the other processes
 * through IPC.
 *
 * When running `yarn build` or `yarn build-main`, this file is compiled to
 * `./src/main.prod.js` using webpack. This gives us some performance wins.
 */
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import path from 'path';
import { app, BrowserWindow, ipcMain, shell } from 'electron';
import { autoUpdater } from 'electron-updater';
import log from 'electron-log';
import MenuBuilder from './menu';

// This works, but need to create typing for it
import AudioProcessor from '../../audio-processor/build/Release/addon.node';

export default class AppUpdater {
  constructor() {
    log.transports.file.level = 'info';
    autoUpdater.logger = log;
    autoUpdater.checkForUpdatesAndNotify();
  }
}

let mainWindow: BrowserWindow | null = null;

if (process.env.NODE_ENV === 'production') {
  const sourceMapSupport = require('source-map-support');
  sourceMapSupport.install();
}

if (
  process.env.NODE_ENV === 'development' ||
  process.env.DEBUG_PROD === 'true'
) {
  require('electron-debug')();
}

const installExtensions = async () => {
  const installer = require('electron-devtools-installer');
  const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
  const extensions = ['REACT_DEVELOPER_TOOLS'];

  return installer
    .default(
      extensions.map((name) => installer[name]),
      forceDownload
    )
    .catch(console.log);
};

const createWindow = async () => {
  if (
    process.env.NODE_ENV === 'development' ||
    process.env.DEBUG_PROD === 'true'
  ) {
    await installExtensions();
  }

  const RESOURCES_PATH = app.isPackaged
    ? path.join(process.resourcesPath, 'assets')
    : path.join(__dirname, '../../assets');

  const getAssetPath = (...paths: string[]): string => {
    return path.join(RESOURCES_PATH, ...paths);
  };

  mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      nodeIntegration: true,
    },
  });

  mainWindow.loadURL(`file://${__dirname}/../index.html`);

  // @TODO: Use 'ready-to-show' event
  //        https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event
  mainWindow.webContents.on('did-finish-load', () => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    if (process.env.START_MINIMIZED) {
      mainWindow.minimize();
    } else {
      mainWindow.show();
      mainWindow.focus();
    }
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();

  // Open urls in the user's browser
  mainWindow.webContents.on('new-window', (event, url) => {
    event.preventDefault();
    shell.openExternal(url);
  });

  // Remove this if your app does not use auto updates
  // eslint-disable-next-line
  new AppUpdater();
};

/**
 * Add event listeners...
 */

app.on('window-all-closed', () => {
  // Respect the OSX convention of having the application in memory even
  // after all windows have been closed
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.whenReady().then(createWindow).catch(console.log);

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) createWindow();
});

// Event handler for asynchronous incoming messages
ipcMain.on('processAudio', (event, args) => {
  AudioProcessor.getData(args, (err: any, resp: any) => {
    event.sender.send('returnFromProcessAudio', resp);
  });
  // Event emitter for sending asynchronous messages
});
```

Addon is a custom c++ I created using cmake-js. It works when running `yarn start`

1. yarn package

2.  Execute the AppImage

## Context

The breaks my app when trying to make package. 

No major changes other than linking my node addon and making ipc calls between the renderer and main processes. 

## Your Environment

- Node version : 14.15.4
- electron-react-boilerplate version or branch : Latest
- Operating System and version : Fedora 33 Workstation
- Link to your project: Private at the moment

**Comment by balsigergil** [comment]
It seems to be an issue related to electron-builder. Did you add the path to your node file in `build.files` array in the package.json ?
To see if your node file is correctly packaged, you can add `"asar": true` to the build object in your package.json.
Maybe it's the link in the your `main.dev.ts` which is the problem. It is correct in dev but the link might need to change for the final packaged app.

**Comment by mithusingh32** [comment]
I did not add it to the package.json, I will give that a try. 

I was under the impression that you need to add to the array if you're planning on rebuilding via node-gyp. The node-addon I've created is compiled w/ cmake-js that targets electron runtime. 

I do have 'asar' set to true.

**Comment by balsigergil** [comment]
Does it build successfully when you run `yarn build` ? Because you import your node file in the main.dev.ts so it should be built by webpack and bundled in the main.prod.js and not be imported afterward, right ?

**Comment by mithusingh32** [comment]
I have not tried `yarn build` but, I would assume that if `yarn package` worked, then build should. But I will run `yarn build` and get you the output. 

Webpack is doing its thing correctly, I think, because you can see the addon node file in the same directory as the main.prod.ts file when I do `yarn package`

**Comment by mithusingh32** [comment]
`yarn build` work as expected

**Comment by MrTob** [comment]
im working with Angular but i also have the same error. I want to include my custom, self written `.node` File into the App but i get following Error.
![chrome_y5SxfTeZBh](https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/30464573/085d6085-f9eb-4e55-91b1-60485af68fd9)

I also use electron-builder to package the App

**Comment by mithusingh32** [comment]
@MrTob I was able to get it working by using node-loader and restructuring the application a little.
Here's the repo: https://github.com/mithusingh32/musicalkey
I haven't worked on the project in a long time, so I'm not sure if it'll work now.
