### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module '../../url/index.tsx'

### ISSUE THREAD

**Issue by Atulin** [electron-react-boilerplate/electron-react-boilerplate#2797]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

It should work

## Current Behavior

It doesn't work

## Steps to Reproduce

1. Build an app and see it work
2. Try to replace the deprecated `node-sass` with Dart-sass
3. Watch how the app no longer starts
4. Go back to the deprecated ancient version of SASS and tell yourself that using `#{"min(100px, 20vw)"}` isn't that bad
5. The app remains broken
```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto

> start
> node -r @babel/register ./.erb/scripts/CheckPortInUse.js && cross-env yarn start:renderer

yarn run v1.22.5
$ cross-env NODE_ENV=development webpack serve --config ./.erb/configs/webpack.config.renderer.dev.babel.js
(node:26540) UnhandledPromiseRejectionWarning: Error: Cannot find module '../../url/index.tsx'
Require stack:
- G:\WebstormProjects\ChryssibooruDesktop\.erb\configs\webpack.config.renderer.dev.babel.js
- G:\WebstormProjects\ChryssibooruDesktop\node_modules\webpack-cli\lib\groups\resolveConfig.js
- G:\WebstormProjects\ChryssibooruDesktop\node_modules\webpack-cli\lib\webpack-cli.js
- G:\WebstormProjects\ChryssibooruDesktop\node_modules\webpack-cli\lib\bootstrap.js
- G:\WebstormProjects\ChryssibooruDesktop\node_modules\webpack-cli\bin\cli.js
- G:\WebstormProjects\ChryssibooruDesktop\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.resolve (G:\WebstormProjects\ChryssibooruDesktop\node_modules\v8-compile-cache\v8-compile-cache.js:164:23)
    at Object.<anonymous> (G:\WebstormProjects\ChryssibooruDesktop\.erb\configs\/webpack.config.renderer.dev.babel.js:47:13)
    at Module._compile (G:\WebstormProjects\ChryssibooruDesktop\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._compile (G:\WebstormProjects\ChryssibooruDesktop\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (G:\WebstormProjects\ChryssibooruDesktop\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 3.10s.

Process finished with exit code 0
```

## Context

Yeah, I did make some changes, like removing the menus or building my actual app on top. Hard to not make changes to boilerplate if you want to do something more than just run that boilerplate.

## Your Environment

- Node version : 14.10.1
- electron-react-boilerplate version or branch : whichever it is that the command in readme pulls from
- Operating System and version : Win10, up to date
- Link to your project : https://github.com/Atulin/Derpibooru-Desktop

**Comment by Atulin** [comment]
Solved by editing `.erb/configs/webpack.config.renderer.dev.babel.js` and swapping `require.resolve('../../url/index.tsx'),` for `require.resolve('../../src/index.tsx'),`
