### ISSUE TITLE
cannot rebuild sqlite3

### ISSUE THREAD

**Issue by Hybueno09** [electron-react-boilerplate/electron-react-boilerplate#2801]
## Summary

How can i build native module successfully

I clone the master branch of erb,i add sqlite3 into _./src/package.json_.I run _yarn_,then i throw error below:

yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=E:\test\electron-react-boilerplate\src
  ⨯ C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild
yarn run v1.22.10
$ node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  nothing.vcxproj -> E:\test\electron-react-boilerplate\src\node_modules\sqlite3\build\Release\\nothing.lib
  unpack_sqlite_dep
  'python2.7' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
  ���������ļ���
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: ��cmd.exe� ����˳�������Ϊ 1�� [E:\test\electron-react-boilerplate\src\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:

Error output:
- Searching dependency tree
gyp info find Python using Python version 2.7.15 found at "C:\Users\Jy12\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Jy12\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\sqlite3\\11.0.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=E:\\test\\electron-react-boilerplate\\src\\node_modules\\sqlite3\\11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=E:\\\\test\\\\electron-react-boilerplate\\\\src\\\\node_modules\\\\sqlite3\\\\11.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\test\\electron-react-boilerplate\\src\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   map: [Function (anonymous)]
gyp info spawn args ]
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'E:\test\electron-react-boilerplate\src\node_modules\sqlite3'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

Error: node-gyp failed to rebuild 'E:\test\electron-react-boilerplate\src\node_modules\sqlite3'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

    at ModuleRebuilder.rebuildNodeGypModule (E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\rebuild.js:183:9)
    at async Promise.all (index 104)
    at async Rebuilder.rebuild (E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\rebuild.js:141:13)
    at async E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\cli.js:145:9
child_process.js:655
    throw err;
    ^

Error: Command failed: ..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (E:\test\electron-react-boilerplate\.erb\scripts\/ElectronRebuild.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (E:\test\electron-react-boilerplate\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (E:\test\electron-react-boilerplate\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 24516,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
error Command failed with exit code 1.
  stackTrace=

**Comment by Hybueno09** [comment]
How can i fix it, thanks

**Comment by sahilbest999** [comment]
i have ran into similar issue

```
  ΓÇó electron-builder  version=22.9.1
  ΓÇó loaded configuration  file=package.json ("build" field)
  ΓÇó installing production dependencies  platform=win32 arch=x64 appDir=D:\Major Project\temp\src
  Γ¿» npm.cmd exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:

> electron-react-boilerplate@2.3.0 postinstall
> yarn electron-rebuild

yarn run v1.22.5
$ node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:

Error output:
- Searching dependency tree
Attempting to build a module with a space in the path
See https://github.com/nodejs/node-gyp/issues/65#issuecomment-368820565 for reasons why this may not work
gyp info find Python using Python version 3.8.5 found at "C:\Users\void\AppData\Local\Programs\Python\Python38\python.exe"
gyp ERR! find VS 
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2019
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
Γ£û Rebuild Failed
[31m
An unhandled error occurred inside electron-rebuild[39m
[31mnode-gyp failed to rebuild 'D:\Major Project\temp\src\node_modules\better-sqlite3'.
Error: Could not find any Visual Studio installation to use



Error: node-gyp failed to rebuild 'D:\Major Project\temp\src\node_modules\better-sqlite3'.
Error: Could not find any Visual Studio installation to use


    at ModuleRebuilder.rebuildNodeGypModule (D:\Major Project\temp\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (D:\Major Project\temp\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Promise.all (index 4)
    at async Rebuilder.rebuild (D:\Major Project\temp\node_modules\electron-rebuild\lib\src\rebuild.js:148:13)
    at async D:\Major Project\temp\node_modules\electron-rebuild\lib\src\cli.js:146:9[39m
child_process.js:655
    throw err;
    ^

Error: Command failed: ..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (D:\Major Project\temp\.erb\scripts\/ElectronRebuild.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (D:\Major Project\temp\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (D:\Major Project\temp\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 6956,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
npm ERR! code 1
npm ERR! path D:\Major Project\temp\src
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c yarn electron-rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\void\AppData\Local\npm-cache\_logs\2021-03-19T19_24_32_111Z-debug.log
```

**Comment by sahilbest999** [comment]
sqlite3 does not work i dont know why but better-sqlite3 works.

**Comment by Hybueno09** [comment]
But `ffi-napi` also does not work ,it throws error below:

```
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=E:\test\electron-react-boilerplate\src
  ⨯ C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild
yarn run v1.22.10
$ node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:

Error output:
- Searching dependency tree
gyp info find Python using Python version 3.6.5 found at "C:\Program Files\Python36\python.exe"
gyp info find Python using Python version 3.6.5 found at "C:\Program Files\Python36\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python36\python.exe
gyp info spawn args [
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\11.0.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=E:\\\\test\\\\electron-react-boilerplate\\\\src\\\\node_modules\\\\ref-napi\\\\11.0.1\\\\<(target_arch)\\\\node.lib',    
gyp info spawn args   '-Dmodule_root_dir=E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python36\python.exe
gyp info spawn args [
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\11.0.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\test\\electron-react-boilerplate\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=E:\\\\test\\\\electron-react-boilerplate\\\\src\\\\node_modules\\\\ref-napi\\\\11.0.1\\\\<(target_arch)\\\\node.lib',    
gyp info spawn args   '-Dmodule_root_dir=E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\test\\electron-react-boilerplate\\src\\node_modules\\ref-napi\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: E:\test\electron-react-boilerplate\src\node_modules\ref-napi\11.0.1\common.gypi not found (cwd: E:\test\electron-react-boilerplate\src\node_modules\ref-napi) while reading includes of binding.gyp while trying to load binding.gyp
gyp: E:\test\electron-react-boilerplate\src\node_modules\ref-napi\11.0.1\common.gypi not found (cwd: E:\test\electron-react-boilerplate\src\node_modules\ref-napi) while reading includes of binding.gyp while trying to load binding.gyp
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'E:\test\electron-react-boilerplate\src\node_modules\ref-napi'.
Error: `gyp` failed with exit code: 1



Error: node-gyp failed to rebuild 'E:\test\electron-react-boilerplate\src\node_modules\ref-napi'.
Error: `gyp` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\rebuild.js:183:9)
    at async Promise.all (index 7)
    at async Rebuilder.rebuild (E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\rebuild.js:141:13)
    at async E:\test\electron-react-boilerplate\node_modules\electron-rebuild\lib\src\cli.js:145:9
child_process.js:655
    throw err;
    ^

Error: Command failed: ..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (E:\test\electron-react-boilerplate\.erb\scripts\/ElectronRebuild.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (E:\test\electron-react-boilerplate\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (E:\test\electron-react-boilerplate\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 30020,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
error Command failed with exit code 1.
  stackTrace=
```
