### ISSUE TITLE
Cannot create property '-reg-example-com' on string '{\"-reg-example-com\":\"\"}'

### ISSUE THREAD

**Issue by vaibhav6233m** [electron-react-boilerplate/electron-react-boilerplate#2802]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

App should run without errors

## Current Behavior

App throws error on `yarn` command
![image](https://user-images.githubusercontent.com/29979122/111869236-5e9e3300-89a4-11eb-93ad-f6bc5575f510.png)
```
$ DEBUG_PROD=true yarn build && yarn start
yarn run v1.22.4
$ concurrently "yarn build:main" "yarn build:renderer"
$ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.main.prod.babel.js
$ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.renderer.prod.babel.js
[1] [webpack-cli] Compilation finished
[1] asset renderer.prod.js 325 KiB [emitted] [minimized] (name: main) 2 related assets
[1] asset style.css 736 bytes [emitted] [minimized] (name: main) 1 related asset
[1] Entrypoint main 325 KiB (1.3 MiB) = style.css 736 bytes renderer.prod.js 325 KiB 2 auxiliary assets
[1] orphan modules 107 KiB [orphan] 15 modules
[1] runtime modules 931 bytes 4 modules
[1] modules by path ./node_modules/core-js/modules/*.js 310 KiB 340 modules
[1] modules by path ./node_modules/core-js/internals/*.js 162 KiB 176 modules
[1] modules by path ./node_modules/core-js/proposals/*.js 6 KiB 28 modules
[1] modules by path ./node_modules/core-js/stage/*.js 1.47 KiB 7 modules
[1] modules by path ./node_modules/prop-types/ 2.58 KiB 3 modules
[1] modules by path ./src/ 107 KiB (javascript) 723 bytes (css/mini-extract) 2 modules
[1] modules by path ./node_modules/react/ 6.48 KiB 2 modules
[1] modules by path ./node_modules/react-dom/ 119 KiB 2 modules
[1] modules by path ./node_modules/react-router/ 10.7 KiB 2 modules
[1] modules by path ./node_modules/scheduler/ 4.91 KiB 2 modules
[1] modules by path ./node_modules/react-is/ 2.69 KiB 2 modules
[1] 6 modules
[1] webpack 5.5.1 compiled successfully in 20464 ms
[1] yarn build:renderer exited with code 0
[0] [webpack-cli] Compilation finished
[0] asset ./src/main.prod.js 706 KiB [emitted] [minimized] (name: main) 2 related assets
[0] 689 modules
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 108:45-58
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./src/main.dev.ts 43:2-27
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 109:61-74
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./src/main.dev.ts 43:2-27
[0]
[0] webpack 5.5.1 compiled with 2 warnings in 24122 ms
[0] yarn build:main exited with code 0
Done in 29.76s.
yarn run v1.22.4
$ node -r @babel/register ./.erb/scripts/CheckPortInUse.js && cross-env yarn start:renderer
$ cross-env NODE_ENV=development webpack serve --config ./.erb/configs/webpack.config.renderer.dev.babel.js
The DLL files are missing. Sit back while we build them for you with "yarn build-dll"
error An unexpected error occurred: "Cannot create property '-reg-example-com' on string '{\"-reg-example-com\":\"\"}'".
(node:44464) UnhandledPromiseRejectionWarning: Error: Command failed: yarn build-dll
error An unexpected error occurred: "Cannot create property '-reg-example-com' on string '{\"-reg-example-com\":\"\"}'".

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (C:\Users\bhavvai\Downloads\electron-react-boilerplate-2.3.0\electron-react-boilerplate-2.3.0\.erb\configs\/webpack.config.renderer.dev.babel.js:34:3)
    at Module._compile (C:\Users\bhavvai\Downloads\electron-react-boilerplate-2.3.0\electron-react-boilerplate-2.3.0\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._compile (C:\Users\bhavvai\Downloads\electron-react-boilerplate-2.3.0\electron-react-boilerplate-2.3.0\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.newLoader [as .js] (C:\Users\bhavvai\Downloads\electron-react-boilerplate-2.3.0\electron-react-boilerplate-2.3.0\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
(node:44464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not ha
ndled with .catch(). (rejection id: 2)
(node:44464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 5.36s.

```
## Steps to Reproduce

- git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
- cd your-project-name
- yarn

## Your Environment

- Node version :v12.14.1
- electron-react-boilerplate version or branch :master/2.3.0
- Operating System and version : Windows 10 latest
- Link to your project :

**Comment by railsjack** [comment]
I have the same problem.
For your information, you need to pay attention to this.
```
The DLL files are missing. Sit back while we build them for you with "yarn build-dll"
error An unexpected error occurred: "Cannot create property '-reg-example-com' on string '{\"-reg-example-com\":\"\"}'".
(node:44464) UnhandledPromiseRejectionWarning: Error: Command failed: yarn build-dll
error An unexpected error occurred: "Cannot create property '-reg-example-com' on string '{\"-reg-example-com\":\"\"}'".
```
A script "build-dll" is gone in the last version of package.json.
I am not sure if it's correct or not. Can you please check it?
![image](https://user-images.githubusercontent.com/1916657/112351516-eff30980-8d04-11eb-8558-75b282fc83da.png)
