### ISSUE TITLE
Failure to yarn add active-win package

### ISSUE THREAD

**Issue by andrewschreiber** [electron-react-boilerplate/electron-react-boilerplate#2814]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Expected behavior is that the active-win package should successfully install via `yarn add` in a base electron-react-boilerplate project.

Active-win (https://github.com/sindresorhus/active-win) is a package for getting the currently active window on your computer. 

The package works properly if used with https://www.electronjs.org/docs/tutorial/quick-start.
![image](https://user-images.githubusercontent.com/1892071/112687753-2fb90e80-8e35-11eb-8789-9db481464575.png)

## Current Behavior

If attempting to install in the top-level package.json, I get a native dependency error. No problem.
```
...
success Saved 9 new dependencies.
info Direct dependencies
└─ active-win@6.3.0
info All dependencies
├─ active-win@6.3.0
├─ ffi-napi@2.5.0
├─ get-symbol-from-current-process-h@1.0.2
├─ get-uv-event-loop-napi-h@1.0.6
├─ iconv@2.3.5
├─ ref-napi@1.5.2
├─ ref-struct-di@1.1.1
├─ ref-struct-napi@1.1.1
└─ ref-wchar-napi@1.0.3
node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock

 Webpack does not work with native dependencies.
active-win is a native dependency and should be installed inside of the "./app" folder.
 First, uninstall the packages from "./package.json":
yarn remove your-package
 Then, instead of installing the package to the root "./package.json":
yarn add your-package
 Install the package to "./src/package.json"
cd ./app && yarn add your-package
 Read more about native dependencies at:
https://electron-react-boilerplate.js.org/docs/adding-dependencies/#module-structure

error Command failed with exit code 1.
```

Then if attempting to install in `src/package.json` this issue appears:

Interestingly `active-win` can then be imported and used in development. However yarn becomes corrupt and no longer able to install new packages or even run `yarn`. A production build created via `yarn package` will also build, but crash immediately.

```
~/git/electron-react-boilerplate/src(master ✔) yarn add active-win
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 12 new dependencies.
info Direct dependencies
└─ active-win@6.3.0
info All dependencies
├─ active-win@6.3.0
├─ ffi-napi@2.5.0
├─ get-symbol-from-current-process-h@1.0.2
├─ get-uv-event-loop-napi-h@1.0.6
├─ iconv@2.3.5
├─ ms@2.1.3
├─ nan@2.14.2
├─ ref-napi@1.5.2
├─ ref-struct-di@1.1.1
├─ ref-struct-napi@1.1.1
├─ ref-wchar-napi@1.0.3
└─ safer-buffer@2.1.2
$ yarn electron-rebuild
yarn run v1.22.10
$ node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js
⠸ Building modules: 0/5gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
⠼ Building modules: 0/5gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
⠹ Building modules: 0/5gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
⠸ Building modules: 0/5gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
⠧ Building modules: 0/5gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
⠼ Building modules: 0/5gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
⠴ Building modules: 0/5gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠇ Building modules: 0/5gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
⠏ Building modules: 0/5  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
⠙ Building modules: 0/5rm: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
make: *** [Release/obj.target/nothing/../../../node-addon-api/src/nothing.o] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-napi'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/andrewschreiber/git/electron-react-boilerplate/src/node_modules/ref-napi'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/electron-rebuild/lib/src/rebuild.js:183:9)
    at async Promise.all (index 14)
    at async Rebuilder.rebuild (/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/electron-rebuild/lib/src/rebuild.js:141:13)
    at async /Users/andrewschreiber/git/electron-react-boilerplate/node_modules/electron-rebuild/lib/src/cli.js:145:9
sed: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
child_process.js:655
    throw err;
    ^

Error: Command failed: ../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (/Users/andrewschreiber/git/electron-react-boilerplate/.erb/scripts/ElectronRebuild.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/andrewschreiber/git/electron-react-boilerplate/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 86813,
  stdout: null,
  stderr: null
}
  LIBTOOL-STATIC Release/nothing.a
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
sed: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
make: *** [Release/obj.target/nothing/../../../node-addon-api/src/nothing.o] Error 1
rm: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
make: *** [Release/obj.target/nothing/../../../node-addon-api/src/nothing.o] Error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
  LIBTOOL-STATIC Release/nothing.a
~/git/electron-react-boilerplate/src(master ✗) warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/binding/src/binding.o
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:305:13: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
    *rptr = std::move(Reference<Object>::New(val));
            ^
../src/binding.cc:305:13: note: remove std::move call here
    *rptr = std::move(Reference<Object>::New(val));
            ^~~~~~~~~~                           ~
../src/binding.cc:305:13: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
    *rptr = std::move(Reference<Object>::New(val));
            ^
../src/binding.cc:305:13: note: remove std::move call here
    *rptr = std::move(Reference<Object>::New(val));
            ^~~~~~~~~~                           ~
1 warning generated.
  SOLINK_MODULE(target) Release/binding.node
1 warning generated.
  SOLINK_MODULE(target) Release/binding.node
```
See https://github.com/sindresorhus/active-win/issues/102 for more discussion

## Steps to Reproduce

1. With a clone of ERB, `cd src && yarn add active-win`

## Context

I am trying to use this package for a quantified self app.

## Your Environment

- Node version : v14.10.1 but also tested on v12.18.3
- electron-react-boilerplate version or branch : Master, today
- Operating System and version : MacOS Catalina 10.15.7, but also tested on BigSur 11.2.2

Thanks for your help! Truly appreciate the boilerplate your team has created.

**Comment by wkddnjset** [comment]
try 

```
$ rm -rf node_modules
$ npm cache clean --force
$ npm install active-win
```

In my case, the package install was successful.
node : 12.22.1
npm : 7.13
yarn : 1.21.1

```
$ npm install active-win                                                                                                                     

added 23 packages, and audited 24 packages in 11s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

However, the following error occurs when packing.

![image](https://user-images.githubusercontent.com/22087542/118794983-14b6c800-b8d5-11eb-9cca-2d26f4d04f78.png)

**Comment by lmick002** [comment]
@andrewschreiber did you figure out how to fixed this? Seems to be related to the post-install electron rebuild script. @amilajack anything thoughts?  Thanks!
