### ISSUE TITLE
Cannot build native dependency (webtorrent)

### ISSUE THREAD

**Issue by Crauzer** [electron-react-boilerplate/electron-react-boilerplate#2897]
## Expected Behavior

Dependency should have been installed

## Current Behavior

Native dependency fails to build because of unknown error

## Steps to Reproduce

```
yarn install v1.22.10
warning ..\..\package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused 
by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild
yarn run v1.22.10
warning ..\..\package.json: No license field
$ node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js
- Building modules: 0/3gyp info find Python using Python version 3.8.6 found at "C:\Python38\python.exe"
\ Building modules: 0/3gyp info find Python using Python version 3.8.6 found at "C:\Python38\python.exe"
gyp info find Python using Python version 3.8.6 found at "C:\Python38\python.exe"
- Building modules: 0/3gyp info find VS using VS2019 (16.9.31205.134) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
(node:4580) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn C:\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\11.0.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\dev\\barracuda\\src\\node_modules\\utp-native\\11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\dev\\\\barracuda\\\\src\\\\node_modules\\\\utp-native\\\\11.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\dev\\barracuda\\src\\node_modules\\utp-native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
\ Building modules: 0/3gyp info find VS using VS2019 (16.9.31205.134) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\11.0.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\dev\\barracuda\\src\\node_modules\\utp-native\\11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\dev\\\\barracuda\\\\src\\\\node_modules\\\\utp-native\\\\11.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\dev\\barracuda\\src\\node_modules\\utp-native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info find VS using VS2019 (16.9.31205.134) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\11.0.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\dev\\barracuda\\src\\node_modules\\utp-native\\11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\dev\\barracuda\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\dev\\\\barracuda\\\\src\\\\node_modules\\\\utp-native\\\\11.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\dev\\barracuda\\src\\node_modules\\utp-native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\dev\\barracuda\\src\\node_modules\\utp-native\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
| Building modules: 0/3gyp: C:\dev\barracuda\src\node_modules\utp-native\11.0.1\common.gypi not found (cwd: C:\dev\barracuda\src\node_modules\utp-native) while reading includes of binding.gyp while trying to load binding.gyp
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\dev\barracuda\src\node_modules\bufferutil'.
Error: `gyp` failed with exit code: 1



Error: node-gyp failed to rebuild 'C:\dev\barracuda\src\node_modules\bufferutil'.
Error: `gyp` failed with exit code: 1


    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Rebuilder.rebuildModuleAt (C:\dev\barracuda\node_modules\electron-rebuild\lib\src\rebuild.js:183:9)
    at async Promise.all (index 43)
    at async Rebuilder.rebuild (C:\dev\barracuda\node_modules\electron-rebuild\lib\src\rebuild.js:141:13)
    at async C:\dev\barracuda\node_modules\electron-rebuild\lib\src\cli.js:145:9
node:child_process:747
    throw err;
    ^

Error: Command failed: ..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (node:child_process:707:11)
    at execSync (node:child_process:744:15)
    at Object.<anonymous> (C:\dev\barracuda\.erb\scripts\/ElectronRebuild.js:18:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Module._compile (C:\dev\barracuda\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.newLoader [as .js] (C:\dev\barracuda\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  status: 4294967295,
  signal: null,
  pid: 12428,
  stdout: null,
  stderr: null
}
```

## Your Environment

- Node version : 16.3
- electron-react-boilerplate version or branch : Latest
- Operating System and version : Windows 10

**Comment by amilajack** [comment]
Does this fail in v3?
