### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by bluebitle** [electron-react-boilerplate/electron-react-boilerplate#2924]
when I build and start, that doesn't work clearly. 

how to use it, if i use import another electron's SDK to use require('./solution)(true);

App threw an error during load
Error: Cannot find module 'electron'

- main.dev.js 
import { app, BrowserWindow } from 'electron';

const { autoUpdater } = require('electron-updater');
const log = require('electron-log');
const path = require('path');
require('../solution')(true);

-- yarn start 

App threw an error during load
Error: Cannot find module 'electron'
    at r (C:\Users\user\IdeaProjects\erb-second-renderer-window-example\app\main.prod.js:1:1753)
    at e.<computed> (C:\Users\user\IdeaProjects\erb-second-renderer-window-example\app\main.prod.js:1:4023)
    at Module../app/main.dev.js (C:\Users\user\IdeaProjects\erb-second-renderer-window-example\app\main.prod.js:1:1163)
    at r (C:\Users\user\IdeaProjects\erb-second-renderer-window-example\app\main.prod.js:1:124)

If it doesn't declare " request('../solution'), it will run normally.

Please let me know how to require

**Comment by f-o-w-l** [comment]
Are you sure you ran the command `yarn` to install dependencies before `yarn build` or `yarn start`?
