### ISSUE TITLE
GitHub workflow failed, Cannot find module '.../.erb/scripts/notarize.js'

### ISSUE THREAD

**Issue by shensven** [electron-react-boilerplate/electron-react-boilerplate#2952]
## Summary

When I upgrade to version 3.0.2,the workflow always fails to compile, I always got this error: 
```sh
[1] webpack 5.38.1 compiled with 3 warnings in 15475 ms
[1] yarn build:renderer exited with code 0
  • electron-builder  version=22.11.5 os=5.8.0-1039-azure
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=linux arch=x64 electron=13.1.8 appOutDir=build/release/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v13.1.8/electron-v13.1.8-linux-x64.zip size=78 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v13.1.8/electron-v13.1.8-linux-x64.zip duration=282ms
  ⨯ Cannot find module '/home/runner/work/winstagram_98/winstagram_98/.erb/scripts/notarize.js'
Require stack:
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/platformPackager.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/electron/ElectronFramework.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/packager.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/index.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/electron-builder/out/builder.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/electron-builder/out/cli/cli.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module '/home/runner/work/winstagram_98/winstagram_98/.erb/scripts/notarize.js'
Require stack:
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/platformPackager.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/electron/ElectronFramework.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/packager.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/out/index.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/electron-builder/out/builder.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/electron-builder/out/cli/cli.js
- /home/runner/work/winstagram_98/winstagram_98/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at resolveFunction (/home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/src/platformPackager.ts:752:13)
    at LinuxPackager.doSignAfterPack (/home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/src/platformPackager.ts:316:23)
    at LinuxPackager.doPack (/home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/src/platformPackager.ts:300:7)
    at LinuxPackager.pack (/home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/runner/work/winstagram_98/winstagram_98/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/runner/work/winstagram_98/winstagram_98/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/runner/work/winstagram_98/winstagram_98/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
More details in the link below
https://github.com/shensven/winstagram_98/runs/3396639709?check_suite_focus=true#step:5:72

What should I do to solve this problem, thank you

**Comment by amilajack** [comment]
Case sensitive https://github.com/shensven/winstagram_98/blob/main/.erb/scripts/Notarize.js
