### ISSUE TITLE
better-sqlite3 is compiled against a different nodejs version

### ISSUE THREAD

**Issue by IzaacJ** [electron-react-boilerplate/electron-react-boilerplate#3011]
## Prerequisites

- [x] Using ~~npm~~ yarn
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Been able to run app w/o error

## Current Behavior

Error message about better-sqlite3 being compiled against a different NodeJS version. This error happens both in dev mode and in the packaged app. This only happens during actual runtime.
Complete error:
```
> electron-react-boilerplate@ start:main C:\Users\izaac\Sources\better-sqlite3-test
> cross-env NODE_ENV=development electron -r ts-node/register/transpile-only ./src/main/main.ts

App threw an error during load
Error: The module '\\?\C:\Users\izaac\Sources\better-sqlite3-test\release\app\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 89. This version of Node.js requires
NODE_MODULE_VERSION 98. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at bindings (C:\Users\izaac\Sources\better-sqlite3-test\release\app\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\izaac\Sources\better-sqlite3-test\release\app\node_modules\better-sqlite3\lib\database.js:9:24)
```

## Steps to Reproduce

1. Clone repo, install modules, add `better-sqlite3` in `release/app/package.json`, add typings
```sh
git clone --depth=1 https://github.com/electron-react-boilerplate/electron-react-boilerplate.git better-sqlite3-test
cd better-sqlite3-test
yarn
cd ./release/app
yarn add better-sqlite3
cd ../..
yarn add -D @types/better-sqlite3
```

2. Import `better-sqlite3` in `main.ts` and use it in some way
```ts
// main.ts
import BSQLite3 from 'better-sqlite3';

const db = new BSQLite3(':memory:');
db.close();
```

3. Try to run dev mode - `yarn start`

## Your Environment

- Node version : 14.18.1 (`choco install nodejs-lts` on Windows, through [nvm-sh/nvm](https://github.com/nvm-sh/nvm): `nvm install --lts` on Debian 11)
- electron-react-boilerplate version or branch : freshly cloned `main` branch
- Operating System and version : Windows 11 Pro (build 22000.258) & Debian 11 (kernel 5.10.70-1)
- Link to your project : N/A

**Comment by TechGrizzlee** [comment]
I am able to build it properly, but in the Electron dev tool, I am getting the following exception. 
`index.js:11 Uncaught ReferenceError: Database is not defined
    at ./src/renderer/database/index.js (index.js:11)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at ./src/renderer/dao/index.js (index.js:2)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at ./src/renderer/App.tsx (App.tsx:2)
    at Object.options.factory (react refresh:6)`

I tried multiple ways to import, but it throws the same ERROR. Could you please help!
`require('better-sqlite3')` is getting undefined always

`const Database = require('better-sqlite3');
const sqliteDb = new Database('foobar.db', { verbose: console.log });
export default sqliteDb;
`

`import { Database } from '@types/better-sqlite3';
const sqliteDb = new Database('foobar.db', { verbose: console.log });
export default sqliteDb;`

**Comment by TechGrizzlee** [comment]
What am I missing [here](https://github.com/JoshuaWise/better-sqlite3/issues/126#issuecomment-966355900)? Can someone help, please! TYA

**Comment by amilajack** [comment]
This should work out of the box with the boilerplate. See this working example: https://github.com/amilajack/erb-better-sqlite3-example
