### ISSUE TITLE
Unable to push code to gitlab using sourcetreee

### ISSUE THREAD

**Issue by rdkashmir** [electron-react-boilerplate/electron-react-boilerplate#3095]
Hi I downloaded the latest bootstrap and added some changes and new form. Also Run:
1. Npm install
2. npm run start ( app is working)

but when I tried to push the code to gitlab using sourcetree, it is giving given below message:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks commit -q -F C:\Users\zzz\AppData\Local\Temp\is30jqmd.gyp
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.{js,jsx,ts,tsx}
[STARTED] Running tasks for *.json,.{eslintrc,prettierrc}
[STARTED] Running tasks for *.{css,scss}
[STARTED] Running tasks for *.{html,md,yml}
[SKIPPED] No staged files match *.json,.{eslintrc,prettierrc}
[STARTED] cross-env NODE_ENV=development eslint --cache
[STARTED] prettier --ignore-path .eslintignore --single-quote --write
[STARTED] prettier --ignore-path .eslintignore --single-quote --write








[SUCCESS] prettier --ignore-path .eslintignore --single-quote --write
[SUCCESS] Running tasks for *.{css,scss}
[SUCCESS] prettier --ignore-path .eslintignore --single-quote --write
[SUCCESS] Running tasks for *.{html,md,yml}
[FAILED] [91mcross-env NODE_ENV=development eslint --cache[39m [2m[FAILED][22m
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...



[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up...

[SUCCESS] Cleaning up...

[91m[91m×[91m cross-env NODE_ENV=development eslint --cache:[39m

Oops! Something went wrong! :(

ESLint: 8.6.0

TSError: ⨯ Unable to compile TypeScript:
.erb/configs/webpack.config.base.ts(8,10): error TS2305: Module '"C:/xxxx/yy//release/app/package"' has no exported member 'dependencies'.

Occurred while linting C:\xxxx\yy\src\components\layout\header.tsx:1
Rule: "import/no-cycle"
    at createTSError (C:\xxxx\yy\node_modules\ts-node\src\index.ts:750:12)
    at reportTSError (C:\xxxx\yy\node_modules\ts-node\src\index.ts:754:19)
    at getOutput (C:\xxxx\yy\node_modules\ts-node\src\index.ts:941:36)
    at Object.compile (C:\xxxx\yy\node_modules\ts-node\src\index.ts:1243:30)
    at Module.m._compile (C:\xxxx\yy\node_modules\ts-node\src\index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\xxxx\yy\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
Error resolving webpackConfig .erb/configs/webpack.config.base.ts(8,10): error TS2305: Module C:/xxxx/yy//release/app/package"' has no exported member 'dependencies
```

husky - pre-commit hook exited with code 1 (error)
Completed with errors, see above.
`

my package.json file is 
````
{
  "name": "electron-react-boilerplate",
  "description": "Electron application boilerplate based on React, React Router, Webpack, React Fast Refresh for rapid application development",
  "scripts": {
    "build": "concurrently \"npm run build:main\" \"npm run build:renderer\"",
    "build:main": "cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.main.prod.ts",
    "build:renderer": "cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.prod.ts",
    "rebuild": "electron-rebuild --parallel --types prod,dev,optional --module-dir release/app",
    "lint": "cross-env NODE_ENV=development eslint . --ext .js,.jsx,.ts,.tsx",
    "package": "ts-node ./.erb/scripts/clean.js dist && npm run build && electron-builder build --publish never",
    "postinstall": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts && opencollective-postinstall",
    "start": "ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer",
    "start:main": "cross-env NODE_ENV=development electron -r ts-node/register/transpile-only ./src/main/main.ts",
    "start:renderer": "cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts",
    "test": "jest",
    "prepare": "husky install"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "cross-env NODE_ENV=development eslint --cache"
    ],
    "*.json,.{eslintrc,prettierrc}": [
      "prettier --ignore-path .eslintignore --parser json --write"
    ],
    "*.{css,scss}": [
      "prettier --ignore-path .eslintignore --single-quote --write"
    ],
    "*.{html,md,yml}": [
      "prettier --ignore-path .eslintignore --single-quote --write"
    ]
  },
  "build": {
    "productName": "ElectronReact",
    "appId": "org.erb.ElectronReact",
    "asar": true,
    "asarUnpack": "**\\*.{node,dll}",
    "files": [
      "dist",
      "node_modules",
      "package.json"
    ],
    "afterSign": ".erb/scripts/notarize.js",
    "mac": {
      "target": {
        "target": "default",
        "arch": [
          "arm64",
          "x64"
        ]
      },
      "type": "distribution",
      "hardenedRuntime": true,
      "entitlements": "assets/entitlements.mac.plist",
      "entitlementsInherit": "assets/entitlements.mac.plist",
      "gatekeeperAssess": false
    },
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": [
        "nsis"
      ]
    },
    "linux": {
      "target": [
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "app": "release/app",
      "buildResources": "assets",
      "output": "release/build"
    },
    "extraResources": [
      "./assets/**"
    ],
    "publish": {
      "provider": "github",
      "owner": "electron-react-boilerplate",
      "repo": "electron-react-boilerplate"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron-react-boilerplate/electron-react-boilerplate.git"
  },
  "author": {
    "name": "Electron React Boilerplate Maintainers",
    "email": "electronreactboilerplate@gmail.com",
    "url": "https://electron-react-boilerplate.js.org"
  },
  "contributors": [
    {
      "name": "Amila Welihinda",
      "email": "amilajack@gmail.com",
      "url": "https://github.com/amilajack"
    },
    {
      "name": "John Tran",
      "email": "jptran318@gmail.com",
      "url": "https://github.com/jooohhn"
    }
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues"
  },
  "keywords": [
    "electron",
    "boilerplate",
    "react",
    "typescript",
    "ts",
    "sass",
    "webpack",
    "hot",
    "reload"
  ],
  "homepage": "https://github.com/electron-react-boilerplate/electron-react-boilerplate#readme",
  "jest": {
    "testURL": "http://localhost/",
    "testEnvironment": "jsdom",
    "transform": {
      "\\.(ts|tsx|js|jsx)$": "ts-jest"
    },
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/.erb/mocks/fileMock.js",
      "\\.(css|less|sass|scss)$": "identity-obj-proxy"
    },
    "moduleFileExtensions": [
      "js",
      "jsx",
      "ts",
      "tsx",
      "json"
    ],
    "moduleDirectories": [
      "node_modules",
      "release/app/node_modules"
    ],
    "testPathIgnorePatterns": [
      "release/app/dist"
    ],
    "setupFiles": [
      "./.erb/scripts/check-build-exists.ts"
    ]
  },
  "devDependencies": {
    "@pmmmwh/react-refresh-webpack-plugin": "0.5.4",
    "@teamsupercell/typings-for-css-modules-loader": "^2.5.1",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@types/jest": "^27.0.3",
    "@types/node": "17.0.5",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "@types/react-test-renderer": "^17.0.1",
    "@types/terser-webpack-plugin": "^5.0.4",
    "@types/webpack-env": "^1.16.3",
    "@typescript-eslint/eslint-plugin": "^5.8.1",
    "@typescript-eslint/parser": "^5.8.1",
    "browserslist-config-erb": "^0.0.3",
    "chalk": "^4.1.2",
    "concurrently": "^6.5.1",
    "core-js": "^3.20.1",
    "cross-env": "^7.0.3",
    "css-loader": "^6.5.1",
    "css-minimizer-webpack-plugin": "^3.3.1",
    "detect-port": "^1.3.0",
    "electron": "^16.0.5",
    "electron-builder": "^22.14.5",
    "electron-devtools-installer": "^3.2.0",
    "electron-notarize": "^1.1.1",
    "electron-rebuild": "^3.2.5",
    "eslint": "^8.5.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-erb": "^4.0.3",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-import-resolver-webpack": "^0.13.2",
    "eslint-plugin-compat": "^4.0.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jest": "^25.3.2",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.5.0",
    "husky": "^7.0.4",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.4.5",
    "lint-staged": "^12.1.4",
    "mini-css-extract-plugin": "^2.4.5",
    "opencollective-postinstall": "^2.0.3",
    "prettier": "^2.5.1",
    "react-refresh": "^0.11.0",
    "react-refresh-typescript": "^2.0.3",
    "react-test-renderer": "^17.0.2",
    "rimraf": "^3.0.2",
    "sass": "^1.45.1",
    "sass-loader": "^12.4.0",
    "style-loader": "^3.3.1",
    "terser-webpack-plugin": "^5.3.0",
    "ts-jest": "^27.1.2",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.4",
    "url-loader": "^4.1.1",
    "webpack": "^5.65.0",
    "webpack-bundle-analyzer": "^4.5.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.7.1",
    "webpack-merge": "^5.8.0"
  },
  "dependencies": {
    "axios": "^0.24.0",
    "bootstrap": "^5.1.3",
    "electron-debug": "^3.2.0",
    "electron-log": "^4.4.4",
    "electron-updater": "^4.6.4",
    "history": "^5.2.0",
    "qs": "^6.10.2",
    "rc-tabs": "^11.10.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-folder-tree": "^5.0.3",
    "react-router-dom": "^6.2.1",
    "regenerator-runtime": "^0.13.9",
    "styled-components": "^5.3.3"
  },
  "devEngines": {
    "node": ">=14.x",
    "npm": ">=7.x"
  },
  "collective": {
    "url": "https://opencollective.com/electron-react-boilerplate-594"
  },
  "browserslist": [],
  "prettier": {
    "overrides": [
      {
        "files": [
          ".prettierrc",
          ".eslintrc"
        ],
        "options": {
          "parser": "json"
        }
      }
    ],
    "singleQuote": true
  }
}
```

**Comment by rdkashmir** [comment]
I am still facing the issue. Could you please help on this?

**Comment by amilajack** [comment]
Few options:
1. remove the pre-commit script
2. fix the errors mentioned above
