### ISSUE TITLE
Using the Chromium Bluetooth API (Currently Crashing)

### ISSUE THREAD

**Issue by andrewrt** [electron-react-boilerplate/electron-react-boilerplate#3119]
## Summary

Trying to use the chromium bluetooth API as per: https://web.dev/bluetooth/

Looks like it should be relatively simple 
### Main
add the following to **main.ts**:
```js
app.commandLine.appendSwitch("enable-web-bluetooth", true);
app.commandLine.appendSwitch('enable-experimental-web-platform-features');
```

and after `mainWindow = new BrowserWindow`, add the following:
```js
 mainWindow.webContents.on('select-bluetooth-device', (event, deviceList, callback) => {
    event.preventDefault()
    const result = deviceList.find((device) => {
      return device.deviceName === 'test'
    })
    console.log('select-bluetooth-device : ', deviceList);
    if (!result) {
      callback('')
    } else {
      callback(result.deviceId)
    }
  })
```

### Renderer
add an onClick handler in renderer: 
```js
  const showBleDevices = (event) => {
    const bleOptions = { acceptAllDevices: true };
    navigator.bluetooth.requestDevice(bleOptions).then((devs) => {
      console.log('BLE Devices: ', (devs));
    }).catch(error => {
    console.log('BLE req device failed: ', error);
    });
  }
```

(called in renderer.tsx via 
```jsx
        <button  type='button' onClick={showBleDevices}>Discover Devices</button>
```

### Error output
I either get a complete crash (w/ no useful log info) or I get the following error on the renderer's console:
error: DOMException: Failed to execute 'requestDevice' on 'Bluetooth': Must be handling a user gesture to show a permission request. 
at showBleDevices (http://localhost:1212/renderer.dev.js:72980:29) 
at HTMLUnknownElement.callCallback (http://localhost:1212/renderer.dev.js:36640:14) 
at Object.invokeGuardedCallbackDev (http://localhost:1212/renderer.dev.js:36689:16) 
at invokeGuardedCallback (http://localhost:1212/renderer.dev.js:36751:31) 
at invokeGuardedCallbackAndCatchFirstError (http://localhost:1212/renderer.dev.js:36765:25) 
at executeDispatch (http://localhost:1212/renderer.dev.js:40938:3) 
at processDispatchQueueItemsInOrder (http://localhost:1212/renderer.dev.js:40970:7) 
at processDispatchQueue (http://localhost:1212/renderer.dev.js:40983:5) 
at dispatchEventsForPlugins (http://localhost:1212/renderer.dev.js:40994:3) 
at http://localhost:1212/renderer.dev.js:41203:12

**Comment by andrewrt** [comment]
minor note for sanity: the renderer side code - if run from create-react-app  in a webapp (chrome) - works w/o crashing.
