### ISSUE TITLE
How to package a forked child process

### ISSUE THREAD

**Issue by megancooper** [electron-react-boilerplate/electron-react-boilerplate#3142]
I am working on an app that uses a forked "server" process to manage and persist state. Right now I fork this process when the electron app starts from `main.dev.ts` like so:

```
const createServerProcess = async (socketName: string) => {
  const serverPath = app.isPackaged
    ? `${__dirname}/dist/server.prod.js`
    : path.join(__dirname, './server/index.js');

  serverProcess = fork(serverPath, [
    '--subprocess',
    app.getVersion(),
    socketName,
    app.getPath('userData'),
  ]);
};
```

Everything works great when I run my application locally. For some reason however, I can't get the packaged app to work. My renderer process and main process startup great, but something is causing the forked process to fail. I think the issue is that the forked process can't access any of the `node_modules`.

When the app is packaged, I used a simple webpack config to bundle the server and store `server.prod.js` inside the generated `dist` file (this is also where `renderer.prod.js` is stored):

(The forked process, i.e. "server", uses knex and sqlite3)

```
import path from 'path';
import webpack from 'webpack';
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';
import { merge } from 'webpack-merge';
import TerserPlugin from 'terser-webpack-plugin';
import baseConfig from './webpack.config.base';
import CheckNodeEnv from '../scripts/CheckNodeEnv';
import DeleteSourceMaps from '../scripts/DeleteSourceMaps';

CheckNodeEnv('production');
DeleteSourceMaps();

const devtoolsConfig = process.env.DEBUG_PROD === 'true' ? {
  devtool: 'source-map'
} : {};

export default merge(baseConfig, {
  ...devtoolsConfig,

  mode: 'production',

  target: 'node',

  entry: path.join(__dirname, '../../src/server/index.js'),
  
  [
    'core-js',
    'regenerator-runtime/runtime',
    path.join(__dirname, '../../src/server/index.js'),
  ],

  output: {
    path: path.join(__dirname, '../../src/dist'),
    publicPath: './dist/',
    filename: 'server.prod.js',
  },

  externals: {
    // Possible drivers for knex - we'll ignore them
    sqlite3: 'sqlite3',
    mysql2: 'mysql2',
    mariasql: 'mariasql',
    mysql: 'mysql',
    oracle: 'oracle',
    'strong-oracle': 'strong-oracle',
    oracledb: 'oracledb',
    pg: 'pg',
    'pg-query-stream': 'pg-query-stream',
    'better-sqlite3': 'better-sqlite3',
    'tedious': 'tedious',
  },

  optimization: {
    minimize: true,
    minimizer:
      [
        new TerserPlugin({
          parallel: true,
        }),
      ],
  },

  plugins: [
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      DEBUG_PROD: false,
    }),

    new BundleAnalyzerPlugin({
      analyzerMode:
        process.env.OPEN_ANALYZER === 'true' ? 'server' : 'disabled',
      openAnalyzer: process.env.OPEN_ANALYZER === 'true',
    }),
  ],
});
```

Am I doing this incorrectly? I'm unsure how to get this bundled so that once the process is forked it has access to all the node modules `knex`, `@vscode/sqlite`, etc that it needs.

After bundling the file structure is:

```
dist/
  server.prod.js
  renderer.prod.js
main.prod.js
...
```

And the forked process exits with the following error:
```
From main process:  Knex: run
$ npm install sqlite3 --save
dlopen(/Users/megan/.../node_modules/@vscode/sqlite3/build/Release/vscode-sqlite3.node, 1): no suitable image found.  Did find:
	/Users/megan/.../node_modules/@vscode/sqlite3/build/Release/vscode-sqlite3.node: code signature in (/Users/megan/.../node_modules/@vscode/sqlite3/build/Release/vscode-sqlite3.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
Error: dlopen(/Users/megan/.../node_modules/@vscode/sqlite3/build/Release/vscode-sqlite3.node, 1): no suitable image found.  Did find:
	/Users/megan/.../node_modules/@vscode/sqlite3/build/Release/vscode-sqlite3.node: code signature in (/Users/megan/.../@vscode/sqlite3/build/Release/vscode-sqlite3.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/megan/.../node_modules/@vscode/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

Thanks for any help.

**Comment by kbrisso** [comment]
Had the same issue with PouchDB. In order for me to run the application with PouchDB in dev mode, I have to install it in the normal package file <project roo>/package.json and then here <project root>/release/app/package.json. When I **compile**  app, I remove the package from the main package file and leave the release one. 
Let me know if it works. 

Package info on doc site.
https://electron-react-boilerplate.js.org/docs/adding-dependencies

**Comment by amilajack** [comment]
@megancooper this might be relevant
https://github.com/electron/electron/issues/2708
Lmk if this helps. If not I can dive deeper

**Comment by amilajack** [comment]
@megancooper I've put together a working example based on [erb-sqlite-example](https://github.com/amilajack/erb-sqlite-example):
https://github.com/amilajack/erb-fork-example
This example uses sqlite in a forked process inside the main process. Works in dev and packaged app.

**Comment by chrislone** [comment]
Can't open https://github.com/amilajack/erb-fork-example, is that have been removed?

**Comment by chrislone** [comment]
@amilajack Hi, amila, https://github.com/amilajack/erb-fork-example returns a 404 page, is that has been removed?

**Comment by MrSharpp** [comment]
> @amilajack Hi, amila, https://github.com/amilajack/erb-fork-example returns a 404 page, is that has been removed?

same
