### ISSUE TITLE
ERR_INVALID_ARG_TYPE: The "from" argument must be of type string.

### ISSUE THREAD

**Issue by astralmedia** [electron-react-boilerplate/electron-react-boilerplate#3173]
## Summary

I have a massive electron app that was built on an old version of the boilerplate (I know, I know). The codebase worked fine last time I used it, but on my newly built machine (and thus maybe newer version of node?) I keep getting this ERR_INVALID_ARG_TYPE error: `The "from" argument must be of type string. Received undefined` right at the end of `npm i` completing.

I am going to rebuild the app properly using the modern stack, but I have to get an update out in the short term.

Thanks for any insight.

Full error:

```
2698 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
2698 verbose stack     at new NodeError (node:internal/errors:371:5)
2698 verbose stack     at validateString (node:internal/validators:120:11)
2698 verbose stack     at relative (node:path:497:5)
2698 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1069:21
2698 verbose stack     at Array.map (<anonymous>)
2698 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1067:66
2698 verbose stack     at Array.map (<anonymous>)
2698 verbose stack     at Arborist.[rollbackMoveBackRetiredUnchanged] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1067:8)
2698 verbose stack     at Arborist.[reifyPackages] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:231:31)
2698 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:151:5)
2699 verbose cwd D:\CHROMA\CHROMA-Hub
2700 verbose Windows_NT 10.0.19042
2701 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
2702 verbose node v16.14.0
2703 verbose npm  v8.3.1
```

**Comment by amilajack** [comment]
seems like an issue unrelated to the boilerplate. it seems like you're passing `undefined` to `path.relative`
