### ISSUE TITLE
Darwin DMG Packaging Error

### ISSUE THREAD

**Issue by MangoSwirl** [electron-react-boilerplate/electron-react-boilerplate#3195]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [n/a] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

`npm run package` packages to a disk image successfully with no errors.

## Current Behavior

After the second `building embedded block map` step, a compound error occurs, and a Python traceback is printed.

The `node_modules/dmg-builder/vendor/dmgbuild/core.py` script fails because the `background.tff` file isn't in the working disk image. (The image is unmounted at this step)

## Steps to Reproduce

The `npm run package` command worked perfectly for me before, and I'm not sure what changed that caused it to fail.

<details>
<summary>Printed error:</summary>

```
Skipping notarizing step. Packaging is not running in CI
  • building        target=macOS zip arch=x64 file=release/build/HillCraft Admin Dashboard-4.5.0-mac.zip
  • building        target=DMG arch=x64 file=release/build/HillCraft Admin Dashboard-4.5.0.dmg
  • building block map  blockMapFile=release/build/HillCraft Admin Dashboard-4.5.0.dmg.blockmap
  • building embedded block map  file=release/build/HillCraft Admin Dashboard-4.5.0-mac.zip
  • building embedded block map  file=release/build/HillCraft Admin Dashboard-4.5.0-mac.zip
  ⨯ Compound error: 

Error #1 --------------------------------------------------------------------------------
Error: Exit code: 1. Command failed: /usr/bin/python /Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 282, in \<module\>
    build_dmg()
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 249, in build_dmg
    alias = Alias.for_file(background_file)
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 347, in for_file
    st = osx.statfs(path)
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/mac_alias/osx.py", line 816, in statfs
    raise OSError(err, os.strerror(err), path)
OSError: [Errno 2] No such file or directory: '/Volumes/HillCraft Admin Dashboard 4.5.0/.background/background.tiff'

Traceback (most recent call last):
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 282, in <module>
    build_dmg()
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 249, in build_dmg
    alias = Alias.for_file(background_file)
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 347, in for_file
    st = osx.statfs(path)
  File "/Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/dmg-builder/vendor/mac_alias/osx.py", line 816, in statfs
    raise OSError(err, os.strerror(err), path)
OSError: [Errno 2] No such file or directory: '/Volumes/HillCraft Admin Dashboard 4.5.0/.background/background.tiff'

    at /Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/builder-util/src/util.ts:129:16
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

Error #2 --------------------------------------------------------------------------------
Error: Exit code: 1. Command failed: hdiutil detach -force /dev/disk3
hdiutil: detach failed - No such file or directory

hdiutil: detach failed - No such file or directory

    at /Users/MangoSwirl/Documents/HillCraft/admin-dashboard/node_modules/builder-util/src/util.ts:129:16
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)  stackTrace=
```
(Truncated, the original stack trace continues with excessive unnecessary line breaks and illogical indents)
</details>

## Possible Solution (Not obligatory)

Working disk image may be unmounted/ejected too early.
## Context

Changes to the boilerplate:
- Added an HTTP server in production and changed it from the `file://` protocol. (worked with no errors for many days before)

## Your Environment

- Node version : v17.5.0
- electron-react-boilerplate version or branch : main
- Operating System and version : macOS 10.14.6 (18G9028)

**Comment by amilajack** [comment]
Better to ask this in the electron-builder community. This doesn't seem to be related to the boilerplate.
