### ISSUE TITLE
Running into an issue with postinstall in npm workspaces (monorepo)

### ISSUE THREAD

**Issue by akoskm** [electron-react-boilerplate/electron-react-boilerplate#3216]
## Summary

Since we moved our electron application into a monorepo `npm start` fails to execute.
`postinstall` looks for a file on a remote location that doesn't exist:

https://github.com/electron/electron/releases/download/vinstall-app-deps/electron-vinstall-app-deps-darwin-arm64.zip

---
Our monorepo structure looks like this:
```
tenlog/
  packages/
    table/ <-- shared react component
    supersonic/ <-- ERB application
    varese/ <-- NodeJS app
  package.json
```

Here are the contents of the top-level package.json:

```
{
  "name": "@tenlog",
  "private": true,
  "workspaces": [
    "./packages/*"
  ]
}
```
First I'm running `npm i` in tenlog (the root of the monorepo).
After, I run `npm start` for the ERB app:

```
% npm run -w packages/supersonic start

> start
> ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer


> start:renderer
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts

The DLL files are missing. Sit back while we build them for you with "npm run build-dll"
npm ERR! Lifecycle script `postinstall` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: electron-react-boilerplate
npm ERR!   at location: /Users/akoskm/Projects/tenlog/packages/supersonic
[webpack-cli] Failed to load '/Users/akoskm/Projects/tenlog/packages/supersonic/.erb/configs/webpack.config.renderer.dev.ts' config
[webpack-cli] Error: Command failed: npm run postinstall
npm ERR! Lifecycle script `postinstall` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: electron-react-boilerplate
npm ERR!   at location: /Users/akoskm/Projects/tenlog/packages/supersonic

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (/Users/akoskm/Projects/tenlog/packages/supersonic/.erb/configs/webpack.config.renderer.dev.ts:39:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/akoskm/Projects/tenlog/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/akoskm/Projects/tenlog/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 0a 3e 20 70 6f 73 74 69 6e 73 74 61 6c 6c 0a 3e 20 74 73 2d 6e 6f 64 65 20 2e 65 72 62 2f 73 63 72 69 70 74 73 2f 63 68 65 63 6b 2d 6e 61 74 69 76 65 ... 2513 more bytes>,
    <Buffer 6e 70 6d 20 45 52 52 21 20 4c 69 66 65 63 79 63 6c 65 20 73 63 72 69 70 74 20 60 70 6f 73 74 69 6e 73 74 61 6c 6c 60 20 66 61 69 6c 65 64 20 77 69 74 ... 170 more bytes>
  ],
  pid: 15016,
  stdout: <Buffer 0a 3e 20 70 6f 73 74 69 6e 73 74 61 6c 6c 0a 3e 20 74 73 2d 6e 6f 64 65 20 2e 65 72 62 2f 73 63 72 69 70 74 73 2f 63 68 65 63 6b 2d 6e 61 74 69 76 65 ... 2513 more bytes>,
  stderr: <Buffer 6e 70 6d 20 45 52 52 21 20 4c 69 66 65 63 79 63 6c 65 20 73 63 72 69 70 74 20 60 70 6f 73 74 69 6e 73 74 61 6c 6c 60 20 66 61 69 6c 65 64 20 77 69 74 ... 170 more bytes>
}
npm ERR! Lifecycle script `start:renderer` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: electron-react-boilerplate
npm ERR!   at location: /Users/akoskm/Projects/tenlog/packages/supersonic
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: electron-react-boilerplate
npm ERR!   at location: /Users/akoskm/Projects/tenlog/packages/supersonic
```

I realized it failed on `postinstall` so I ran that directly, I think its output is more helpful:
```
% npm run -w packages/supersonic postinstall

> postinstall
> ts-node .erb/scripts/check-native-dep.js && electron-builder -c.electronVersion install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts && opencollective-postinstall

  • electron-builder  version=23.0.3 os=21.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/build/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=keytar@7.7.0 platform=darwin arch=arm64
  • install prebuilt binary  name=keytar version=7.7.0 platform=darwin arch=arm64 napi=
                                                                                         • packaging       platform=darwin arch=arm64 electron=install-app-deps appOutDir=release/build/mac-arm64
  ⨯ cannot resolve https://github.com/electron/electron/releases/download/vinstall-app-deps/electron-vinstall-app-deps-darwin-arm64.zip: status code 404
github.com/develar/app-builder/pkg/download.(*Downloader).follow
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:237
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
	/Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
	/usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581
  ⨯ /Users/akoskm/Projects/tenlog/node_modules/app-builder-bin/mac/app-builder_amd64 process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: /Users/akoskm/Projects/tenlog/node_modules/app-builder-bin/mac/app-builder_amd64 process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/Users/akoskm/Projects/tenlog/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! Lifecycle script `postinstall` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: electron-react-boilerplate
npm ERR!   at location: /Users/akoskm/Projects/tenlog/packages/supersonic
```

**Comment by akoskm** [comment]
## ✅  Solved

`electron-builder` doc states:

> electronVersion String | “undefined” - The version of electron you are packaging for. Defaults to version of electron, electron-prebuilt or electron-prebuilt-compile dependency.

https://www.electron.build/configuration/configuration

I suspect that because the package `electron` is not in the local `node_modules` anymore but in the top-level `node_modules` `electron-builder` cannot guess the version properly.

I solved this problem by adding the `electronVersion` options the the "build" in `packages/supersonic/package.json`:

```
"build": {
    "electronVersion": "18.2.0",
```
