### ISSUE TITLE
How to add the file in app.asar/dist ?

### ISSUE THREAD

**Issue by EGo14T** [electron-react-boilerplate/electron-react-boilerplate#3265]
When I use third-party dependencies, it reports a error
```js
(node:15600) UnhandledPromiseRejectionWarning: Error: ENOENT, dist\riotgames.pem not found in xxx\release\build\win-unpacked\resources\app.asar
    at createError (node:electron/js2c/asar_bundle:5:1255)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:5:7706)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at fsReadFileAsar (node:internal/util:346:12)
    at Object.readFile (node:electron/js2c/asar_bundle:5:9056)
    at next (xxx\release\build\win-unpacked\resources\app.asar\dist\main\webpack:\node_modules\xxx\dist\authentication.js:56:61)
    at Generator.next (<anonymous>)
    at xxx\release\build\win-unpacked\resources\app.asar\dist\main\webpack:\node_modules\xxx\dist\authentication.js:8:71
    at new Promise (<anonymous>)
```

so how to package the file in app.asar/dist ?

**Comment by EGo14T** [comment]
I solved the problem with copy-webpack-plugin
