### ISSUE TITLE
postinstall return node-abi error after install sqlite3

### ISSUE THREAD

**Issue by Aaqu** [electron-react-boilerplate/electron-react-boilerplate#3312]
- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

run `npm run postinstall` after `npm install sqlite3` in `/release/app`  work properly

## Current Behavior

return 
`Could not detect abi for version 20.0.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron`

## Steps to Reproduce

1. `cd /release/app`
2. `npm install sqlite3`
3. `npm run postinstall`
4. `cd ../..`
5. `npm run postinstall`

## Possible Solution (Not obligatory)

package.json
```
"overrides": { 
  "electron-rebuild": { "node-abi": "3.24.0" } 
},
```
or

1. go to project folder
2. `npm uninstall electron-rebuild`
3. `npm install --save-dev electron-rebuild`
4. `cd /release/app`
5. `npm run postinstall`

## Your Environment

- Node version :  16.15.0
- electron-react-boilerplate version or branch : 4.6.0
- Operating System and version : windows 10 and 11, mac os
- Link to your project :

**Comment by Aaqu** [comment]
more specifically, none-abi package in electron-rebuild needs updated to a latest version

**Comment by andrewrt** [comment]
i'm seeing the same issue when installing serialport to the /releases/app folder - so it seems like the latest version breaks all native deps perhaps?

same version of serialport was working with ERB from a few months ago... so assuming it's ERB related

**Comment by andrewrt** [comment]
i'll piggyback on your issue @Aaqu - here's my output: 
```
  ⨯ /Users/andrew/.nvm/versions/node/v14.17.0/bin/node process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Output:

> electron-react-boilerplate@4.6.0 postinstall /Users/andrew/code/js/electron/my-cool-app/release/app
> npm run electron-rebuild && npm run link-modules


> electron-react-boilerplate@4.6.0 electron-rebuild /Users/andrew/code/js/electron/my-cool-app/release/app
> node -r ts-node/register ../../.erb/scripts/electron-rebuild.js


Error output:
- Searching dependency tree
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
Could not detect abi for version 20.0.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 20.0.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/Users/andrew/code/js/electron/my-cool-app/node_modules/node-abi/index.js:39:9)
    at Rebuilder.get ABI [as ABI] (/Users/andrew/code/js/electron/my-cool-app/node_modules/electron-rebuild/lib/src/rebuild.js:86:39)
    at PrebuildInstall.prebuiltModuleExists (/Users/andrew/code/js/electron/my-cool-app/node_modules/electron-rebuild/lib/src/module-type/prebuild-install.js:61:179)
    at ModuleRebuilder.prebuildInstallNativeModuleExists (/Users/andrew/code/js/electron/my-cool-app/node_modules/electron-rebuild/lib/src/module-rebuilder.js:68:37)
    at Rebuilder.rebuildModuleAt (/Users/andrew/code/js/electron/my-cool-app/node_modules/electron-rebuild/lib/src/rebuild.js:128:35)
    at async Rebuilder.rebuild (/Users/andrew/code/js/electron/my-cool-app/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
    at async /Users/andrew/code/js/electron/my-cool-app/node_modules/electron-rebuild/lib/src/cli.js:158:9
Error: Command failed: ../../node_modules/.bin/electron-rebuild --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:640:11)
    at execSync (child_process.js:676:15)
    at Object.<anonymous> (/Users/andrew/code/js/electron/my-cool-app/.erb/scripts/electron-rebuild.js:16:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/Users/andrew/code/js/electron/my-cool-app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (/Users/andrew/code/js/electron/my-cool-app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 82257,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@4.6.0 electron-rebuild: `node -r ts-node/register ../../.erb/scripts/electron-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@4.6.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrew/.npm/_logs/2022-09-13T23_53_31_513Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@4.6.0 postinstall: `npm run electron-rebuild && npm run link-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@4.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrew/.npm/_logs/2022-09-13T23_53_31_571Z-debug.log
  failedTask=installAppDeps stackTrace=Error: /Users/andrew/.nvm/versions/node/v14.17.0/bin/node process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1```

**Comment by Aaqu** [comment]
Template have electron-rebuild with node-abi version 3.8.0 ([package-lock.json](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/package-lock.json))
In this release, node-abi supports electron v18 ([node-abi 3.8.0](https://github.com/lgeiger/node-abi/compare/v3.7.0...v3.8.0))
```
    "node_modules/node-abi": {
      "version": "3.8.0",
      "resolved": "https://registry.npmjs.org/node-abi/-/node-abi-3.8.0.tgz",
      "integrity": "sha512-tzua9qWWi7iW4I42vUPKM+SfaF0vQSLAm4yO5J83mSwB7GeoWrDKC/K+8YCnYNwqP5duwazbw2X9l4m8SC2cUw==",
      "dev": true,
      "dependencies": {
        "semver": "^7.3.5"
      },
      "engines": {
        "node": ">=10"
      }
    },
```

update to 3.24.0 this includes support for electron v21 and lower ([node-abi 3.24.0](https://github.com/electron/node-abi/compare/v3.23.0...v3.24.0))
 
```
    "node_modules/node-abi": {
      "version": "3.24.0",
      "resolved": "https://registry.npmjs.org/node-abi/-/node-abi-3.24.0.tgz",
      "integrity": "sha512-YPG3Co0luSu6GwOBsmIdGW6Wx0NyNDLg/hriIyDllVsNwnI6UeqaWShxC3lbH4LtEQUgoLP3XR1ndXiDAWvmRw==",
      "dev": true,
      "dependencies": {
        "semver": "^7.3.5"
      },
      "engines": {
        "node": ">=10"
      }
    },
```

**Comment by AbdoShiabany** [comment]
I have the same issue here .. I tried 

"overrides": { 
  "electron-rebuild": { "node-abi": "3.24.0" } 
},

in pacakge.json

and I tried to update package-lock.json to this:

    "node_modules/node-abi": {
      "version": "3.24.0",
      "resolved": "https://registry.npmjs.org/node-abi/-/node-abi-3.24.0.tgz",
      "integrity": "sha512-YPG3Co0luSu6GwOBsmIdGW6Wx0NyNDLg/hriIyDllVsNwnI6UeqaWShxC3lbH4LtEQUgoLP3XR1ndXiDAWvmRw==",
      "dev": true,
      "dependencies": {
        "semver": "^7.3.5"
      },
      "engines": {
        "node": ">=10"
      }
    },

And here is the output:
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\User\Desktop\Electronjs\react electron\accountant\release\app\node_modules\sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use



Error: node-gyp failed to rebuild 'C:\Users\User\Desktop\Electronjs\react electron\accountant\release\app\node_modules\sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use


    at NodeGyp.rebuildModule (C:\Users\User\Desktop\Electronjs\react electron\accountant\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (C:\Users\User\Desktop\Electronjs\react electron\accountant\node_modules\electron-rebuild\lib\src\module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (C:\Users\User\Desktop\Electronjs\react electron\accountant\node_modules\electron-rebuild\lib\src\module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (C:\Users\User\Desktop\Electronjs\react electron\accountant\node_modules\electron-rebuild\lib\src\rebuild.js:149:13)
    at async Rebuilder.rebuild (C:\Users\User\Desktop\Electronjs\react electron\accountant\node_modules\electron-rebuild\lib\src\rebuild.js:112:17)
    at async C:\Users\User\Desktop\Electronjs\react electron\accountant\node_modules\electron-rebuild\lib\src\cli.js:158:9
Error: Command failed: ..\..\node_modules\.bin\electron-rebuild --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:902:15)
    at Object.<anonymous> (C:\Users\User\Desktop\Electronjs\react electron\accountant\.erb\scripts\electron-rebuild.js:16:11)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\User\Desktop\Electronjs\react electron\accountant\node_modules\ts-node\src\index.ts:1621:12)                                                                                                                                                         )
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 15180,
  stdout: null,
  stderr: null
}

**Comment by Aaqu** [comment]
> Error: Could not find any Visual Studio installation to use

Try to install visual studio like in this tutorial, node gyp needs it
[visual studio configuration](https://stackoverflow.com/a/61721059/14549188)
