### ISSUE TITLE
An unhandled error occurred inside electron-rebuild node-gyp failed to rebuild on install better-sqlite3

### ISSUE THREAD

**Issue by Beerwerd** [electron-react-boilerplate/electron-react-boilerplate#3338]
## Prerequisites

when I try to install `better-sqlite3` in `release/app` folder in `4.6.0` version, I got an error:

- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)

```
> electron-react-boilerplate@4.6.0 electron-rebuild
> node -r ts-node/register ../../.erb/scripts/electron-rebuild.js

⠇ Building module: better-sqlite3, Completed: 0  TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
⠏ Building module: better-sqlite3, Completed: 0  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
⠴ Building module: better-sqlite3, Completed: 0  LIBTOOL-STATIC Release/sqlite3.a
⠧ Building module: better-sqlite3, Completed: 0  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
⠙ Building module: better-sqlite3, Completed: 0./src/util/macros.lzz:157:21: error: no member named 'AccessorSignature' in namespace 'v8'
                v8::AccessorSignature::New(isolate, recv)
                ~~~~^
./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
                int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
                    ^
./src/util/binder.lzz:37:51: error: no member named 'CreationContext' in 'v8::Object'
                v8::Local<v8::Context> ctx = obj->CreationContext();
                                             ~~~~~^
⠹ Building module: better-sqlite3, Completed: 01 warning and 2 errors generated.
make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/project/release/app/node_modules/better-sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/project/release/app/node_modules/better-sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/project/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/project/node_modules/electron-rebuild/lib/src/module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (/project/node_modules/electron-rebuild/lib/src/module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (/project/node_modules/electron-rebuild/lib/src/rebuild.js:149:13)
    at async Rebuilder.rebuild (/project/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
    at async /project/node_modules/electron-rebuild/lib/src/cli.js:158:9
Error: Command failed: ../../node_modules/.bin/electron-rebuild --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (/project/.erb/scripts/electron-rebuild.js:16:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (/project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 47660,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.

```

At the same time the solution from [example](https://github.com/amilajack/erb-better-sqlite3-example) installs and works correct

- Node version : v16.15.1
- electron-react-boilerplate version or branch : 4.6.0
- Operating System and version : MacOS Monterey

**Comment by reza-azimi-dev** [comment]
have you tried to install Command Line Tools? in my case I had to install it from XCode > Open Developer Tools > More Developer Tools. It will redirect you to developer.apple page .Then install the Command Line Tools from the list.

**Comment by reza-azimi-dev** [comment]
having the same issue while trying to install `active-win` as dependency in `release/app/package.json`

my log:
```
npm i             

> electron-react-boilerplate@4.6.0 postinstall
> npm run electron-rebuild && npm run link-modules


> electron-react-boilerplate@4.6.0 electron-rebuild
> node -r ts-node/register ../../.erb/scripts/electron-rebuild.js

⠴ Building module: ffi-napi, Completed: 0  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
⠦ Building module: ffi-napi, Completed: 0  LIBTOOL-STATIC Release/nothing.a
⠧ Building module: ffi-napi, Completed: 0warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
⠇ Building module: ffi-napi, Completed: 0  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
⠏ Building module: ffi-napi, Completed: 0  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
⠋ Building module: ffi-napi, Completed: 0  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
../deps/libffi/src/java_raw_api.c:328:46: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
  ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
                                             ^
../deps/libffi/config/mac/arm64/ffi.h:299:56: note: 'ffi_java_raw_size' has been explicitly marked deprecated here
size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
                                                       ^
../deps/libffi/src/java_raw_api.c:331:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
  ffi_java_ptrarray_to_raw (cif, avalue, raw);
  ^
../deps/libffi/config/mac/arm64/ffi.h:295:93: note: 'ffi_java_ptrarray_to_raw' has been explicitly marked deprecated here
void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw) __attribute__((deprecated));
                                                                                            ^
2 warnings generated.
⠙ Building module: ffi-napi, Completed: 0  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
⠹ Building module: ffi-napi, Completed: 0  CC(target) Release/obj.target/ffi/deps/libffi/src/aarch64/ffi.o
../deps/libffi/src/aarch64/ffi.c:738:17: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
      if (i + 1 == cif->aarch64_nfixedargs)
          ~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/aarch64/ffi.c:991:17: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
      if (i + 1 == cif->aarch64_nfixedargs)
          ~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~
⠸ Building module: ffi-napi, Completed: 02 warnings generated.
  CC(target) Release/obj.target/ffi/deps/libffi/src/aarch64/sysv.o
⠼ Building module: ffi-napi, Completed: 0  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
⠸ Building module: ffi-napi, Completed: 0  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
⠋ Building module: ffi-napi, Completed: 0  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
⠼ Building module: ffi-napi, Completed: 0  SOLINK_MODULE(target) Release/ffi_bindings.node
⠏ Building module: ref-napi, Completed: 1  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
⠋ Building module: ref-napi, Completed: 1warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/binding/src/binding.o
⠸ Building module: ref-napi, Completed: 1../src/binding.cc:305:13: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
    *rptr = std::move(Reference<Object>::New(val));
            ^
../src/binding.cc:305:13: note: remove std::move call here
    *rptr = std::move(Reference<Object>::New(val));
            ^~~~~~~~~~                           ~
⠙ Building module: ref-napi, Completed: 11 warning generated.
  SOLINK_MODULE(target) Release/binding.node
⠼ Building module: iconv, Completed: 2  CXX(target) Release/obj.target/iconv/src/binding.o
⠇ Building module: iconv, Completed: 2In file included from ../src/binding.cc:18:
In file included from ../../../../nan/nan.h:180:
../../../../nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
typedef v8::Local<v8::AccessorSignature> Sig;
                  ~~~~^
In file included from ../src/binding.cc:18:
../../../../nan/nan.h:2546:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/xyz/.electron-gyp/20.3.1/include/node/v8-template.h:814:8: note: candidate function not viable: no known conversion from 'imp::Sig' (aka 'int') to 'v8::SideEffectType' for 7th argument
  void SetAccessor(
       ^
/Users/xyz/.electron-gyp/20.3.1/include/node/v8-template.h:807:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::AccessorGetterCallback' (aka 'void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') for 2nd argument
  void SetAccessor(
       ^
2 errors generated.
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/ex1/release/app/node_modules/ref-wchar-napi/node_modules/iconv'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/ex1/release/app/node_modules/ref-wchar-napi/node_modules/iconv'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/ex1/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/ex1/node_modules/electron-rebuild/lib/src/module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (/ex1/node_modules/electron-rebuild/lib/src/module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (/ex1/node_modules/electron-rebuild/lib/src/rebuild.js:149:13)
    at async Rebuilder.rebuild (/ex1/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
    at async /ex1/node_modules/electron-rebuild/lib/src/cli.js:158:9
Error: Command failed: ../../node_modules/.bin/electron-rebuild --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at Object.<anonymous> (/ex1/.erb/scripts/electron-rebuild.js:16:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/ex1/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/ex1/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 95117,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /ex1/release/app
npm ERR! command failed
npm ERR! command sh -c -- npm run electron-rebuild && npm run link-modules

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2022-10-07T21_39_32_513Z-debug-0.log


```

**Comment by leopucci** [comment]
Hey guys how are you? It happened to me also. 
This is because electron 20 is not supported yet by sqlite. 
https://github.com/WiseLibs/better-sqlite3/issues/867
As suggested on this other issue, 
`FWIW you can npm install electron@19.0.10 and still get npx electron-rebuild -f -w better-sqlite3 to work as expected while we wait.`

**Comment by amilajack** [comment]
closing, unrelated to ERB
