### ISSUE TITLE
Build package with @tensorflow/tfjs-node

### ISSUE THREAD

**Issue by caoquy2000** [electron-react-boilerplate/electron-react-boilerplate#3339]
Hi guys, im using Electron v12.2.3 and Window 10.
When i run: npm run package and run exe file.
I got error:
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: package.json does not exist at C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\package.json
    at Object.t.find (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:729566)
    at Object.11587 (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:2:313685)
    at webpack_require (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:9465201)
    at Object.69908 (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:1067158)
    at webpack_require (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:9465201)
    at Object.35533 (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:1069188)
    at webpack_require (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:9465201)
    at C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:9466047
    at Object.<anonymous> (C:\Users\Admin\Documents\Project\Desktop\OmicallProjectLocalTeam\release\build\win-unpacked\resources\app\dist\main\main.js:14:9466110)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

[OK]
I imported the @tensorflow/tfjs-node in main.js. I think its call ./package.json. So how can i fix it ?. How can i use tfjs-node and npm run package successfully?
Thanks!

**Comment by amilajack** [comment]
See https://electron-react-boilerplate.js.org/docs/native-modules
