### ISSUE TITLE
Resolve error: TSError: ⨯ Unable to compile TypeScript:

### ISSUE THREAD

**Issue by sanket1726** [electron-react-boilerplate/electron-react-boilerplate#3423]
![image](https://user-images.githubusercontent.com/32524672/218660136-4b16e71f-589d-4f75-b9bd-aaa4b04a65ab.png)

**Comment by lucasrabiec** [comment]
I noticed the same issue. Any ideas?

**Comment by theronburger** [comment]
Having a similar issue when importing a typescript file without the extension.
The error reports the checkNodeEnv function being implicitly any
```
Resolve error: TSError: ⨯ Unable to compile TypeScript:
app/.erb/configs/webpack.config.renderer.dev.ts(12,26):
error TS7016: Could not find a declaration file for module '../scripts/check-node-env'. 
'/Users/theron/Developer/CodeWorks/Rulie/app/.erb/scripts/check-node-env.js'
implicitly has an 'any' type.
```

Adding the extension to the import clears up the error.
However typescript imports should not have extensions.
The app runs as normal despite VS Code displaying the error.

Steps to reproduce :
Clean install as per https://electron-react-boilerplate.js.org/docs/installation
Create a component typescript file in renderer/components, say "Menu.tsx"

```
export default function Menu() {
  return <div className="text-sky-500">I am the menu</div>;
}
```

in App, importing without the .tsx extension causes the error 
```
import { MemoryRouter as Router, Routes, Route } from 'react-router-dom';
import Menu from './components/Menu';
```

**Comment by habibatabay** [comment]
I have the same issue. Anyone help?

**Comment by jamiejcole** [comment]
Getting the same issue as well with a clean install of ERB.

I'm getting the following error (8 of them) on line 1 of `src/renderer/index.tsx`:
```
Resolve error: TSError: ⨯ Unable to compile TypeScript:
electron/.erb/configs/webpack.config.renderer.dev.ts(12,26): error TS7016: Could not find a declaration file for module '../scripts/check-node-env'. 'C:/Users/admin/Documents/project/electron/.erb/scripts/check-node-env.js' implicitly has an 'any' type.

    at createTSError (C:\Users\admin\Documents\project\electron\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\admin\Documents\project\electron\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\admin\Documents\project\electron\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\admin\Documents\project\electron\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Users\admin\Documents\project\electron\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\admin\Documents\project\electron\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)eslint[import/no-duplicates](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/no-duplicates.md)
```

Adding the .js file extension `import checkNodeEnv from '../scripts/check-node-env.js';
` in `webpack.config.renderer.dev.ts` doesn't clear the error for me either.
> Having a similar issue when importing a typescript file without the extension. The error reports the checkNodeEnv function being implicitly any
> 
> ```
> Resolve error: TSError: ⨯ Unable to compile TypeScript:
> app/.erb/configs/webpack.config.renderer.dev.ts(12,26):
> error TS7016: Could not find a declaration file for module '../scripts/check-node-env'. 
> '/Users/theron/Developer/CodeWorks/Rulie/app/.erb/scripts/check-node-env.js'
> implicitly has an 'any' type.
> ```
> 
> Adding the extension to the import clears up the error. However typescript imports should not have extensions. The app runs as normal despite VS Code displaying the error.
> 
> Steps to reproduce : Clean install as per https://electron-react-boilerplate.js.org/docs/installation Create a component typescript file in renderer/components, say "Menu.tsx"
> 
> ```
> export default function Menu() {
>   return <div className="text-sky-500">I am the menu</div>;
> }
> ```
> 
> in App, importing without the .tsx extension causes the error
> 
> ```
> import { MemoryRouter as Router, Routes, Route } from 'react-router-dom';
> import Menu from './components/Menu';
> ```

**Comment by jamiejcole** [comment]
Modifying `.eslintrc.js` in root folder to include node config has cleaned up the error for me. Seems to be a duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3235.
```
settings: {
    'import/resolver': {
      // See https://github.com/benmosher/eslint-plugin-import/issues/1396#issuecomment-575727774 for line below
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        moduleDirectory: ['node_modules', 'src/'],
      },
      webpack: {
        config: require.resolve('./.erb/configs/webpack.config.eslint.ts'),
      },
      typescript: {},
    },
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
  },
```
