### ISSUE TITLE
Error running build command without deleting dist folder manually

### ISSUE THREAD

**Issue by josegiufrida** [electron-react-boilerplate/electron-react-boilerplate#3424]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Run `npm run build` without having to delete the dist folder manually

## Current Behavior

Running `npm run build` more than once causes an error, as the `dist` folder is not removed automatically.
The `npm run package` command, on the other hand, does work correctly, since it includes the deletion of the dist folder.

## Steps to Reproduce

- Run `npm run build`
- Run `npm run build` again

**Stack traces**

[0] npmnpm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[0]  WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[1] 
[1] > build:renderer
[1] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.prod.ts
[1] 
[0] 
[0] > build:main
[0] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.main.prod.ts
[0] 
[0] [webpack-cli] Failed to load 'C:\projects\test-erb\.erb\configs\webpack.config.main.prod.ts' config
[0] [webpack-cli] Error: Illegal characters in path.
[0]     at pathArg (C:\projects\test-erb\node_modules\rimraf\src\path-arg.ts:48:27)
[0]     at AsyncFunction.<anonymous> (C:\projects\test-erb\node_modules\rimraf\src\index.ts:56:19)
[0]     at deleteSourceMaps (C:\projects\test-erb\.erb\scripts\delete-source-maps.js:8:12)
[0]     at Object.<anonymous> (C:\projects\test-erb\.erb\configs\webpack.config.main.prod.ts:16:17)
[0]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[0]     at Module.m._compile (C:\projects\test-erb\node_modules\ts-node\src\index.ts:1618:23)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[0]     at Object.require.extensions.<computed> [as .ts] (C:\projects\test-erb\node_modules\ts-node\src\index.ts:1621:12)
[0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
[0]   path: 'C:\\projects\\test-erb\\release\\app\\dist\\main\\*.js.map',
[0]   code: 'EINVAL'
[0] }
[0] npm run build:main exited with code 2
[1] [webpack-cli] Failed to load 'C:\projects\test-erb\.erb\configs\webpack.config.renderer.prod.ts' config
[1] [webpack-cli] Error: Illegal characters in path.
[1]     at pathArg (C:\projects\test-erb\node_modules\rimraf\src\path-arg.ts:48:27)
[1]     at AsyncFunction.<anonymous> (C:\projects\test-erb\node_modules\rimraf\src\index.ts:56:19)
[1]     at deleteSourceMaps (C:\projects\test-erb\.erb\scripts\delete-source-maps.js:8:12)
[1]     at Object.<anonymous> (C:\projects\test-erb\.erb\configs\webpack.config.renderer.prod.ts:19:17)
[1]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[1]     at Module.m._compile (C:\projects\test-erb\node_modules\ts-node\src\index.ts:1618:23)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[1]     at Object.require.extensions.<computed> [as .ts] (C:\projects\test-erb\node_modules\ts-node\src\index.ts:1621:12)
[1]     at Module.load (node:internal/modules/cjs/loader:981:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
[1]   path: 'C:\\projects\\test-erb\\release\\app\\dist\\main\\*.js.map',
[1]   code: 'EINVAL'
[1] }
[1] npm run build:renderer exited with code 2

## Possible Solution (Not obligatory)

Add `ts-node ./.erb/scripts/clean.js dist` on `build` command.

**Comment by MaxAzarov** [comment]
I think that this error is connected to this one: 
https://stackoverflow.com/questions/75281066/error-illegal-characters-in-path-in-npm-rimraf
So the solution is to use rimraf v3

**Comment by jsam07** [comment]
If you don't want to downgrade to v3, you could set the `glob` option to `true` in [delete-source-maps.js](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/7e0d6f9bd6a3490f418e8489760ee8f67ae4b97e/.erb/scripts/delete-source-maps.js#L6):

```js
rimraf.sync(path.join(webpackPaths.distMainPath, '*.js.map'), { glob: true });
rimraf.sync(path.join(webpackPaths.distRendererPath, '*.js.map'), { glob: true });
```

🚨Note: globbing was only restored in `v4.2.0` and above.
