### ISSUE TITLE
`rimraf` v4 breaks `.erb/scripts/delete-source-maps.js`

### ISSUE THREAD

**Issue by nexensys** [electron-react-boilerplate/electron-react-boilerplate#3452]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

The second call of `npm run build` should delete source maps as intended

## Current Behavior

Process exited with code `2`:
```
 [webpack-cli] Failed to load '...\.erb\configs\webpack.config.renderer.prod.ts' config
 [webpack-cli] Error: Illegal characters in path.
     at pathArg (...\node_modules\rimraf\src\path-arg.ts:48:27)
     at AsyncFunction.<anonymous> (...\node_modules\rimraf\src\index.ts:56:19)
     at Object.<anonymous> (...\.erb\configs\webpack.config.renderer.prod.ts:20:17)
     at Module._compile (node:internal/modules/cjs/loader:1105:14)
     at Module.m._compile (...\node_modules\ts-node\src\index.ts:1618:23)
     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
     at Object.require.extensions.<computed> [as .ts] (...\node_modules\ts-node\src\index.ts:1621:12)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Function.Module._load (node:internal/modules/cjs/loader:827:12) {
   path: '...\\release\\app\\dist\\main\\*.js.map',
   code: 'EINVAL'
 }
```

## Steps to Reproduce

Literally just run `npm run build` twice

## Possible Solution (Not obligatory)

It appears that `rimraf` version 4 removed wildcard support (see isaacs/rimraf#249) Current, working, solution is to downgrade to version `3.0.2`

## Context

Trying to rebuild (testing my implementation of multi-renderer support) was much harder having to delete the folder every time.

## Your Environment

- Node version : 18.1.0
- electron-react-boilerplate version or branch : latest, main branch
- Operating System and version : Windows 10
- Link to your project : (closed source, sorry)

**Comment by ghayasleo** [comment]
@ErrorGamer2000 Did you get the solution? I am currently new to electron js and I wanna build a desktop app real quick and I'm not sure if I should use this boilerplate or not

**Comment by ErrorGamer2000** [comment]
@ghayasleo Yes. Either edit your `package.json` file and set the `rimraf` dependency version to `^3.0.2` or (easier) run `npm i -f rimraf@3`.

**Comment by georgiancamarasan** [comment]
#3469 should fix the issue.
