### ISSUE TITLE
Database Folder in Src not packaging

### ISSUE THREAD

**Issue by akshatsingh1718** [electron-react-boilerplate/electron-react-boilerplate#3478]
## Other Folder's not Packaging

I am creating an ap where i will be using database SQL as well. The database folder is present in src dir where main and renderer folder is also kept. 
```
- package.json
- assets
-  src
 |----- main
 |----- renderer
 |----- database
```

when I am running 
```npm run package``` 

and importing these lines 

```  
const controller = require(path.join(__dirname, '../database/controller'));
const db = require(path.join(__dirname, '../database/models'));
```

I am getting an error the following error 

```
Error: Cannot find module 'C:\Users\Akshat singh\AppData\Local\Programs\pmsProForASR\resources\app.asar\dist\database\controller'
    at t (C:\Users\Akshat singh\AppData\Local\Programs\pmsProForASR\resources\app.asar\dist\main\webpack:\pmsProForASR\src\main\ sync:2:10)
    at C:\Users\Akshat singh\AppData\Local\Programs\pmsProForASR\resources\app.asar\dist\main\webpack:\pmsProForASR\src\main\main.ts:160:22
    at C:\Users\Akshat singh\AppData\Local\Programs\pmsProForASR\resources\app.asar\dist\main\webpack:\pmsProForASR\src\main\main.ts:495:37
    at factory (C:\Users\Akshat singh\AppData\Local\Programs\pmsProForASR\resources\app.asar\dist\main\webpack:\pmsProForASR\src\main\main.ts:495:37)
    at C:\Users\Akshat singh\AppData\Local\Programs\pmsProForASR\resources\app.asar\dist\main\webpack:\pmsProForASR\webpack\universalModuleDefinition:3:20
    at Object.<anonymous> (C:\Users\Akshat singh\AppData\Local\Programs\pmsProForASR\resources\app.asar\dist\main\webpack:\pmsProForASR\webpack\universalModuleDefinition:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by salimdriai** [comment]
@akshatsingh1718  did you found any solution ?
