### ISSUE TITLE
How to set up paths with TsconfigPathsPlugins

### ISSUE THREAD

**Issue by akoskm** [electron-react-boilerplate/electron-react-boilerplate#3535]
I'm replacing my relative imports with absolute imports. Here are some of the important dependencies and their versions from my `package.json`:

```
"eslint": "^8.49.0",
"eslint-config-erb": "^4.0.6"
"webpack": "^5.88.2",
"tsconfig-paths-webpack-plugin": "^4.1.0",
"typescript": "^5.2.2",
```

I added the `TsconfigPathsPlugins` plugin to `.erb/configs/webpack.config.base.ts` and set up `tsconfig.json` like the following:

```
{
  "compilerOptions": {
    "incremental": true,
    "target": "es2021",
    "module": "commonjs",
    "lib": ["dom", "es2021"],
    "jsx": "react-jsx",
    "strict": true,
    "sourceMap": true,
    "baseUrl": "./src",
    /* Additional Checks */
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    /* Module Resolution Options */
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "allowJs": true,
    "skipLibCheck": true,
    "outDir": ".erb/dll",
    "typeRoots": ["./src/types", "node_modules/@types"],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "exclude": ["test", "release/build", "release/app/dist", ".erb/dll"]
}
```

Both tsc and eslint checks are passing with these changes and I don't see any errors in my editor when using the aliased imports:

```
// src/main.ts
...
import { APP_STARTED } from '@/renderer/telemetry/constants';
...
```

However, when starting the app the modules are not found:

```
% npm start

> start
> ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer


> start:renderer
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts

Starting preload.js builder...
Starting Main Process...
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:1212/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.27:1212/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:1212/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/akoskm/Projects/sprcalc-electron/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'

> start:main
> cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only ./src/main/main.ts


> start:preload
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts

[electronmon] waiting for a change to restart it
App threw an error during load
Error: Cannot find module '@/renderer/telemetry/constants'
Require stack:
- /Users/akoskm/Projects/sprcalc-electron/src/main/main.ts
- /Users/akoskm/Projects/sprcalc-electron/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:117419)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/akoskm/Projects/sprcalc-electron/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (/Users/akoskm/Projects/sprcalc-electron/node_modules/runtime-required/runtime-required.js:28:44)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1150:19)
    at Module.patchedRequire (/Users/akoskm/Projects/sprcalc-electron/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at Module.Hook._require.Module.require (/Users/akoskm/Projects/sprcalc-electron/node_modules/require-in-the-middle/index.js:167:34)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/akoskm/Projects/sprcalc-electron/src/main/main.ts:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
```

**Comment by adamhp** [comment]
@srischard That helped me out thanks!
