### ISSUE TITLE
Can't get Node-Pty working

### ISSUE THREAD

**Issue by daniel-centore** [electron-react-boilerplate/electron-react-boilerplate#3566]
## Summary

I'm using electron-react-boilerplate and I'm struggling to get `node-pty` installed. 

* I first add `"node-pty": "^1.0.0"` to `release/app/package.json`
* `cd root/release/app`
* `npm i`
* `cd root`
* `npm i`

If I do `npm run start`, it executes, but any calls to pty result in error
```typescript
import pty from 'node-pty';
pty.spawn('bash', [], {
    name: 'xterm-color',
    cols: 80,
    rows: 24,
    cwd: process.env.HOME,
    env: process.env,
  });
```
```
Error occurred in handler for 'checkout': TypeError: Cannot read properties of undefined (reading 'spawn')
```

If instead I build using `npm run build` and then execute using `node release/app/dist/main/main.js`, I get the error:
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/lib/unixTerminal.js
- /Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/lib/index.js
- /Users/dcentore/Dropbox/Projects/Derevo/release/app/dist/main/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/lib/unixTerminal.js',
    '/Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/lib/index.js',
    '/Users/dcentore/Dropbox/Projects/Derevo/release/app/dist/main/main.js'
  ]
}
/Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/lib/unixTerminal.js:40
        throw outerError;
        ^

Error: The module '/Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 116. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/dcentore/Dropbox/Projects/Derevo/release/app/node_modules/node-pty/lib/unixTerminal.js:29:11)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.6.1
```

How can I get node-pty working with the `electron-react-boilerplate`?

**Comment by daniel-centore** [comment]
The answer is here: https://stackoverflow.com/a/77691961/998251

Needed to use:

```typescript
import * as pty from 'node-pty';
```
