### ISSUE TITLE
Error: Invalid header: Does not start with Cr24

### ISSUE THREAD

**Issue by aza547** [electron-react-boilerplate/electron-react-boilerplate#3671]
## Prerequisites

- [ x ] Using npm
- [ x ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ x ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ x ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ x ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

No error.

## Current Behavior

An error is logged to the terminal in dev mode.

```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:1212/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.180:1212/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::4ca0:a33a:17c3:d881]:1212/
<i> [webpack-dev-server] Content not from webpack is served from 'D:\checkouts\electron-react-boilerplate\public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] [electronmon] waiting for a change to restart it
[1]
[1] Error: Invalid header: Does not start with Cr24
[1]     at crxToZip (D:\checkouts\electron-react-boilerplate\.erb\dll\main.bundle.dev.js:42519:15)
[1]     at D:\checkouts\electron-react-boilerplate\.erb\dll\main.bundle.dev.js:42556:32
[1]     at callHanler (D:\checkouts\electron-react-boilerplate\.erb\dll\main.bundle.dev.js:43561:16)
[1]     at tryCatcher (D:\checkouts\electron-react-boilerplate\.erb\dll\main.bundle.dev.js:43278:32)
[1]     at D:\checkouts\electron-react-boilerplate\.erb\dll\main.bundle.dev.js:43417:38
[1]     at flush (D:\checkouts\electron-react-boilerplate\.erb\dll\main.bundle.dev.js:43320:17)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[1] 17:16:53.852 > Skip checkForUpdates because application is not packed and dev update config is not forced
[1] 17:16:53.854 > checkForUpdatesAndNotify called, downloadPromise is null
```

## Steps to Reproduce

1. Clone the latest version of main.
2. `npm install`
3. `npm start`
4. Error appears.

## Possible Solution (Not obligatory)

Unclear, but looks like a reappearance of this: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2577. 

## Context
Low impact, but may cause FUD. 

## Your Environment

- Node version : v20.10.0 (also occurs on v22.12.0)
- electron-react-boilerplate version or branch : latest main
- Operating System and version : Windows 11
- Link to your project : N/A

**Comment by jamesblashill** [comment]
I'm not familiar with this package, but I experienced the same problem just today after cloning the repo. Upon upgrading: `electron-devtools-installer` from `3.2.0` => `3.2.1`, the problem went away for me.

**Comment by aza547** [comment]
That resolves it for me also. Thanks!
