### ISSUE TITLE
Publishing app to web & electron – preferred approach?

### ISSUE THREAD

**Issue by t1mmen** [electron-react-boilerplate/electron-react-boilerplate#80]
I'm looking to publish my app both to the web, and as a standalone executable. 

Is anyone doing this, and if so, care to share your preferred approach? If not, is this something the maintainers are interested in as part of the repo? I'll try to lend a helping hand in the coming weeks if so.

**Comment by chentsulin** [comment]
I think we should not include web stuff into this boilerplate, it will increase unnecessary complexity in a desktop-only application. But if someone is interested in how to build them together, I can work on a separate repo to demo it in next couple of weeks.

**Comment by t1mmen** [comment]
@chentsulin Makes sense to keep it separate for complexities sake. I'd be *very* interested in a demo of how to, though!

**Comment by alexhawkins** [comment]
I'd be very interested in this as well. @chentsulin  Let me know if you decide to do this. I'm going to see if I can get it to work on my own but any help from anyone would be much appreciated. Shoot me an email @ alex.hawkins@shiphawk.com

**Comment by flywithmemsl** [comment]
Yo @chentsulin, I'm currently working with your boilerplate, it awesome, thank you. 
I'll need website build feature in next two weeks, so if I can help you somehow with it, please tell me.

**Comment by acao** [comment]
I'm doing this with a modified version of this boilerplate.

All i had to do was handle argv from make-webpack-config, and when 'web' is provided then the webpack options.target = web, otherwise the electron renderer as this boilerplate provides.

Deployment is another matter - I just adapted the package.json scripts to a makefile and deploy the web version to s3 (after running a build-web using --target web as described above).

It's actually not very complicated at all. The only thing I have left to is find some way to allow the renderer process to detect whether its being run in electron or in the web, so that for example 'openDialog' function can choose to open a native dialog or material ui dialog.

The one thing that will get you caught is what build you're running in development depending on whether you are developing for electron or web, and same for deployment. Oh and make sure hot-dev-server knows what it needs to do as well.

**Comment by acao** [comment]
Apologies, I forked this project a few months ago and the webpack config has changed significantly since then. I hope that this still helps folks who are looking to get this working!

**Comment by flywithmemsl** [comment]
https://gist.github.com/flywithmemsl/0d9eba3c7e0ebc3dddc3 — works for me
replaced `commonjs2` with `var` in libraryTarget
removed `webpackTargetElectronRenderer`

**Comment by acao** [comment]
Cool! Also forgot to mention, i just passed --target web to wepback-dev-server/wepback, no argv handling

From my makefile:
```makefile
build-web:
	@node_modules/.bin/webpack --config webpack/webpack.config.production.js --progress --profile --colors --target web

build:
	@node_modules/.bin/webpack --config webpack/webpack.config.production.js --progress --profile --colors

hot-dev-web:
	@node_modules/.bin/webpack-dev-server --config webpack/webpack-hot-dev-server.config.js --hot --progress --colors --port 2992 --inline --target web
```
if you specify --target to webpack-dev-server or webpack, it overrides the webpack options.target prop.

**Comment by t1mmen** [comment]
I can confirm that @acao's approach works fine. Thanks!

**Comment by t1mmen** [comment]
Another thing to keep in mind: Polyfills weren't set up by default when I cloned this project, so you might want to include that when building for the web (assuming you're using ES6/7 features)

In the webpack config, change:

 `config.entry = './app/index'`

... to... 

 `config.entry = ['babel-core/polyfill', './app/index'];`

**Comment by marekhrabe** [comment]
Thanks a lot for your research, guys. I will try to add web support to my project this week. 

I'm just wondering if the solution is to create webpack target and introduce a way to detect the environment (browser/electron) it might be worth adding right to the core or at least transform this discussion into a simple docs page? I can probably help with that if @chentsulin would be interested :)

**Comment by Kornflexx** [comment]
Hello :),
The compilation work well, but I don't know how to use the files int dist/. How do I connect to the web app with my browser ?

I'm waiting for the update, thanks a lot for your work :)

**Comment by aequasi** [comment]
Were you able to make that separate repo @chentsulin? Instructions seem unclear now. Seems like the structure has changed considerably

**Comment by amilajack** [comment]
there hasnt been any progress on this yet

**Comment by doulmi** [comment]
0 o, No one can give a simple solution?

**Comment by amilajack** [comment]
I haven't looked into it too much yet.

**Comment by chentsulin** [comment]
I'd recommend for using [nativefier](https://github.com/jiahaog/nativefier) to create a new web app runs on both env. It's the simplest way that I could ever find.

**Comment by aequasi** [comment]
I'm sorry, but that is a terrible solution.

**Comment by vjtc0n** [comment]
Have anyone done this task successfully yet ?

**Comment by amilajack** [comment]
@vjtc0n not yet. I'm thinking of integrating `react-boilerplate` into this repo just to see how portability of web -> electron is

**Comment by vjtc0n** [comment]
@amilajack Thank you.

Hoping your work going well soon.

**Comment by marekhrabe** [comment]
I got it working in my app last summer, by making a custom webpack config for a web build. My specific solution, provided as-is: https://gist.github.com/marekhrabe/4a412d232d6c9f2a25d594d2a83e6ba1

Tips for integrating to your app: 
- create a task in your package.json, just like you have for electron so you can easily run it. (mine was for example `cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.web.js --progress --profile --colors`)
- try to run the app in browser and watch for errors in console. You might need to add few other modules to `node` section of the config if they fail to load
- write your app with the browser in mind - like using universal XHR, over specific node module…
- write your electron-specific features in a safe way. [is-electron](https://www.npmjs.com/package/is-electron) is a great helper for this. look at this example how you can have different implementations: https://gist.github.com/marekhrabe/64bf5c3cf497c410bc9b0194f7efdd2d

I'm not sure there is an universal solution that can be added to a boilerplate, it really depends on your app.

**Comment by lion19** [comment]
Has anyone got this working with the current version of the boilerplate? I attempted both @acao's solution of overriding the target to web and @marekhrabe's solution of a custom web config that pretty much overrides the target to web.  I additionally modified the template HTML to directly import the style.css and bundle.js.  

Both approaches result in:

    es6.number.constructor.js:20 Uncaught ReferenceError: module is not defined

The project/tooling has otherwise thus far been a dream to work with!

**Comment by amilajack** [comment]
@lion19 At the moment, I don't think there's a proven or recommended way of doing this.

**Comment by lion19** [comment]
@amilajack Got it, thanks for the response.  It does make sense to keep the web tooling separate.  I'll be sure to post here if I come up with something helpful!

**Comment by amilajack** [comment]
> It does make sense to keep the web tooling separate.

I actually think that there should be a way to do this. Its just that no one has really come up with a proven way of doing this. Also the tooling for electron and the browser are almost identical. The only difference is the target in the webpack config. Let me know if you find anything

**Comment by lion19** [comment]
@amilajack I eventually did a web build working.  I built a web config importing the production config.  Relative to the production config I overrode the 'target' of to 'web', and additionally overrode the output.libraryTarget to 'umd' (the base config sets this to 'commonjs2'), which, if I'm not mistaken, took care of the definition of 'module' in the global scope.

**Comment by Slapbox** [comment]
@lion19 Would it be possible to share your webpack configs? I'd love to help find better solutions to this for myself and other users of the boilerplate.

**Comment by lion19** [comment]
Sure @Slapbox, [here's the the web config](https://gist.github.com/lion19/0c615ebf869327c6627e02f72c082388).  I haven't factored or anything, it could very likely just merge the couple properties that differ onto the production config if that makes sense for you.  My custom [webapp.html](https://gist.github.com/lion19/c383fcb313540cf6b81014932b24c8e9) additionally needs to remove references to the process environment.  Let me know how it goes!

**Comment by Slapbox** [comment]
@lion19 thanks so much for sharing that! I won't get to that task for a couple weeks, but I'm excited to try and really thankful to have something to help guide me.

Will definitely update when I can.

**Comment by Slapbox** [comment]
Just wanted to mention there is at least one other boilerplate out there that is attacking this issue.

**Comment by Slapbox** [comment]
@lion19 do you have any updated version of this config? I know a good deal has changed in the past year and I'm hoping to take a crack at this later this month. If you've got any starting point for me that's further along, I'd love to use it to try and find a config general enough to warrant a pull request.

**Comment by Germain-Italic** [comment]
@Slapbox Have your worked on this recently?

**Comment by Slapbox** [comment]
I did eventually reach a working solution. Unfortunately I can't share it though as my project hardly resembles the boilerplate in any way anymore, and frankly, I'm not even sure the full extent of the changes it required anymore. There were changes to a number of config files.

Here's some things I know you need to do:

First: Make a new webpack.config file for web and associated commands in the package.json file.

Second: Ensure you're not loading any dependencies which won't work on the web, such as `node`'s `fs` or any native dependencies.

Here's some bits you'll need in your new webpack.config for web (Webpack 4). Obviously some parts of them can change, but things like `libraryTarget` and `target` are essential:

```js
 target: 'web',
 output: {
    path: path.join(__dirname, '../app/webdist'),
    publicPath: './webdist/',
    filename: 'web.prod.js',
    libraryTarget: 'umd',
  },
```

Sorry I don't have a ready-made solution to share. I'm happy to answer any questions you have as you try to make this work for your project though.

**Comment by Germain-Italic** [comment]
Thanks @Slapbox for pointing `libraryTarget: 'umd'`, as I was stuck with `Uncaught ReferenceError: module is not defined` error and did not understand from [the docs](https://webpack.js.org/guides/author-libraries/) what this attribute was made for.

My app is now working with Webpack's devServer in dev mode, and served by Apache when build.

Here's a comprehensive tutorial in case someone else is stuck:

# dev 

_package.json:_
```
    "dev-web": "cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-web-dev",
    "start-web-dev": "cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.web.dev.js",
```

_webpack.config.web.dev.js:_
- Copied from webpack.config.renderer.dev.js
- Imported and configured [htmlLoader](https://github.com/webpack-contrib/html-loader) plugin
- Created app/index.template.html plugin copied from app/app.html (removed both script tags)
- removed blocks related to dll, manifest, and devServer's _start-main-dev_ `before()` hook
- replaced default 1212 port by 1111 port to avoid collision when yarn dev is also running
- and of course c hange `target: 'web'`  and add `output.libraryTarget: 'umd'`as pointed out by @Slapbox 
- added devServer's option `open: true` to automatically open Chrome's window on http://localhost:1111/#/

# build

_package.json:_
```
    "build-web": "cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.web.prod.js --colors",
```

_webpack.config.web.prod.js:_
- Copied from webpack.config.renderer.prod.js
- Similar edits as per dev config (see above), except the htmlLoader which is not required
- Installed and configured [HtmlWebpackPlugin](https://github.com/jantimon/html-webpack-plugin) in order to create the final index.html file served by Apache automatically, inserting hashed references to .css and .js bundles. Plugin config : 
```
new HtmlWebpackPlugin({
      hash: true,
      title: 'My Web application',
      myPageHeader: 'Hello World',
      template: './app/index.template.html',
      filename: '../www/index.html' //relative to root of the application
    })
```

**Comment by Slapbox** [comment]
Nice work!

**Comment by acao** [comment]
here is an example I updated the other day(originally created 4 years ago.. 😮... has it been that long?)  that summarizes all of this

https://github.com/acao/webpack-web-and-electron-example

i would have seperated it out into 5 webpack config files, but i wanted to keep things as simple as possible, but this covers all of the above if anyone is looking for a working example of what @Germain-Italic is going for here! if folks would prefer a seperated out config for demonstration purposes, i can gladly do that

setting `options.output.libraryTarget` to umd isn't mandatory but a good idea, the default for webpack is `var`, which works fine in browsers

**Comment by dbvrac** [comment]
I *almost* have it. I used the process @Germain-Italic stepped through for **dev.**, including the webpack.config.web.dev.js file and it works great! I love it!
Note: `import htmlLoader from 'html-loader';` doesn't seem to be used.

However, I'm still struggling with the **build** part. It builds (so it seems), but I'm not clear how to deploy it. I've tried serving it a few different ways with `http-server` but the best I manage to get is

console: `GET http://localhost:8080/ [HTTP/1.1 200 OK 2ms]`
console: `GET http://localhost:8080/dist/web.prod.js?cbf9d1a283858d08c31a [HTTP/1.1 404 Not Found 1ms]`

**Comment by Germain-Italic** [comment]
@dbvrac could you post your prod webpack.config.prod.js?

**Comment by dbvrac** [comment]
@Germain-Italic Thanks for the info. Which version of ERB are you working with?
Setting aside my n00b issues with `Build` for a moment, I had `Dev` running quite nicely. However, this was when my project was based on ERB **v0.14.0.** I have since brought my project up to **v0.17.0** and I'm unable to get `Dev` to work. I updated the scripts in package.json to look in the new `configs` directory, but I'm uncertain how to get past this:
```
$yarn run dev-web
yarn run v1.10.1
$ cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-web-dev
/Users/username/directory/project-name/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /Users/username/directory/project-name/internals/scripts/CheckPortInUse.js: Unexpected token (6:12)
  4 | 
  5 | (function CheckPortInUse() {
> 6 |   const port: string = process.env.PORT || '1212';
    |             ^
  7 | 
  8 |   detectPort(port, (err: ?Error, availablePort: number) => {
  9 |     if (port !== String(availablePort)) {
    at Parser.pp$5.raise (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$1.parseVar (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:2342:12)
    at Parser.pp$1.parseVarStatement (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:2169:8)
    at Parser.pp$1.parseStatement (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:1861:19)
    at Parser.pp$1.parseBlockBody (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$1.parseFunction (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:2386:8)
    at Parser.pp$3.parseFunctionExpression (/Users/username/directory/project-name/node_modules/babylon/lib/index.js:3760:17)
error Command failed with exit code 1.

```

**Comment by Germain-Italic** [comment]
Hi @dbvrac my version is v0.14.0
I won't risk trying another version.

**Comment by janakg** [comment]
Hello friends, please see the changes required to enable web dev and production in a clean way for the latest release 0.17. 

I have created PR for the same. Meanwhile, you can see the changes here.
https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2136

**Comment by AshwinDeTaeye** [comment]
Hello, now the project has moved quit a bit since this discussion started.
We can now run the boilerpate within the browser by default for development. 

Is anyone now able to do the same within production? ( maybe with express)
So one .exe / .appimage that when installed runs the electron app, and host the same UI on localhost.

**Comment by cglun** [comment]
If I use ant Design, the packaged application route cannot work
